name: Run .NET unit tests
description: Runs .NET unit tests under a specified configuration

inputs:
  project:
    default: ""
    description: The test project
    required: true
  configuration:
    default: Debug
    description: The build configuration
    required: false

runs:
  using: composite
  steps:
  - run: dotnet build "${{ inputs.project }}"
      -t:Rebuild
      -p:WarningLevel=0
      -p:Configuration=${{ inputs.configuration }}
    shell: bash
  - run: dotnet test "${{ inputs.project }}"
      --no-build
      --logger "GitHubActions;report-warnings=true"
      --configuration "${{ inputs.configuration }}"
    shell: bash
