trigger:
- feature/azure-pipelines

variables:
  DOTVVM_ROOT: $(Build.SourcesDirectory)
  BUILD_CONFIGURATION: Release
  DISPLAY: :42
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  - job: testLinux
    displayName: Run tests on Linux
    pool: DockerAgentsLinux
    workspace:
      clean: all
    steps:
      env:
        GITHUB_TOKEN: $(GitHub.Token)
      - task: Cache@2
        inputs:
          key: '"npm" | "$(Agent.OS)" | src/DotVVM.Framework/package.json'
          path: $(DOTVVM_ROOT)/.npm
          restoreKeys: '"npm" | "$(Agent.OS)"'
      - task: Cache@2
        inputs:
          key: '"nuget" | "$(Agent.OS)" | **/*.csproj | **/packages.config'
          path: $(DOTVVM_ROOT)/.nuget
      - script: ./ci/linux/run.sh
        displayName: run.sh
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: $(DOTVVM_ROOT)/artifacts/test/**/*.trx
          buildConfiguration: $(BUILD_CONFIGURATION)
          testRunTitle: Linux

  - job: testWindows
    displayName: Run tests on Windows
    pool:
      name: DockerAgents
    workspace:
      clean: all
    steps:
      env:
        GITHUB_TOKEN: $(GitHub.Token)
      - task: Cache@2
        inputs:
          key: '"npm" | "$(Agent.OS)" | src/DotVVM.Framework/package.json'
          path: $(DOTVVM_ROOT)\.npm
          restoreKeys: '"npm" | "$(Agent.OS)"'
      - task: Cache@2
        inputs:
          key: '"nuget" | "$(Agent.OS)" | **/*.csproj | **/packages.config'
          path: $(DOTVVM_ROOT)/src/packages
      - powershell: .\ci\windows\run.ps1
        displayName: run.ps1
        failOnStderr: false
        errorActionPreference: continue
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: $(DOTVVM_ROOT)\artifacts\test\**\*.trx
          buildConfiguration: $(BUILD_CONFIGURATION)
          testRunTitle: Windows
