name: uitest
description: Runs DotVVM UI test with a specific profile

inputs:
  browser:
    default: chrome
    description: The name of the browser to be tested in
    required: false
  github-token:
    description: GitHub token so that test results can be uploaded
    required: true

runs:
  using: composite
  steps:

  # run the appropriate uitest script
  - if: ${{ runner.os != 'Windows' }}
    name: uitest.sh
    run: bash ./.github/uitest/uitest.sh
      --samples-profile "seleniumconfig.aspnetcorelatest.${{ inputs.browser }}.json"
      --trx-name "ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx"
    shell: bash
  - if: ${{ runner.os == 'Windows' }}
    name: uitest.ps1
    run: .\.github\uitest\uitest.ps1
      -SamplesProfile "seleniumconfig.owin.${{ inputs.browser }}.json"
      -TrxName "ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx"
    shell: pwsh

  # publish the result to github
  - uses: ./.github/test-report
    with:
      trx-path: artifacts/test/ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx
      report-name: tests-${{ inputs.browser }}-${{ runner.os }}
      report-title: UI Test Results from ${{ inputs.browser }} on ${{ runner.os }}
      github-token: ${{ inputs.github-token }}
