name: Run UI tests

inputs:
  profile:
    default: seleniumconfig.aspnetcorelatest
  browser:
    default: chrome

runs:
  using: composite
  steps:
  - if: ${{ runner.os != 'Windows' }}
    name: uitest.sh
    run: bash ./.github/uitest/uitest.sh --samples-profile ${{ inputs.profile }}.${{ inputs.browser }}.json
    shell: bash
  - if: ${{ runner.os == 'Windows' }}
    name: uitest.ps1
    run: bash ./.github/uitest/uitest.ps1 --samples-profile ${{ inputs.profile }}.${{ inputs.browser }}.json
    shell: pwsh
  # - name: Parse test results
  #   uses: NasAmin/trx-parser@v0.2.0
  #   id: trx-parser
  #   with:
  #     TRX_PATH: ${{ github.workspace }}/artifacts/test
  #     REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
