name: Run UI tests
description: Runs DotVVM UI test with a specific profile

inputs:
  browser:
    default: chrome
    description: The name of the browser to be tested in
    required: false
  token:
    description: GitHub token so that test results can be uploaded
    required: true

runs:
  using: composite
  steps:
  # browser setup
  # - if: matrix.browser == 'chromium'
  #   uses: browser-actions/setup-chromium@latest
  # - if: matrix.browser == 'firefox'
  #   uses: browser-actions/setup-firefox@latest
  # - uses: nanasess/setup-chromedriver@v1

  # run the appropriate uitest script
  - if: ${{ runner.os != 'Windows' }}
    name: uitest.sh
    run: bash ./.github/uitest/uitest.sh
      --samples-profile "seleniumconfig.aspnetcorelatest.${{ inputs.browser }}.json"
      --trx-name "ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx"
    shell: bash
  - if: ${{ runner.os == 'Windows' }}
    name: uitest.ps1
    run: .\.github\uitest\uitest.ps1
      -SamplesProfile "seleniumconfig.owin.${{ inputs.browser }}.json"
      -TrxName "ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx"
    shell: pwsh

  # publish the result to github
  - name: Make the _TMP dir
    run: mkdir ${{ github.workspace }}/_TMP
    shell: bash
  - name: Parse test results
    uses: zyborg/dotnet-tests-report@v1
    with:
      test_results_path: artifacts/test/ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx
      report_name: ui-test-results-${{ inputs.browser }}-${{ runner.os }}
      report_title: UI Test Results from ${{ inputs.browser }} on ${{ runner.os }}
      github_token: ${{ inputs.token }}
