name: uitest
description: Runs DotVVM UI test with a specific profile

inputs:
  browser:
    default: chrome
    description: The name of the browser to be tested in
    required: false
  build-configuration:
    default: Debug
    description: which --configuration to pass to dotnet build / dotnet run
    required: false
  runtime-environment:
    default: Development
    description: which --environment to pass to ASP.NET Core / dotnet run. Irrelevant on Windows, since we use OWIN there
    required: false
  samples-config:
    default: Default
    description: Determines which DotvvmConfiguration will be used in samples. See src/Samples/Common/sampleConfig.json for available options
    required: false
  github-token:
    description: GitHub token so that test results can be uploaded
    required: true

runs:
  using: composite
  steps:

  # run the appropriate uitest script
  - if: ${{ runner.os != 'Windows' }}
    name: uitest.sh
    run: bash ./.github/uitest/uitest.sh
      --samples-profile "seleniumconfig.aspnetcorelatest.${{ inputs.browser }}.json"
      --trx-name "ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx"
      --config "${{ inputs.build-configuration }}"
      --environment "${{ inputs.runtime-environment }}"
    shell: bash
    env:
      DOTVVM_SAMPLES_CONFIG_PROFILE: ${{ inputs.samples-config }}

  - if: ${{ runner.os == 'Windows' }}
    run: choco install dotnet-aspnetcoremodule-v2 -y
    shell: pwsh
  - if: ${{ runner.os == 'Windows' }}
    run: iisreset
    shell: pwsh
  - if: ${{ runner.os == 'Windows' }}
    name: uitest.ps1
    run: .\.github\uitest\uitest.ps1
      -SamplesProfile "seleniumconfig.owin.${{ inputs.browser }}.json"
      -TrxName "ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx"
      -Config "${{ inputs.build-configuration }}"
    shell: pwsh
    env:
      DOTVVM_SAMPLES_CONFIG_PROFILE: ${{ inputs.samples-config }}

  # publish the result to github
  - uses: ./.github/test-report
    with:
      trx-path: artifacts/test/ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx
      report-name: ${{ inputs.browser }}-tests-${{ runner.os }}-${{ inputs.runtime-environment }}-${{ inputs.samples-config }}
      report-title: UI Test Results from ${{ inputs.browser }} on ${{ runner.os }}
      github-token: ${{ inputs.github-token }}
