name: Run UI tests

inputs:
  profile:
    default: seleniumconfig.aspnetcorelatest
  browser:
    default: chrome
  token:
    default: null

runs:
  using: composite
  steps:
  # browser setup
  # - if: matrix.browser == 'chromium'
  #   uses: browser-actions/setup-chromium@latest
  # - if: matrix.browser == 'firefox'
  #   uses: browser-actions/setup-firefox@latest

  # run the appropriate uitest script
  - if: ${{ runner.os != 'Windows' }}
    name: uitest.sh
    run: bash ./.github/uitest/uitest.sh
      --samples-profile "${{ inputs.profile }}.${{ inputs.browser }}.json"
      --trx-name "ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx"
    shell: bash
  - if: ${{ runner.os == 'Windows' }}
    name: uitest.ps1
    run: .\.github\uitest\uitest.ps1
      -SamplesProfile "${{ inputs.profile }}.${{ inputs.browser }}.json"
      -TrxName "ui-test-results-${{ inputs.browser }}-${{ runner.os }}.trx"
    shell: pwsh

  # publish the result to github
  - name: Parse test results
    uses: NasAmin/trx-parser@v0.2.0
    id: trx-parser
    with:
      TRX_PATH: ${{ github.workspace }}/artifacts/test
      REPO_TOKEN: ${{ inputs.token }}
