var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var DotVVM;
(function (DotVVM) {
    var Samples;
    (function (Samples) {
        var Common;
        (function (Common) {
            var Api;
            (function (Api) {
                var AspNetCore;
                (function (AspNetCore) {
                    var ClientBase = /** @class */ (function () {
                        function ClientBase() {
                        }
                        ClientBase.prototype.transformOptions = function (options) {
                            options.credentials = "same-origin";
                            return Promise.resolve(options);
                        };
                        return ClientBase;
                    }());
                    /* tslint:disable */
                    /* eslint-disable */
                    //----------------------
                    // <auto-generated>
                    //     Generated using the NSwag toolchain v13.13.2.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
                    // </auto-generated>
                    //----------------------
                    // ReSharper disable InconsistentNaming
                    var TestWebApiClientAspNetCore = /** @class */ (function (_super) {
                        __extends(TestWebApiClientAspNetCore, _super);
                        function TestWebApiClientAspNetCore(baseUrl, http) {
                            var _this = _super.call(this) || this;
                            _this.jsonParseReviver = undefined;
                            _this.http = http ? http : window;
                            _this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "http://localhost:5001";
                            return _this;
                        }
                        /**
                         * @param category (optional)
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.bindingSharingGetGet = function (category) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/BindingSharing/get?";
                            if (category !== undefined && category !== null)
                                url_ += "category=" + encodeURIComponent("" + category) + "&";
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "GET",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processBindingSharingGetGet(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processBindingSharingGetGet = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    if (Array.isArray(resultData200)) {
                                        result200 = [];
                                        for (var _i = 0, resultData200_1 = resultData200; _i < resultData200_1.length; _i++) {
                                            var item = resultData200_1[_i];
                                            result200.push(BindingSharingItemDTO.fromJS(item));
                                        }
                                    }
                                    else {
                                        result200 = null;
                                    }
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.bindingSharingGetGetWithRouteParam = function (category) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/BindingSharing/getWithRouteParam/{category}";
                            if (category === undefined || category === null)
                                throw new Error("The parameter 'category' must be defined.");
                            url_ = url_.replace("{category}", encodeURIComponent("" + category));
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "GET",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processBindingSharingGetGetWithRouteParam(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processBindingSharingGetGetWithRouteParam = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    if (Array.isArray(resultData200)) {
                                        result200 = [];
                                        for (var _i = 0, resultData200_2 = resultData200; _i < resultData200_2.length; _i++) {
                                            var item = resultData200_2[_i];
                                            result200.push(BindingSharingItemDTO.fromJS(item));
                                        }
                                    }
                                    else {
                                        result200 = null;
                                    }
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @param category (optional)
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.bindingSharingPostPost = function (category) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/BindingSharing/post?";
                            if (category !== undefined && category !== null)
                                url_ += "category=" + encodeURIComponent("" + category) + "&";
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "POST",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processBindingSharingPostPost(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processBindingSharingPostPost = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    if (Array.isArray(resultData200)) {
                                        result200 = [];
                                        for (var _i = 0, resultData200_3 = resultData200; _i < resultData200_3.length; _i++) {
                                            var item = resultData200_3[_i];
                                            result200.push(BindingSharingItemDTO.fromJS(item));
                                        }
                                    }
                                    else {
                                        result200 = null;
                                    }
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.getCompanies = function () {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Companies";
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "GET",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processGetCompanies(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processGetCompanies = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    if (Array.isArray(resultData200)) {
                                        result200 = [];
                                        for (var _i = 0, resultData200_4 = resultData200; _i < resultData200_4.length; _i++) {
                                            var item = resultData200_4[_i];
                                            result200.push(CompanyOfString.fromJS(item));
                                        }
                                    }
                                    else {
                                        result200 = null;
                                    }
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @param sortingOptions (optional)
                         * @param sortingOptions_SortDescending (optional)
                         * @param sortingOptions_SortExpression (optional)
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.companiesGetSorted = function (sortingOptions, sortingOptions_SortDescending, sortingOptions_SortExpression) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Companies/sorted?";
                            if (sortingOptions !== undefined && sortingOptions !== null)
                                url_ += "sortingOptions=" + encodeURIComponent("" + sortingOptions) + "&";
                            if (sortingOptions_SortDescending !== undefined && sortingOptions_SortDescending !== null)
                                url_ += "sortingOptions.SortDescending=" + encodeURIComponent("" + sortingOptions_SortDescending) + "&";
                            if (sortingOptions_SortExpression !== undefined && sortingOptions_SortExpression !== null)
                                url_ += "sortingOptions.SortExpression=" + encodeURIComponent("" + sortingOptions_SortExpression) + "&";
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "GET",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processCompaniesGetSorted(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processCompaniesGetSorted = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    result200 = GridViewDataSetOfCompanyOfBoolean.fromJS(resultData200);
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @param pagingOptions (optional)
                         * @param pagingOptions_PageIndex (optional)
                         * @param pagingOptions_PageSize (optional)
                         * @param pagingOptions_TotalItemsCount (optional)
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.companiesGetPaged = function (pagingOptions, pagingOptions_PageIndex, pagingOptions_PageSize, pagingOptions_TotalItemsCount) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Companies/paged?";
                            if (pagingOptions !== undefined && pagingOptions !== null)
                                url_ += "pagingOptions=" + encodeURIComponent("" + pagingOptions) + "&";
                            if (pagingOptions_PageIndex !== undefined && pagingOptions_PageIndex !== null)
                                url_ += "pagingOptions.PageIndex=" + encodeURIComponent("" + pagingOptions_PageIndex) + "&";
                            if (pagingOptions_PageSize !== undefined && pagingOptions_PageSize !== null)
                                url_ += "pagingOptions.PageSize=" + encodeURIComponent("" + pagingOptions_PageSize) + "&";
                            if (pagingOptions_TotalItemsCount !== undefined && pagingOptions_TotalItemsCount !== null)
                                url_ += "pagingOptions.TotalItemsCount=" + encodeURIComponent("" + pagingOptions_TotalItemsCount) + "&";
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "GET",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processCompaniesGetPaged(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processCompaniesGetPaged = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    result200 = GridViewDataSetOfCompanyOfString.fromJS(resultData200);
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @param sortingOptions (optional)
                         * @param sortingOptions_SortDescending (optional)
                         * @param sortingOptions_SortExpression (optional)
                         * @param pagingOptions (optional)
                         * @param pagingOptions_PageIndex (optional)
                         * @param pagingOptions_PageSize (optional)
                         * @param pagingOptions_TotalItemsCount (optional)
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.companiesGetSortedandpaged = function (sortingOptions, sortingOptions_SortDescending, sortingOptions_SortExpression, pagingOptions, pagingOptions_PageIndex, pagingOptions_PageSize, pagingOptions_TotalItemsCount) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Companies/sortedandpaged?";
                            if (sortingOptions !== undefined && sortingOptions !== null)
                                url_ += "sortingOptions=" + encodeURIComponent("" + sortingOptions) + "&";
                            if (sortingOptions_SortDescending !== undefined && sortingOptions_SortDescending !== null)
                                url_ += "sortingOptions.SortDescending=" + encodeURIComponent("" + sortingOptions_SortDescending) + "&";
                            if (sortingOptions_SortExpression !== undefined && sortingOptions_SortExpression !== null)
                                url_ += "sortingOptions.SortExpression=" + encodeURIComponent("" + sortingOptions_SortExpression) + "&";
                            if (pagingOptions !== undefined && pagingOptions !== null)
                                url_ += "pagingOptions=" + encodeURIComponent("" + pagingOptions) + "&";
                            if (pagingOptions_PageIndex !== undefined && pagingOptions_PageIndex !== null)
                                url_ += "pagingOptions.PageIndex=" + encodeURIComponent("" + pagingOptions_PageIndex) + "&";
                            if (pagingOptions_PageSize !== undefined && pagingOptions_PageSize !== null)
                                url_ += "pagingOptions.PageSize=" + encodeURIComponent("" + pagingOptions_PageSize) + "&";
                            if (pagingOptions_TotalItemsCount !== undefined && pagingOptions_TotalItemsCount !== null)
                                url_ += "pagingOptions.TotalItemsCount=" + encodeURIComponent("" + pagingOptions_TotalItemsCount) + "&";
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "GET",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processCompaniesGetSortedandpaged(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processCompaniesGetSortedandpaged = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    result200 = GridViewDataSetOfCompanyOfString.fromJS(resultData200);
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @param companyId (optional)
                         * @param pageIndex (optional)
                         * @param pageSize (optional)
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.getOrdersAll = function (companyId, pageIndex, pageSize) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Orders?";
                            if (companyId !== undefined && companyId !== null)
                                url_ += "companyId=" + encodeURIComponent("" + companyId) + "&";
                            if (pageIndex !== undefined && pageIndex !== null)
                                url_ += "pageIndex=" + encodeURIComponent("" + pageIndex) + "&";
                            if (pageSize !== undefined && pageSize !== null)
                                url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "GET",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processGetOrdersAll(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processGetOrdersAll = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    if (Array.isArray(resultData200)) {
                                        result200 = [];
                                        for (var _i = 0, resultData200_5 = resultData200; _i < resultData200_5.length; _i++) {
                                            var item = resultData200_5[_i];
                                            result200.push(Order.fromJS(item));
                                        }
                                    }
                                    else {
                                        result200 = null;
                                    }
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @param body (optional)
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.postOrders = function (body) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Orders";
                            url_ = url_.replace(/[?&]$/, "");
                            var content_ = JSON.stringify(body);
                            var options_ = {
                                body: content_,
                                method: "POST",
                                headers: {
                                    "Content-Type": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processPostOrders(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processPostOrders = function (response) {
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    return;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.getOrders = function (orderId) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Orders/{orderId}";
                            if (orderId === undefined || orderId === null)
                                throw new Error("The parameter 'orderId' must be defined.");
                            url_ = url_.replace("{orderId}", encodeURIComponent("" + orderId));
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "GET",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processGetOrders(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processGetOrders = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    result200 = Order.fromJS(resultData200);
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @param body (optional)
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.putOrders = function (orderId, body) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Orders/{orderId}";
                            if (orderId === undefined || orderId === null)
                                throw new Error("The parameter 'orderId' must be defined.");
                            url_ = url_.replace("{orderId}", encodeURIComponent("" + orderId));
                            url_ = url_.replace(/[?&]$/, "");
                            var content_ = JSON.stringify(body);
                            var options_ = {
                                body: content_,
                                method: "PUT",
                                headers: {
                                    "Content-Type": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processPutOrders(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processPutOrders = function (response) {
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    return;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.ordersDeleteDelete = function (orderId) {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Orders/delete/{orderId}";
                            if (orderId === undefined || orderId === null)
                                throw new Error("The parameter 'orderId' must be defined.");
                            url_ = url_.replace("{orderId}", encodeURIComponent("" + orderId));
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "DELETE",
                                headers: {}
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processOrdersDeleteDelete(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processOrdersDeleteDelete = function (response) {
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    return;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        /**
                         * @return Success
                         */
                        TestWebApiClientAspNetCore.prototype.slowPostRandomNumber = function () {
                            var _this = this;
                            var url_ = this.baseUrl + "/api/Slow/random-number";
                            url_ = url_.replace(/[?&]$/, "");
                            var options_ = {
                                method: "POST",
                                headers: {
                                    "Accept": "application/json"
                                }
                            };
                            return this.transformOptions(options_).then(function (transformedOptions_) {
                                return _this.http.fetch(url_, transformedOptions_);
                            }).then(function (_response) {
                                return _this.processSlowPostRandomNumber(_response);
                            });
                        };
                        TestWebApiClientAspNetCore.prototype.processSlowPostRandomNumber = function (response) {
                            var _this = this;
                            var status = response.status;
                            var _headers = {};
                            if (response.headers && response.headers.forEach) {
                                response.headers.forEach(function (v, k) { return _headers[k] = v; });
                            }
                            ;
                            if (status === 200) {
                                return response.text().then(function (_responseText) {
                                    var result200 = null;
                                    var resultData200 = _responseText === "" ? null : JSON.parse(_responseText, _this.jsonParseReviver);
                                    result200 = resultData200 !== undefined ? resultData200 : null;
                                    return result200;
                                });
                            }
                            else if (status !== 200 && status !== 204) {
                                return response.text().then(function (_responseText) {
                                    return throwException("An unexpected server error occurred.", status, _responseText, _headers);
                                });
                            }
                            return Promise.resolve(null);
                        };
                        return TestWebApiClientAspNetCore;
                    }(ClientBase));
                    AspNetCore.TestWebApiClientAspNetCore = TestWebApiClientAspNetCore;
                    var BindingSharingItemDTO = /** @class */ (function () {
                        function BindingSharingItemDTO(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        BindingSharingItemDTO.prototype.init = function (_data) {
                            if (_data) {
                                this.id = _data["id"] !== undefined ? _data["id"] : null;
                                this.name = _data["name"] !== undefined ? _data["name"] : null;
                            }
                        };
                        BindingSharingItemDTO.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new BindingSharingItemDTO();
                            result.init(data);
                            return result;
                        };
                        BindingSharingItemDTO.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["id"] = this.id !== undefined ? this.id : null;
                            data["name"] = this.name !== undefined ? this.name : null;
                            return data;
                        };
                        return BindingSharingItemDTO;
                    }());
                    AspNetCore.BindingSharingItemDTO = BindingSharingItemDTO;
                    var CompanyOfBoolean = /** @class */ (function () {
                        function CompanyOfBoolean(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        CompanyOfBoolean.prototype.init = function (_data) {
                            if (_data) {
                                this.id = _data["id"] !== undefined ? _data["id"] : null;
                                this.name = _data["name"] !== undefined ? _data["name"] : null;
                                this.owner = _data["owner"] !== undefined ? _data["owner"] : null;
                                this.department = _data["department"] !== undefined ? _data["department"] : null;
                            }
                        };
                        CompanyOfBoolean.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new CompanyOfBoolean();
                            result.init(data);
                            return result;
                        };
                        CompanyOfBoolean.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["id"] = this.id !== undefined ? this.id : null;
                            data["name"] = this.name !== undefined ? this.name : null;
                            data["owner"] = this.owner !== undefined ? this.owner : null;
                            data["department"] = this.department !== undefined ? this.department : null;
                            return data;
                        };
                        return CompanyOfBoolean;
                    }());
                    AspNetCore.CompanyOfBoolean = CompanyOfBoolean;
                    var CompanyOfString = /** @class */ (function () {
                        function CompanyOfString(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        CompanyOfString.prototype.init = function (_data) {
                            if (_data) {
                                this.Id = _data["id"] !== undefined ? _data["id"] : null;
                                this.Name = _data["name"] !== undefined ? _data["name"] : null;
                                this.Owner = _data["owner"] !== undefined ? _data["owner"] : null;
                                this.Department = _data["department"] !== undefined ? _data["department"] : null;
                            }
                        };
                        CompanyOfString.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new CompanyOfString();
                            result.init(data);
                            return result;
                        };
                        CompanyOfString.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["id"] = this.Id !== undefined ? this.Id : null;
                            data["name"] = this.Name !== undefined ? this.Name : null;
                            data["owner"] = this.Owner !== undefined ? this.Owner : null;
                            data["department"] = this.Department !== undefined ? this.Department : null;
                            return data;
                        };
                        return CompanyOfString;
                    }());
                    AspNetCore.CompanyOfString = CompanyOfString;
                    var GridViewDataSetOfCompanyOfBoolean = /** @class */ (function () {
                        function GridViewDataSetOfCompanyOfBoolean(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        GridViewDataSetOfCompanyOfBoolean.prototype.init = function (_data) {
                            if (_data) {
                                this.IsRefreshRequired = _data["isRefreshRequired"] !== undefined ? _data["isRefreshRequired"] : null;
                                if (Array.isArray(_data["items"])) {
                                    this.Items = [];
                                    for (var _i = 0, _a = _data["items"]; _i < _a.length; _i++) {
                                        var item = _a[_i];
                                        this.Items.push(CompanyOfBoolean.fromJS(item));
                                    }
                                }
                                else {
                                    this.Items = null;
                                }
                                this.pagingOptions = _data["pagingOptions"] ? IPagingOptions.fromJS(_data["pagingOptions"]) : null;
                                this.rowEditOptions = _data["rowEditOptions"] ? IRowEditOptions.fromJS(_data["rowEditOptions"]) : null;
                                this.sortingOptions = _data["sortingOptions"] ? ISortingOptions.fromJS(_data["sortingOptions"]) : null;
                            }
                        };
                        GridViewDataSetOfCompanyOfBoolean.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new GridViewDataSetOfCompanyOfBoolean();
                            result.init(data);
                            return result;
                        };
                        GridViewDataSetOfCompanyOfBoolean.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["isRefreshRequired"] = this.IsRefreshRequired !== undefined ? this.IsRefreshRequired : null;
                            if (Array.isArray(this.Items)) {
                                data["items"] = [];
                                for (var _i = 0, _a = this.Items; _i < _a.length; _i++) {
                                    var item = _a[_i];
                                    data["items"].push(item.toJSON());
                                }
                            }
                            data["pagingOptions"] = this.pagingOptions ? this.pagingOptions.toJSON() : null;
                            data["rowEditOptions"] = this.rowEditOptions ? this.rowEditOptions.toJSON() : null;
                            data["sortingOptions"] = this.sortingOptions ? this.sortingOptions.toJSON() : null;
                            return data;
                        };
                        return GridViewDataSetOfCompanyOfBoolean;
                    }());
                    AspNetCore.GridViewDataSetOfCompanyOfBoolean = GridViewDataSetOfCompanyOfBoolean;
                    var GridViewDataSetOfCompanyOfString = /** @class */ (function () {
                        function GridViewDataSetOfCompanyOfString(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        GridViewDataSetOfCompanyOfString.prototype.init = function (_data) {
                            if (_data) {
                                this.IsRefreshRequired = _data["isRefreshRequired"] !== undefined ? _data["isRefreshRequired"] : null;
                                if (Array.isArray(_data["items"])) {
                                    this.Items = [];
                                    for (var _i = 0, _a = _data["items"]; _i < _a.length; _i++) {
                                        var item = _a[_i];
                                        this.Items.push(CompanyOfString.fromJS(item));
                                    }
                                }
                                else {
                                    this.Items = null;
                                }
                                this.pagingOptions = _data["pagingOptions"] ? IPagingOptions.fromJS(_data["pagingOptions"]) : null;
                                this.rowEditOptions = _data["rowEditOptions"] ? IRowEditOptions.fromJS(_data["rowEditOptions"]) : null;
                                this.sortingOptions = _data["sortingOptions"] ? ISortingOptions.fromJS(_data["sortingOptions"]) : null;
                            }
                        };
                        GridViewDataSetOfCompanyOfString.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new GridViewDataSetOfCompanyOfString();
                            result.init(data);
                            return result;
                        };
                        GridViewDataSetOfCompanyOfString.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["isRefreshRequired"] = this.IsRefreshRequired !== undefined ? this.IsRefreshRequired : null;
                            if (Array.isArray(this.Items)) {
                                data["items"] = [];
                                for (var _i = 0, _a = this.Items; _i < _a.length; _i++) {
                                    var item = _a[_i];
                                    data["items"].push(item.toJSON());
                                }
                            }
                            data["pagingOptions"] = this.pagingOptions ? this.pagingOptions.toJSON() : null;
                            data["rowEditOptions"] = this.rowEditOptions ? this.rowEditOptions.toJSON() : null;
                            data["sortingOptions"] = this.sortingOptions ? this.sortingOptions.toJSON() : null;
                            return data;
                        };
                        return GridViewDataSetOfCompanyOfString;
                    }());
                    AspNetCore.GridViewDataSetOfCompanyOfString = GridViewDataSetOfCompanyOfString;
                    var INearPageIndexesProvider = /** @class */ (function () {
                        function INearPageIndexesProvider(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        INearPageIndexesProvider.prototype.init = function (_data) {
                        };
                        INearPageIndexesProvider.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new INearPageIndexesProvider();
                            result.init(data);
                            return result;
                        };
                        INearPageIndexesProvider.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            return data;
                        };
                        return INearPageIndexesProvider;
                    }());
                    AspNetCore.INearPageIndexesProvider = INearPageIndexesProvider;
                    var IPagingOptions = /** @class */ (function () {
                        function IPagingOptions(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        IPagingOptions.prototype.init = function (_data) {
                            if (_data) {
                                this.PageIndex = _data["pageIndex"] !== undefined ? _data["pageIndex"] : null;
                                this.PageSize = _data["pageSize"] !== undefined ? _data["pageSize"] : null;
                                this.TotalItemsCount = _data["totalItemsCount"] !== undefined ? _data["totalItemsCount"] : null;
                                this.IsFirstPage = _data["isFirstPage"] !== undefined ? _data["isFirstPage"] : null;
                                this.IsLastPage = _data["isLastPage"] !== undefined ? _data["isLastPage"] : null;
                                this.PagesCount = _data["pagesCount"] !== undefined ? _data["pagesCount"] : null;
                                if (Array.isArray(_data["nearPageIndexes"])) {
                                    this.NearPageIndexes = [];
                                    for (var _i = 0, _a = _data["nearPageIndexes"]; _i < _a.length; _i++) {
                                        var item = _a[_i];
                                        this.NearPageIndexes.push(item);
                                    }
                                }
                                else {
                                    this.NearPageIndexes = null;
                                }
                            }
                        };
                        IPagingOptions.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new IPagingOptions();
                            result.init(data);
                            return result;
                        };
                        IPagingOptions.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["pageIndex"] = this.PageIndex !== undefined ? this.PageIndex : null;
                            data["pageSize"] = this.PageSize !== undefined ? this.PageSize : null;
                            data["totalItemsCount"] = this.TotalItemsCount !== undefined ? this.TotalItemsCount : null;
                            data["isFirstPage"] = this.IsFirstPage !== undefined ? this.IsFirstPage : null;
                            data["isLastPage"] = this.IsLastPage !== undefined ? this.IsLastPage : null;
                            data["pagesCount"] = this.PagesCount !== undefined ? this.PagesCount : null;
                            if (Array.isArray(this.NearPageIndexes)) {
                                data["nearPageIndexes"] = [];
                                for (var _i = 0, _a = this.NearPageIndexes; _i < _a.length; _i++) {
                                    var item = _a[_i];
                                    data["nearPageIndexes"].push(item);
                                }
                            }
                            return data;
                        };
                        return IPagingOptions;
                    }());
                    AspNetCore.IPagingOptions = IPagingOptions;
                    var IRowEditOptions = /** @class */ (function () {
                        function IRowEditOptions(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        IRowEditOptions.prototype.init = function (_data) {
                            if (_data) {
                                this.PrimaryKeyPropertyName = _data["primaryKeyPropertyName"] !== undefined ? _data["primaryKeyPropertyName"] : null;
                                this.EditRowId = _data["editRowId"] !== undefined ? _data["editRowId"] : null;
                            }
                        };
                        IRowEditOptions.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new IRowEditOptions();
                            result.init(data);
                            return result;
                        };
                        IRowEditOptions.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["primaryKeyPropertyName"] = this.PrimaryKeyPropertyName !== undefined ? this.PrimaryKeyPropertyName : null;
                            data["editRowId"] = this.EditRowId !== undefined ? this.EditRowId : null;
                            return data;
                        };
                        return IRowEditOptions;
                    }());
                    AspNetCore.IRowEditOptions = IRowEditOptions;
                    var ISortingOptions = /** @class */ (function () {
                        function ISortingOptions(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        ISortingOptions.prototype.init = function (_data) {
                            if (_data) {
                                this.SortDescending = _data["sortDescending"] !== undefined ? _data["sortDescending"] : null;
                                this.SortExpression = _data["sortExpression"] !== undefined ? _data["sortExpression"] : null;
                            }
                        };
                        ISortingOptions.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new ISortingOptions();
                            result.init(data);
                            return result;
                        };
                        ISortingOptions.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["sortDescending"] = this.SortDescending !== undefined ? this.SortDescending : null;
                            data["sortExpression"] = this.SortExpression !== undefined ? this.SortExpression : null;
                            return data;
                        };
                        return ISortingOptions;
                    }());
                    AspNetCore.ISortingOptions = ISortingOptions;
                    var Order = /** @class */ (function () {
                        function Order(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        Order.prototype.init = function (_data) {
                            if (_data) {
                                this.id = _data["id"] !== undefined ? _data["id"] : null;
                                this.Number = _data["Number"] !== undefined ? _data["Number"] : null;
                                this.date = _data["date"] ? new Date(_data["date"].toString()) : null;
                                this.companyId = _data["companyId"] !== undefined ? _data["companyId"] : null;
                                if (Array.isArray(_data["orderItems"])) {
                                    this.orderItems = [];
                                    for (var _i = 0, _a = _data["orderItems"]; _i < _a.length; _i++) {
                                        var item = _a[_i];
                                        this.orderItems.push(OrderItem.fromJS(item));
                                    }
                                }
                                else {
                                    this.orderItems = null;
                                }
                            }
                        };
                        Order.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new Order();
                            result.init(data);
                            return result;
                        };
                        Order.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["id"] = this.id !== undefined ? this.id : null;
                            data["Number"] = this.Number !== undefined ? this.Number : null;
                            data["date"] = this.date ? this.date.toISOString() : null;
                            data["companyId"] = this.companyId !== undefined ? this.companyId : null;
                            if (Array.isArray(this.orderItems)) {
                                data["orderItems"] = [];
                                for (var _i = 0, _a = this.orderItems; _i < _a.length; _i++) {
                                    var item = _a[_i];
                                    data["orderItems"].push(item.toJSON());
                                }
                            }
                            return data;
                        };
                        return Order;
                    }());
                    AspNetCore.Order = Order;
                    var OrderItem = /** @class */ (function () {
                        function OrderItem(data) {
                            if (data) {
                                for (var property in data) {
                                    if (data.hasOwnProperty(property))
                                        this[property] = data[property];
                                }
                            }
                        }
                        OrderItem.prototype.init = function (_data) {
                            if (_data) {
                                this.id = _data["id"] !== undefined ? _data["id"] : null;
                                this.text = _data["text"] !== undefined ? _data["text"] : null;
                                this.amount = _data["amount"] !== undefined ? _data["amount"] : null;
                                this.discount = _data["discount"] !== undefined ? _data["discount"] : null;
                                this.isOnStock = _data["isOnStock"] !== undefined ? _data["isOnStock"] : null;
                            }
                        };
                        OrderItem.fromJS = function (data) {
                            data = typeof data === 'object' ? data : {};
                            var result = new OrderItem();
                            result.init(data);
                            return result;
                        };
                        OrderItem.prototype.toJSON = function (data) {
                            data = typeof data === 'object' ? data : {};
                            data["id"] = this.id !== undefined ? this.id : null;
                            data["text"] = this.text !== undefined ? this.text : null;
                            data["amount"] = this.amount !== undefined ? this.amount : null;
                            data["discount"] = this.discount !== undefined ? this.discount : null;
                            data["isOnStock"] = this.isOnStock !== undefined ? this.isOnStock : null;
                            return data;
                        };
                        return OrderItem;
                    }());
                    AspNetCore.OrderItem = OrderItem;
                    var ApiException = /** @class */ (function (_super) {
                        __extends(ApiException, _super);
                        function ApiException(message, status, response, headers, result) {
                            var _this = _super.call(this) || this;
                            _this.isApiException = true;
                            _this.message = message;
                            _this.status = status;
                            _this.response = response;
                            _this.headers = headers;
                            _this.result = result;
                            return _this;
                        }
                        ApiException.isApiException = function (obj) {
                            return obj.isApiException === true;
                        };
                        return ApiException;
                    }(Error));
                    AspNetCore.ApiException = ApiException;
                    function throwException(message, status, response, headers, result) {
                        if (result !== null && result !== undefined)
                            throw result;
                        else
                            throw new ApiException(message, status, response, headers, null);
                    }
                })(AspNetCore = Api.AspNetCore || (Api.AspNetCore = {}));
            })(Api = Common.Api || (Common.Api = {}));
        })(Common = Samples.Common || (Samples.Common = {}));
    })(Samples = DotVVM.Samples || (DotVVM.Samples = {}));
})(DotVVM || (DotVVM = {}));
