<Project Sdk="Microsoft.NET.Sdk">
  <!--Related to compilation-->
  <PropertyGroup>
    <AssemblyTitle>DotVVM.CommandLine</AssemblyTitle>
    <AssemblyName>dotnet-dotvvm</AssemblyName>
    <TargetFramework>$(DotnetCoreTargetVersion)</TargetFramework>
    <AssemblyOriginatorKeyFile>dotvvmwizard.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <!--Related to packaging-->
  <PropertyGroup>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dotvvm</ToolCommandName>
    <PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>
    <PackageId>DotVVM.CommandLine</PackageId>
    <Description>Command-line tools for DotVVM.</Description>
    <PackageTags>$(PackageTags);cli</PackageTags>
    <RollForward>Major</RollForward> <!-- allows running on newer .NET version if the requested net6.0 is not installed -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSwag.CodeGeneration.CSharp" Version="13.13.2" />
    <PackageReference Include="NSwag.CodeGeneration.Typescript" Version="13.13.2" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NuGet.Frameworks" Version="5.9.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
    <PackageReference Include="vswhere" Version="3.1.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(VSWhereDir)vswhere.exe" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Framework/Framework/DotVVM.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**/*.liquid" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\DotVVMCommandLine.targets" />
  </ItemGroup>

</Project>
