name: Set up DotVVM build

inputs:
  sln:
    default: src/DotVVM.sln

runs:
  using: composite
  steps:
  # nuget-related
  - run: echo "::group::Caching"
    shell: bash
  - uses: actions/cache@v2
    with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget
  - if: ${{ runner.os == 'Windows' }}
    uses: actions/cache@v2
    with:
      path: src/packages
      key: nuget-old-style-packages
  - run: echo "::endgroup::"
    shell: bash

  # .NET-related
  - run: echo "::group::.NET"
    shell: bash
  - uses: actions/setup-dotnet@v1
    with:
      dotnet-version: |
        5.0.403
        6.0.100
  - if: ${{ runner.os == 'Windows' }}
    uses: microsoft/setup-msbuild@v1.1
  - run: echo "::endgroup::"
    shell: bash

  # restore packages
  - run: echo "::group::Restore packages"
    shell: bash
  - if: ${{ runner.os == 'Windows' }}
    uses: nuget/setup-nuget@v1
  - if: ${{ runner.os == 'Windows' }}
    run: nuget restore ${{ inputs.sln }}
    shell: pwsh
  - if: ${{ runner.os != 'Windows' }}
    run: dotnet restore ${{ inputs.sln }}
    shell: bash
  - run: echo "::endgroup::"
    shell: bash

