name: setup
description: Sets up the build environment for the DotVVM repo.

inputs:
  sln:
    default: src/DotVVM.sln
    description: Path to a Visual Studio solution
    required: false

runs:
  using: composite
  steps:

  # nuget
  - uses: nuget/setup-nuget@v1
    with:
      nuget-version: '6.x'
  - uses: actions/cache@v3
    id: nuget-cache
    with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
      restore-keys: ${{ runner.os }}-nuget-

  # Node.js
  - uses: actions/setup-node@v3
    with:
      node-version: 18
  - run: |
      corepack enable
      yarn set version stable
    shell: bash

  # .NET
  - uses: actions/setup-dotnet@v4
    with:
      dotnet-version: |
        8.0.x
        6.0.x
  - if: ${{ runner.os == 'Windows' }}
    uses: microsoft/setup-msbuild@v1.1

  # restore nuget packages
  - if: ${{ runner.os == 'Windows' }}
    run: msbuild ${{ inputs.sln }} -t:Restore
    shell: pwsh
  - if: ${{ runner.os != 'Windows' }}
    run: dotnet restore ${{ inputs.sln }}
    shell: bash

  # restore dotnet tools
  - run: dotnet tool restore
    shell: pwsh
    working-directory: src/
