name: clitests
description: Builds and runs the DotVVM CommandLine tests

runs:
  using: composite
  steps:
  - name: Build Compiler
    run: dotnet build
      src/Tools/Compiler/DotVVM.Compiler.csproj
      --no-restore
      --configuration Debug
      -p:WarningLevel=0
    shell: bash
  - name: Build CommandLine
    run: dotnet build
      src/Tools/CommandLine/DotVVM.CommandLine.csproj
      --framework net8.0
      --no-restore
      --configuration Debug
      -p:WarningLevel=0
    shell: bash
  - name: Build CommandLine.Tests
    run: dotnet build
      src/Tools/Tests/CommandLine/DotVVM.CommandLine.Tests.csproj
      --framework net8.0
      --no-restore
      --configuration Debug
      -p:WarningLevel=0
    shell: bash
  - name: Run CommandLine.Tests (Debug)
    run: dotnet test
      src/Tools/Tests/CommandLine/DotVVM.CommandLine.Tests.csproj
      --framework net8.0
      --no-restore
      --logger "GitHubActions;report-warnings=true"
      --logger "trx;LogFileName=${{ github.workspace }}/artifacts/test/unit-test-results-commandline-tests-net8.0-Debug.trx"
      --configuration Debug
      -p:WarningLevel=0
    shell: bash

