using System;
using System.Collections.Generic;
using System.Linq;
using DotVVM.Framework.Binding;
using DotVVM.Framework.Hosting;
using DotVVM.Framework.Parser;
using DotVVM.Framework.Runtime;

namespace DotVVM.Framework.Controls.Bootstrap
{
    public class GlyphIcon : HtmlGenericControl
    {

        public GlyphIcons Icon
        {
            get { return (GlyphIcons)GetValue(IconProperty); }
            set { SetValue(IconProperty, value); }
        }
        public static readonly DotvvmProperty IconProperty =
            DotvvmProperty.Register<GlyphIcons, GlyphIcon>(t => t.Icon, GlyphIcons.Empty);


        public GlyphIcon() : base("span")
        {
            ResourceDependencies.Add(Constants.BootstrapResourceName);
        }

        protected override void AddAttributesToRender(IHtmlWriter writer, RenderContext context)
        {
            if (Icon != GlyphIcons.Empty)
            {
                var iconName = KnockoutHelper.ConvertToCamelCase(Icon.ToString().Replace("_", "-"));
                writer.AddAttribute("class", "glyphicon glyphicon-" + iconName);
            }
            base.AddAttributesToRender(writer, context);
        }
    }

    public enum GlyphIcons
    {
        Empty,
        Asterisk,
        Plus,
        Euro,
        Minus,
        Cloud,
        Envelope,
        Pencil,
        Glass,
        Music,
        Search,
        Heart,
        Star,
        Star_empty,
        User,
        Film,
        Th_large,
        Th,
        Th_list,
        Ok,
        Remove,
        Zoom_in,
        Zoom_out,
        Off,
        Signal,
        Cog,
        Trash,
        Home,
        File,
        Time,
        Road,
        Download_alt,
        Download,
        Upload,
        Inbox,
        Play_circle,
        Repeat,
        Refresh,
        List_alt,
        Lock,
        Flag,
        Headphones,
        Volume_off,
        Volume_down,
        Volume_up,
        Qrcode,
        Barcode,
        Tag,
        Tags,
        Book,
        Bookmark,
        Print,
        Camera,
        Font,
        Bold,
        Italic,
        Text_height,
        Text_width,
        Align_left,
        Align_center,
        Align_right,
        Align_justify,
        List,
        Indent_left,
        Indent_right,
        Facetime_video,
        Picture,
        Map_marker,
        Adjust,
        Tint,
        Edit,
        Share,
        Check,
        Move,
        Step_backward,
        Fast_backward,
        Backward,
        Play,
        Pause,
        Stop,
        Forward,
        Fast_forward,
        Step_forward,
        Eject,
        Chevron_left,
        Chevron_right,
        Plus_sign,
        Minus_sign,
        Remove_sign,
        Ok_sign,
        Question_sign,
        Info_sign,
        Screenshot,
        Remove_circle,
        Ok_circle,
        Ban_circle,
        Arrow_left,
        Arrow_right,
        Arrow_up,
        Arrow_down,
        Share_alt,
        Resize_full,
        Resize_small,
        Exclamation_sign,
        Gift,
        Leaf,
        Fire,
        Eye_open,
        Eye_close,
        Warning_sign,
        Plane,
        Calendar,
        Random,
        Comment,
        Magnet,
        Chevron_up,
        Chevron_down,
        Retweet,
        Shopping_cart,
        Folder_close,
        Folder_open,
        Resize_vertical,
        Resize_horizontal,
        Hdd,
        Bullhorn,
        Bell,
        Certificate,
        Thumbs_up,
        Thumbs_down,
        Hand_right,
        Hand_left,
        Hand_up,
        Hand_down,
        Circle_arrow_right,
        Circle_arrow_left,
        Circle_arrow_up,
        Circle_arrow_down,
        Globe,
        Wrench,
        Tasks,
        Filter,
        Briefcase,
        Fullscreen,
        Dashboard,
        Paperclip,
        Heart_empty,
        Link,
        Phone,
        Pushpin,
        Usd,
        Gbp,
        Sort,
        Sort_by_alphabet,
        Sort_by_alphabet_alt,
        Sort_by_order,
        Sort_by_order_alt,
        Sort_by_attributes,
        Sort_by_attributes_alt,
        Unchecked,
        Expand,
        Collapse_down,
        Collapse_up,
        Log_in,
        Flash,
        Log_out,
        New_window,
        Record,
        Save,
        Open,
        Saved,
        Import,
        Export,
        Send,
        Floppy_disk,
        Floppy_saved,
        Floppy_remove,
        Floppy_save,
        Floppy_open,
        Credit_card,
        Transfer,
        Cutlery,
        Header,
        Compressed,
        Earphone,
        Phone_alt,
        Tower,
        Stats,
        Sd_video,
        Hd_video,
        Subtitles,
        Sound_stereo,
        Sound_dolby,
        Sound_5_1,
        Sound_6_1,
        Sound_7_1,
        Copyright_mark,
        Registration_mark,
        Cloud_download,
        Cloud_upload,
        Tree_conifer,
        Tree_deciduous
    }
}
