/*!
 * Knockout JavaScript library v3.5.0-pre
 * (c) The Knockout.js team - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {(function(n){var y=this||(0,eval)("this"),t=y.document,N=y.navigator,w=y.jQuery,I=y.JSON;(function(n){"function"===typeof define&&define.amd?define(["exports","require"],n):"object"===typeof exports&&"object"===typeof module?n(module.exports||exports):n(y.ko={})})(function(O,P){function K(a,c){return null===a||typeof a in T?a===c:!1}function U(b,c){var d;return function(){d||(d=a.a.setTimeout(function(){d=n;b()},c))}}function V(b,c){var d;return function(){clearTimeout(d);d=a.a.setTimeout(b,c)}}function W(a,
c){c&&"change"!==c?"beforeChange"===c?this.Vb(a):this.Ua(a,c):this.Wb(a)}function X(a,c){null!==c&&c.o&&c.o()}function Y(a,c){var d=this.Wc,e=d[u];e.da||(this.Ab&&this.$a[c]?(d.Zb(c,a,this.$a[c]),this.$a[c]=null,--this.Ab):e.F[c]||d.Zb(c,a,e.G?{ta:a}:d.Ic(a)),a.tb&&a.Rc())}function L(b,c,d,e){a.f[b]={init:function(b,h,g,l,k){var m,q;a.u(function(){var l=h(),g=a.a.c(l),g=!d!==!g,z=!q;if(z||c||g!==m)z&&a.Ja.Na()&&(q=a.a.Ia(a.g.childNodes(b),!0)),g?(z||a.g.oa(b,a.a.Ia(q)),a.Fa(e?e(k,l):k,b)):a.g.Ka(b),
m=g},null,{l:b});return{controlsDescendantBindings:!0}}};a.j.Ha[b]=!1;a.g.$[b]=!0}var a="undefined"!==typeof O?O:{};a.b=function(b,c){for(var d=b.split("."),e=a,f=0;f<d.length-1;f++)e=e[d[f]];e[d[d.length-1]]=c};a.P=function(a,c,d){a[c]=d};a.version="3.5.0-pre";a.b("version",a.version);a.options={deferUpdates:!1,useOnlyNativeEvents:!1};a.ja=function(){var a=!1,c=[],d={pause:function(){a=!0},yd:function(){a=!1;for(var d=0;d<c.length;d++)c[d]();c=[]},Kb:function(d){a?c.push(d):d()}};Object.defineProperty(d,
"isPaused",{get:function(){return a},enumerable:!0,configurable:!0});return d}();a.b("delaySync",a.ja);a.b("delaySync.pause",a.ja.pause);a.b("delaySync.isPaused",a.ja.isPaused);a.b("delaySync.resume",a.ja.yd);a.b("delaySync.run",a.ja.Kb);a.a=function(){function b(a,b){for(var c in a)f.call(a,c)&&b(c,a[c])}function c(a,b){if(b)for(var c in b)f.call(b,c)&&(a[c]=b[c]);return a}function d(a,b){a.__proto__=b;return a}function e(b,c,d,e){var k=b[c].match(r)||[];a.a.D(d.match(r),function(b){a.a.Ea(k,b,e)});
b[c]=k.join(" ")}var f=Object.prototype.hasOwnProperty,h={__proto__:[]}instanceof Array,g="function"===typeof Symbol,l={},k={};l[N&&/Firefox\/2/i.test(N.userAgent)?"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];l.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(l,function(a,b){if(b.length)for(var c=0,d=b.length;c<d;c++)k[b[c]]=a});var m={propertychange:!0},q=t&&function(){for(var a=3,b=t.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML=
"\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:n}(),r=/\S+/g,p;return{nc:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],D:function(a,b){for(var c=0,d=a.length;c<d;c++)b(a[c],c)},A:function(b,c,d){if(d){c=a.a.za(c);d=0;for(var e=b.length;d<e;d++)if(a.a.za(b[d])===c)return d}else{if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(b,c);d=0;for(e=b.length;d<e;d++)if(b[d]===c)return d}return-1},bc:function(a,b,c){for(var d=0,e=a.length;d<
e;d++)if(b.call(c,a[d],d))return a[d];return null},Za:function(b,c){var d=a.a.A(b,c);0<d?b.splice(d,1):0===d&&b.shift()},cc:function(b){b=b||[];for(var c=[],d=0,e=b.length;d<e;d++)0>a.a.A(c,b[d])&&c.push(b[d]);return c},ub:function(a,b){a=a||[];for(var c=[],d=0,e=a.length;d<e;d++)c.push(b(a[d],d));return c},Xa:function(a,b){a=a||[];for(var c=[],d=0,e=a.length;d<e;d++)b(a[d],d)&&c.push(a[d]);return c},Ya:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var c=0,d=b.length;c<d;c++)a.push(b[c]);
return a},Ea:function(b,c,d,e){var k=a.a.A(a.a.za(b),c,e);e&&!a.J(c)&&(c=a.T(c));0>k?d&&b.push(c):d||b.splice(k,1)},va:h,extend:c,setPrototypeOf:d,nb:h?d:c,L:b,Qa:function(a,b){if(!a)return a;var c={},d;for(d in a)f.call(a,d)&&(c[d]=b(a[d],d,a));return c},Db:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},wc:function(b){b=a.a.fa(b);for(var c=(b[0]&&b[0].ownerDocument||t).createElement("div"),d=0,e=b.length;d<e;d++)c.appendChild(a.ia(b[d]));return c},Ia:function(b,c){for(var d=0,e=b.length,
k=[];d<e;d++){var f=b[d].cloneNode(!0);k.push(c?a.ia(f):f)}return k},oa:function(b,c){a.a.Db(b);if(c)for(var d=0,e=c.length;d<e;d++)b.appendChild(c[d])},Ec:function(b,c){var d=b.nodeType?[b]:b;if(0<d.length){for(var e=d[0],k=e.parentNode,f=0,m=c.length;f<m;f++)k.insertBefore(c[f],e);f=0;for(m=d.length;f<m;f++)a.removeNode(d[f])}},Ma:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.splice(0,1);for(;1<a.length&&a[a.length-1].parentNode!==b;)a.length--;
if(1<a.length){var c=a[0],d=a[a.length-1];for(a.length=0;c!==d;)a.push(c),c=c.nextSibling;a.push(d)}}return a},Gc:function(a,b){7>q?a.setAttribute("selected",b):a.selected=b},pb:function(a){return null===a||a===n?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ad:function(a,b){a=a||"";return b.length>a.length?!1:a.substring(0,b.length)===b},ad:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;if(b.contains)return b.contains(1!==a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==
(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},Cb:function(b){return a.a.ad(b,b.ownerDocument.documentElement)},$b:function(b){return!!a.a.bc(b,a.a.Cb)},K:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},fc:function(b){return a.onError?function(){try{return b.apply(this,arguments)}catch(c){throw a.onError&&a.onError(c),c;}}:b},setTimeout:function(b,c){return setTimeout(a.a.fc(b),c)},kc:function(b){setTimeout(function(){a.onError&&a.onError(b);throw b;},0)},C:function(b,
c,d){var e=a.a.fc(d);d=m[c];if(a.options.useOnlyNativeEvents||d||!w)if(d||"function"!=typeof b.addEventListener)if("undefined"!=typeof b.attachEvent){var k=function(a){e.call(b,a)},f="on"+c;b.attachEvent(f,k);a.a.O.Da(b,function(){b.detachEvent(f,k)})}else throw Error("Browser doesn't support addEventListener or attachEvent");else b.addEventListener(c,e,!1);else p||(p="function"==typeof w(b).on?"on":"bind"),w(b)[p](c,e)},Ra:function(b,c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");
var d;"input"===a.a.K(b)&&b.type&&"click"==c.toLowerCase()?(d=b.type,d="checkbox"==d||"radio"==d):d=!1;if(a.options.useOnlyNativeEvents||!w||d)if("function"==typeof t.createEvent)if("function"==typeof b.dispatchEvent)d=t.createEvent(k[c]||"HTMLEvents"),d.initEvent(c,!0,!0,y,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(d);else throw Error("The supplied element doesn't support dispatchEvent");else if(d&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");
else w(b).trigger(c)},c:function(b){return a.J(b)?b():b},Cd:function(b){return a.J(b)?b:a.T(b)},za:function(b){return a.J(b)?b.B():b},rb:function(b,c,d){var k;c&&("object"===typeof b.classList?(k=b.classList[d?"add":"remove"],a.a.D(c.match(r),function(a){k.call(b.classList,a)})):"string"===typeof b.className.baseVal?e(b.className,"baseVal",c,d):e(b,"className",c,d))},ob:function(b,c){var d=a.a.c(c);if(null===d||d===n)d="";var e=a.g.firstChild(b);!e||3!=e.nodeType||a.g.nextSibling(e)?a.g.oa(b,[b.ownerDocument.createTextNode(d)]):
e.data=d;a.a.fd(b)},Fc:function(a,b){a.name=b;if(7>=q)try{a.mergeAttributes(t.createElement("<input name='"+a.name+"'/>"),!1)}catch(c){}},fd:function(a){9<=q&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},bd:function(a){if(q){var b=a.style.width;a.style.width=0;a.style.width=b}},vd:function(b,c){b=a.a.c(b);c=a.a.c(c);for(var d=[],e=b;e<=c;e++)d.push(e);return d},fa:function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c]);return b},ic:function(a){return g?Symbol(a):a},
Ed:6===q,Fd:7===q,ca:q,pc:function(b,c){for(var d=a.a.fa(b.getElementsByTagName("input")).concat(a.a.fa(b.getElementsByTagName("textarea"))),e="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},k=[],f=d.length-1;0<=f;f--)e(d[f])&&k.push(d[f]);return k},sd:function(b){return"string"==typeof b&&(b=a.a.pb(b))?I&&I.parse?I.parse(b):(new Function("return "+b))():null},Ob:function(b,c,d){if(!I||!I.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");
return I.stringify(a.a.c(b),c,d)},ud:function(c,d,e){e=e||{};var k=e.params||{},f=e.includeFields||this.nc,m=c;if("object"==typeof c&&"form"===a.a.K(c))for(var m=c.action,l=f.length-1;0<=l;l--)for(var h=a.a.pc(c,f[l]),g=h.length-1;0<=g;g--)k[h[g].name]=h[g].value;d=a.a.c(d);var q=t.createElement("form");q.style.display="none";q.action=m;q.method="post";for(var r in d)c=t.createElement("input"),c.type="hidden",c.name=r,c.value=a.a.Ob(a.a.c(d[r])),q.appendChild(c);b(k,function(a,b){var c=t.createElement("input");
c.type="hidden";c.name=a;c.value=b;q.appendChild(c)});t.body.appendChild(q);e.submitter?e.submitter(q):q.submit();setTimeout(function(){q.parentNode.removeChild(q)},0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",a.a.D);a.b("utils.arrayFirst",a.a.bc);a.b("utils.arrayFilter",a.a.Xa);a.b("utils.arrayGetDistinctValues",a.a.cc);a.b("utils.arrayIndexOf",a.a.A);a.b("utils.arrayMap",a.a.ub);a.b("utils.arrayPushAll",a.a.Ya);a.b("utils.arrayRemoveItem",a.a.Za);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",
a.a.nc);a.b("utils.getFormFields",a.a.pc);a.b("utils.peekObservable",a.a.za);a.b("utils.postJson",a.a.ud);a.b("utils.parseJson",a.a.sd);a.b("utils.registerEventHandler",a.a.C);a.b("utils.stringifyJson",a.a.Ob);a.b("utils.range",a.a.vd);a.b("utils.toggleDomNodeCssClass",a.a.rb);a.b("utils.triggerEvent",a.a.Ra);a.b("utils.unwrapObservable",a.a.c);a.b("utils.objectForEach",a.a.L);a.b("utils.addOrRemoveItem",a.a.Ea);a.b("utils.setTextContent",a.a.ob);a.b("unwrap",a.a.c);Function.prototype.bind||(Function.prototype.bind=
function(a){var c=this;if(1===arguments.length)return function(){return c.apply(a,arguments)};var d=Array.prototype.slice.call(arguments,1);return function(){var e=d.slice(0);e.push.apply(e,arguments);return c.apply(a,e)}});a.a.h=new function(){function a(b,h){var g=b[d];if(!g||"null"===g||!e[g]){if(!h)return n;g=b[d]="ko"+c++;e[g]={}}return e[g]}var c=0,d="__ko__"+(new Date).getTime(),e={};return{get:function(c,d){var e=a(c,!1);return e===n?n:e[d]},set:function(c,d,e){if(e!==n||a(c,!1)!==n)a(c,!0)[d]=
e},clear:function(a){var b=a[d];return b?(delete e[b],a[d]=null,!0):!1},S:function(){return c++ +d}}};a.b("utils.domData",a.a.h);a.b("utils.domData.clear",a.a.h.clear);a.a.O=new function(){function b(b,c){var e=a.a.h.get(b,d);e===n&&c&&(e=[],a.a.h.set(b,d,e));return e}function c(d){var e=b(d,!1);if(e)for(var e=e.slice(0),l=0;l<e.length;l++)e[l](d);a.a.h.clear(d);a.a.O.cleanExternalData(d);if(f[d.nodeType])for(e=d.firstChild;d=e;)e=d.nextSibling,8===d.nodeType&&c(d)}var d=a.a.h.S(),e={1:!0,8:!0,9:!0},
f={1:!0,9:!0};return{Da:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},Dc:function(c,e){var f=b(c,!1);f&&(a.a.Za(f,e),0==f.length&&a.a.h.set(c,d,n))},ia:function(a){if(e[a.nodeType]&&(c(a),f[a.nodeType]))for(var b=a.getElementsByTagName("*"),d,k=0;k<b.length;k++)if(c(d=b[k]),b[k]!==d)throw Error("ko.cleanNode: An already cleaned node was removed from the document");return a},removeNode:function(b){a.ia(b);b.parentNode&&b.parentNode.removeChild(b)},
cleanExternalData:function(a){w&&"function"==typeof w.cleanData&&w.cleanData([a])}}};a.ia=a.a.O.ia;a.removeNode=a.a.O.removeNode;a.b("cleanNode",a.ia);a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.O);a.b("utils.domNodeDisposal.addDisposeCallback",a.a.O.Da);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.O.Dc);(function(){var b=[0,"",""],c=[1,"<table>","</table>"],d=[3,"<table><tbody><tr>","</tr></tbody></table>"],e=[1,"<select multiple='multiple'>","</select>"],f={thead:c,tbody:c,
tfoot:c,tr:[2,"<table><tbody>","</tbody></table>"],td:d,th:d,option:e,optgroup:e},h=8>=a.a.ca;a.a.ya=function(c,d){var e;if(w)if(w.parseHTML)e=w.parseHTML(c,d)||[];else{if((e=w.clean([c],d))&&e[0]){for(var m=e[0];m.parentNode&&11!==m.parentNode.nodeType;)m=m.parentNode;m.parentNode&&m.parentNode.removeChild(m)}}else{(e=d)||(e=t);var m=e.parentWindow||e.defaultView||y,q=a.a.pb(c).toLowerCase(),r=e.createElement("div"),p;p=(q=q.match(/^<([a-z]+)[ >]/))&&f[q[1]]||b;q=p[0];p="ignored<div>"+p[1]+c+p[2]+
"</div>";"function"==typeof m.innerShiv?r.appendChild(m.innerShiv(p)):(h&&e.appendChild(r),r.innerHTML=p,h&&r.parentNode.removeChild(r));for(;q--;)r=r.lastChild;e=a.a.fa(r.lastChild.childNodes)}return e};a.a.Mb=function(b,c){a.a.Db(b);c=a.a.c(c);if(null!==c&&c!==n)if("string"!=typeof c&&(c=c.toString()),w)w(b).html(c);else for(var d=a.a.ya(c,b.ownerDocument),e=0;e<d.length;e++)b.appendChild(d[e])}})();a.b("utils.parseHtmlFragment",a.a.ya);a.b("utils.setHtml",a.a.Mb);a.W=function(){function b(c,e){if(c)if(8==
c.nodeType){var f=a.W.yc(c.nodeValue);null!=f&&e.push({$c:c,qd:f})}else if(1==c.nodeType)for(var f=0,h=c.childNodes,g=h.length;f<g;f++)b(h[f],e)}var c={};return{Gb:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);c[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},Lc:function(a,b){var f=c[a];if(f===n)throw Error("Couldn't find any memo with ID "+
a+". Perhaps it's already been unmemoized.");try{return f.apply(null,b||[]),!0}finally{delete c[a]}},Mc:function(c,e){var f=[];b(c,f);for(var h=0,g=f.length;h<g;h++){var l=f[h].$c,k=[l];e&&a.a.Ya(k,e);a.W.Lc(f[h].qd,k);l.nodeValue="";l.parentNode&&l.parentNode.removeChild(l)}},yc:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.W);a.b("memoization.memoize",a.W.Gb);a.b("memoization.unmemoize",a.W.Lc);a.b("memoization.parseMemoText",a.W.yc);a.b("memoization.unmemoizeDomNodeAndDescendants",
a.W.Mc);a.ga=function(){function b(){if(f)for(var b=f,c=0,d;g<f;)if(d=e[g++]){if(g>b){if(5E3<=++c){g=f;a.a.kc(Error("'Too much recursion' after processing "+c+" task groups."));break}b=f}try{d()}catch(q){a.a.kc(q)}}}function c(){b();g=f=e.length=0}var d,e=[],f=0,h=1,g=0;y.MutationObserver?d=function(a){var b=t.createElement("div");(new MutationObserver(a)).observe(b,{attributes:!0});return function(){b.classList.toggle("foo")}}(c):d=t&&"onreadystatechange"in t.createElement("script")?function(a){var b=
t.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;t.documentElement.removeChild(b);b=null;a()};t.documentElement.appendChild(b)}:function(a){setTimeout(a,0)};return{scheduler:d,mb:function(b){f||a.ga.scheduler(c);e[f++]=b;return h++},cancel:function(a){a=a-(h-f);a>=g&&a<f&&(e[a]=null)},resetForTesting:function(){var a=f-g;g=f=e.length=0;return a},zd:b}}();a.b("tasks",a.ga);a.b("tasks.schedule",a.ga.mb);a.b("tasks.runEarly",a.ga.zd);a.La={throttle:function(b,c){b.throttleEvaluation=
c;var d=null;return a.N({read:b,write:function(e){clearTimeout(d);d=a.a.setTimeout(function(){b(e)},c)}})},rateLimit:function(a,c){var d,e,f;"number"==typeof c?d=c:(d=c.timeout,e=c.method);a.sb=!1;f="notifyWhenChangesStop"==e?V:U;a.jb(function(a){return f(a,d)})},deferred:function(b,c){if(!0!==c)throw Error("The 'deferred' extender only accepts the value 'true', because it is not supported to turn deferral off once enabled.");b.sb||(b.sb=!0,b.jb(function(c){var e,f=!1;return function(){if(!f){a.ga.cancel(e);
e=a.ga.mb(c);try{f=!0,b.notifySubscribers(n,"dirty")}finally{f=!1}}}}))},notify:function(a,c){a.equalityComparer="always"==c?null:K}};var T={undefined:1,"boolean":1,number:1,string:1};a.b("extenders",a.La);a.Jc=function(b,c,d){this.ta=b;this.vb=c;this.Zc=d;this.da=!1;a.P(this,"dispose",this.o)};a.Jc.prototype.o=function(){this.da=!0;this.Zc()};a.U=function(){a.a.nb(this,E);E.Fb(this)};var E={Fb:function(a){a.M={change:[]};a.Xb=1},subscribe:function(b,c,d){var e=this;d=d||"change";var f=new a.Jc(e,
c?b.bind(c):b,function(){a.a.Za(e.M[d],f);e.Va&&e.Va(d)});e.Ga&&e.Ga(d);e.M[d]||(e.M[d]=[]);e.M[d].push(f);return f},notifySubscribers:function(b,c){c=c||"change";"change"===c&&this.Sb();if(this.cb(c)){var d="change"===c&&this.Pc||this.M[c].slice(0);try{a.s.dc();for(var e=0,f;f=d[e];++e)f.da||f.vb(b)}finally{a.s.end()}}},bb:function(){return this.Xb},jd:function(a){return this.bb()!==a},Sb:function(){++this.Xb},jb:function(b){var c=this,d=a.J(c),e,f,h,g;c.Ua||(c.Ua=c.notifySubscribers,c.notifySubscribers=
W);var l=b(function(){c.tb=!1;d&&g===c&&(g=c.Tb?c.Tb():c());var a=f||c.gb(h,g);f=e=!1;a&&c.Ua(h=g)});c.Wb=function(a){c.Pc=c.M.change.slice(0);c.tb=e=!0;g=a;l()};c.Vb=function(a){e||(h=a,c.Ua(a,"beforeChange"))};c.Rc=function(){c.gb(h,c.B(!0))&&(f=!0)}},cb:function(a){return this.M[a]&&this.M[a].length},gd:function(b){if(b)return this.M[b]&&this.M[b].length||0;var c=0;a.a.L(this.M,function(a,b){"dirty"!==a&&(c+=b.length)});return c},gb:function(a,c){return!this.equalityComparer||!this.equalityComparer(a,
c)},extend:function(b){var c=this;b&&a.a.L(b,function(b,e){var f=a.La[b];"function"==typeof f&&(c=f(c,e)||c)});return c}};a.P(E,"subscribe",E.subscribe);a.P(E,"extend",E.extend);a.P(E,"getSubscriptionsCount",E.gd);a.a.va&&a.a.setPrototypeOf(E,Function.prototype);a.U.fn=E;a.uc=function(a){return null!=a&&"function"==typeof a.subscribe&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.U);a.b("isSubscribable",a.uc);a.Ja=a.s=function(){function b(a){d.push(e);e=a}function c(){e=d.pop()}var d=
[],e,f=0;return{dc:b,end:c,Cc:function(b){if(e){if(!a.uc(b))throw Error("Only subscribable things can act as dependencies");e.vb.call(e.Vc,b,b.Qc||(b.Qc=++f))}},I:function(a,d,e){try{return b(),a.apply(d,e||[])}finally{c()}},Na:function(){if(e)return e.u.Na()},hb:function(){if(e)return e.hb}}}();a.b("computedContext",a.Ja);a.b("computedContext.getDependenciesCount",a.Ja.Na);a.b("computedContext.isInitial",a.Ja.hb);a.b("ignoreDependencies",a.Dd=a.s.I);var F=a.a.ic("_latestValue");a.T=function(b){function c(){if(0<
arguments.length)return c.gb(c[F],arguments[0])&&(c.ra(),c[F]=arguments[0],c.qa()),this;a.s.Cc(c);return c[F]}c[F]=b;a.a.va||a.a.extend(c,a.U.fn);a.U.fn.Fb(c);a.a.nb(c,C);a.options.deferUpdates&&a.La.deferred(c,!0);return c};var C={equalityComparer:K,B:function(){return this[F]},qa:function(){this.notifySubscribers(this[F],"spectate");this.notifySubscribers(this[F])},ra:function(){this.notifySubscribers(this[F],"beforeChange")}};a.a.va&&a.a.setPrototypeOf(C,a.U.fn);var J=a.T.Ca="__ko_proto__";C[J]=
a.T;a.J=function(b){if((b="function"==typeof b&&b[J])&&b!==a.T&&b!==a.u)throw Error("Invalid object that looks like an observable; possibly from another Knockout instance");return!!b};a.Oa=function(b){return"function"==typeof b&&(b[J]===a.T||b[J]===a.u&&b.rc)};a.b("observable",a.T);a.b("isObservable",a.J);a.b("isWriteableObservable",a.Oa);a.b("isWritableObservable",a.Oa);a.b("observable.fn",C);a.P(C,"peek",C.B);a.P(C,"valueHasMutated",C.qa);a.P(C,"valueWillMutate",C.ra);a.xa=function(b){b=b||[];if("object"!=
typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");b=a.T(b);a.a.nb(b,a.xa.fn);return b.extend({trackArrayChanges:!0})};a.xa.fn={remove:function(b){for(var c=this.B(),d=[],e="function"!=typeof b||a.J(b)?function(a){return a===b}:b,f=0;f<c.length;f++){var h=c[f];e(h)&&(0===d.length&&this.ra(),d.push(h),c.splice(f,1),f--)}d.length&&this.qa();return d},removeAll:function(b){if(b===n){var c=this.B(),d=c.slice(0);this.ra();
c.splice(0,c.length);this.qa();return d}return b?this.remove(function(c){return 0<=a.a.A(b,c)}):[]},destroy:function(b){var c=this.B(),d="function"!=typeof b||a.J(b)?function(a){return a===b}:b;this.ra();for(var e=c.length-1;0<=e;e--)d(c[e])&&(c[e]._destroy=!0);this.qa()},destroyAll:function(b){return b===n?this.destroy(function(){return!0}):b?this.destroy(function(c){return 0<=a.a.A(b,c)}):[]},indexOf:function(b){var c=this();return a.a.A(c,b)},replace:function(a,c){var d=this.indexOf(a);0<=d&&(this.ra(),
this.B()[d]=c,this.qa())}};a.a.va&&a.a.setPrototypeOf(a.xa.fn,a.T.fn);a.a.D("pop push reverse shift sort splice unshift".split(" "),function(b){a.xa.fn[b]=function(){var a=this.B();this.ra();this.ec(a,b,arguments);var d=a[b].apply(a,arguments);this.qa();return d===a?this:d}});a.a.D(["slice"],function(b){a.xa.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.b("observableArray",a.xa);a.La.trackArrayChanges=function(b,c){function d(){if(!e){e=!0;l=b.notifySubscribers;b.notifySubscribers=
function(a,b){b&&"change"!==b||++g;return l.apply(this,arguments)};var c=[].concat(b.B()||[]);f=null;h=b.subscribe(function(d){d=[].concat(d||[]);if(b.cb("arrayChange")){var e;if(!f||1<g)f=a.a.xb(c,d,b.wb);e=f}c=d;f=null;g=0;e&&e.length&&b.notifySubscribers(e,"arrayChange")})}}b.wb={};c&&"object"==typeof c&&a.a.extend(b.wb,c);b.wb.sparse=!0;if(!b.ec){var e=!1,f=null,h,g=0,l,k=b.Ga,m=b.Va;b.Ga=function(a){k&&k.call(b,a);"arrayChange"===a&&d()};b.Va=function(a){m&&m.call(b,a);"arrayChange"!==a||b.cb("arrayChange")||
(l&&(b.notifySubscribers=l,l=n),h.o(),e=!1)};b.ec=function(b,c,d){function k(a,b,c){return m[m.length]={status:a,value:b,index:c}}if(e&&!g){var m=[],l=b.length,h=d.length,H=0;switch(c){case "push":H=l;case "unshift":for(c=0;c<h;c++)k("added",d[c],H+c);break;case "pop":H=l-1;case "shift":l&&k("deleted",b[H],H);break;case "splice":c=Math.min(Math.max(0,0>d[0]?l+d[0]:d[0]),l);for(var l=1===h?l:Math.min(c+(d[1]||0),l),h=c+h-2,H=Math.max(l,h),n=[],Q=[],v=2;c<H;++c,++v)c<l&&Q.push(k("deleted",b[c],c)),
c<h&&n.push(k("added",d[v],c));a.a.oc(Q,n);break;default:return}f=m}}}};var u=a.a.ic("_state");a.u=a.N=function(b,c,d){function e(){if(0<arguments.length){if("function"===typeof f)f.apply(h.ab,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this}a.s.Cc(e);(h.la||h.G&&e.eb())&&e.ea();return h.R}"object"===typeof b?d=b:(d=d||{},b&&(d.read=b));if("function"!=typeof d.read)throw Error("Pass a function that returns the value of the ko.computed");
var f=d.write,h={R:n,ma:!0,la:!0,fb:!1,Pb:!1,da:!1,lb:!1,G:!1,Bc:d.read,ab:c||d.owner,l:d.disposeWhenNodeIsRemoved||d.l||null,wa:d.disposeWhen||d.wa,Bb:null,F:{},V:0,mc:null};e[u]=h;e.rc="function"===typeof f;a.a.va||a.a.extend(e,a.U.fn);a.U.fn.Fb(e);a.a.nb(e,A);d.pure?(h.lb=!0,h.G=!0,a.a.extend(e,aa)):d.deferEvaluation&&a.a.extend(e,ba);a.options.deferUpdates&&a.La.deferred(e,!0);h.l&&(h.Pb=!0,h.l.nodeType||(h.l=null));h.G||d.deferEvaluation||e.ea();h.l&&e.ka()&&a.a.O.Da(h.l,h.Bb=function(){e.o()});
return e};var A={equalityComparer:K,Na:function(){return this[u].V},Zb:function(a,c,d){if(this[u].lb&&c===this)throw Error("A 'pure' computed must not be called recursively");this[u].F[a]=d;d.Ta=this[u].V++;d.Ba=c.bb()},eb:function(){var a,c,d=this[u].F;for(a in d)if(Object.prototype.hasOwnProperty.call(d,a)&&(c=d[a],c.ta.jd(c.Ba)))return!0},pd:function(){this.Sa&&!this[u].fb&&this.Sa(!1)},ka:function(){var a=this[u];return a.la||0<a.V},xd:function(){this.tb?this[u].la&&(this[u].ma=!0):this.lc()},
Ic:function(a){if(a.sb&&!this[u].l){var c=a.subscribe(this.pd,this,"dirty"),d=a.subscribe(this.xd,this);return{ta:a,o:function(){c.o();d.o()}}}return a.subscribe(this.lc,this)},lc:function(){var b=this,c=b.throttleEvaluation;c&&0<=c?(clearTimeout(this[u].mc),this[u].mc=a.a.setTimeout(function(){b.ea(!0)},c)):b.Sa?b.Sa(!0):b.ea(!0)},ea:function(b){var c=this[u],d=c.wa,e=!1;if(!c.fb&&!c.da){if(c.l&&!a.a.Cb(c.l)||d&&d()){if(!c.Pb){this.o();return}}else c.Pb=!1;c.fb=!0;try{e=this.ed(b)}finally{c.fb=!1}c.V||
this.o();return e}},ed:function(b){var c=this[u],d=!1,e=c.lb?n:!c.V,f={Wc:this,$a:c.F,Ab:c.V};a.s.dc({Vc:f,vb:Y,u:this,hb:e});c.F={};c.V=0;f=this.dd(c,f);this.gb(c.R,f)&&(c.G?this.Sb():this.notifySubscribers(c.R,"beforeChange"),c.R=f,this.notifySubscribers(c.R,"spectate"),!c.G&&b&&this.notifySubscribers(c.R),d=!0);e&&this.notifySubscribers(c.R,"awake");return d},dd:function(b,c){try{var d=b.Bc;return b.ab?d.call(b.ab):d()}finally{a.s.end(),c.Ab&&!b.G&&a.a.L(c.$a,X),b.ma=b.la=!1}},B:function(a){var c=
this[u];(c.la&&(a||!c.V)||c.G&&this.eb())&&this.ea();return c.R},jb:function(b){a.U.fn.jb.call(this,b);this.Tb=function(){this[u].ma&&this.ea();return this[u].R};this.Sa=function(a){this.Vb(this[u].R);this[u].la=!0;a&&(this[u].ma=!0);this.Wb(this)}},o:function(){var b=this[u];!b.G&&b.F&&a.a.L(b.F,function(a,b){b.o&&b.o()});b.l&&b.Bb&&a.a.O.Dc(b.l,b.Bb);b.F=n;b.V=0;b.da=!0;b.ma=!1;b.la=!1;b.G=!1;b.l=n;b.wa=n;b.Bc=n;this.rc||(b.ab=n)}},aa={Ga:function(b){var c=this,d=c[u];if(!d.da&&d.G&&"change"==b){d.G=
!1;if(d.ma||c.eb())d.F=null,d.V=0,c.ea()&&c.Sb();else{var e=[];a.a.L(d.F,function(a,b){e[b.Ta]=a});a.a.D(e,function(a,b){var e=d.F[a],l=c.Ic(e.ta);l.Ta=b;l.Ba=e.Ba;d.F[a]=l})}d.da||c.notifySubscribers(d.R,"awake")}},Va:function(b){var c=this[u];c.da||"change"!=b||this.cb("change")||(a.a.L(c.F,function(a,b){b.o&&(c.F[a]={ta:b.ta,Ta:b.Ta,Ba:b.Ba},b.o())}),c.G=!0,this.notifySubscribers(n,"asleep"))},bb:function(){var b=this[u];b.G&&(b.ma||this.eb())&&this.ea();return a.U.fn.bb.call(this)}},ba={Ga:function(a){"change"!=
a&&"beforeChange"!=a||this.B()}};a.a.va&&a.a.setPrototypeOf(A,a.U.fn);var R=a.T.Ca;A[R]=a.u;a.tc=function(b){return"function"==typeof b&&b[R]===a.u};a.ld=function(b){return a.tc(b)&&b[u]&&b[u].lb};a.b("computed",a.u);a.b("dependentObservable",a.u);a.b("isComputed",a.tc);a.b("isPureComputed",a.ld);a.b("computed.fn",A);a.P(A,"peek",A.B);a.P(A,"dispose",A.o);a.P(A,"isActive",A.ka);a.P(A,"getDependenciesCount",A.Na);a.Ac=function(b,c){if("function"===typeof b)return a.u(b,c,{pure:!0});b=a.a.extend({},
b);b.pure=!0;return a.u(b,c)};a.b("pureComputed",a.Ac);(function(){function b(a,f,h){h=h||new d;a=f(a);if("object"!=typeof a||null===a||a===n||a instanceof RegExp||a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var g=a instanceof Array?[]:{};h.save(a,g);c(a,function(c){var d=f(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "function":g[c]=d;break;case "object":case "undefined":var m=h.get(d);g[c]=m!==n?m:b(d,f,h)}});return g}function c(a,
b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function d(){this.keys=[];this.values=[]}a.Kc=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");return b(c,function(b){for(var c=0;a.J(b)&&10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.Kc(b);return a.a.Ob(b,c,d)};d.prototype={constructor:d,save:function(b,c){var d=a.a.A(this.keys,b);0<=d?this.values[d]=c:(this.keys.push(b),
this.values.push(c))},get:function(b){b=a.a.A(this.keys,b);return 0<=b?this.values[b]:n}}})();a.b("toJS",a.Kc);a.b("toJSON",a.toJSON);(function(){a.m={H:function(b){switch(a.a.K(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.a.h.get(b,a.f.options.Hb):7>=a.a.ca?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.m.H(b.options[b.selectedIndex]):n;default:return b.value}},sa:function(b,c,d){switch(a.a.K(b)){case "option":switch(typeof c){case "string":a.a.h.set(b,
a.f.options.Hb,n);"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__;b.value=c;break;default:a.a.h.set(b,a.f.options.Hb,c),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof c?c:""}break;case "select":if(""===c||null===c)c=n;for(var e=-1,f=0,h=b.options.length,g;f<h;++f)if(g=a.m.H(b.options[f]),g==c||""===g&&c===n){e=f;break}if(d||0<=e||c===n&&1<b.size)b.selectedIndex=e;break;default:if(null===c||c===n)c="";b.value=c}}}})();a.b("selectExtensions",a.m);a.b("selectExtensions.readValue",
a.m.H);a.b("selectExtensions.writeValue",a.m.sa);a.j=function(){function b(b){b=a.a.pb(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));b+="\n,";var c=[],d=b.match(e),q,g=[],p=0;if(1<d.length)for(var z=0,B;B=d[z];++z){var x=B.charCodeAt(0);if(44===x){if(0>=p){c.push(q&&g.length?{key:q,value:g.join("")}:{unknown:q||g.join("")});q=p=0;g=[];continue}}else if(58===x){if(!p&&!q&&1===g.length){q=g.pop();continue}}else if(47===x&&1<B.length&&(47===B.charCodeAt(1)||42===B.charCodeAt(1)))continue;else 47===x&&
z&&1<B.length?(x=d[z-1].match(f))&&!h[x[0]]&&(b=b.substr(b.indexOf(B)+1),d=b.match(e),z=-1,B="/"):40===x||123===x||91===x?++p:41===x||125===x||93===x?--p:q||g.length||34!==x&&39!==x||(B=B.slice(1,-1));g.push(B)}return c}var c=["true","false","null","undefined"],d=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,e=RegExp("\"(?:\\\\.|[^\"])*\"|'(?:\\\\.|[^'])*'|`(?:\\\\.|[^`])*`|/\\*(?:[^*]|\\*+[^*/])*\\*+/|//.*\n|/(?:\\\\.|[^/])+/w*|[^\\s:,/][^,\"'`{}()/:[\\]]*[^\\s,\"'`{}()/:[\\]]|[^\\s]","g"),
f=/[\])"'A-Za-z0-9_$]+$/,h={"in":1,"return":1,"typeof":1},g={};return{Ha:[],pa:g,Ib:b,kb:function(e,k){function m(b,e){var k;if(!z){var l=a.getBindingHandler(b);if(l&&l.preprocess&&!(e=l.preprocess(e,b,m)))return;if(l=g[b])k=e,0<=a.a.A(c,k)?k=!1:(l=k.match(d),k=null===l?!1:l[1]?"Object("+l[1]+")"+l[2]:k),l=k;l&&h.push("'"+b+"':function(_z){"+k+"=_z}")}p&&(e="function(){return "+e+" }");f.push("'"+b+"':"+e)}k=k||{};var f=[],h=[],p=k.valueAccessors,z=k.bindingParams,B="string"===typeof e?b(e):e;a.a.D(B,
function(a){m(a.key||a.unknown,a.value)});h.length&&m("_ko_property_writers","{"+h.join(",")+" }");return f.join(",")},od:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},Aa:function(b,c,d,e,f){if(b&&a.J(b))!a.Oa(b)||f&&b.B()===e||b(e);else if((b=c.get("_ko_property_writers"))&&b[d])b[d](e)}}}();a.b("expressionRewriting",a.j);a.b("expressionRewriting.bindingRewriteValidators",a.j.Ha);a.b("expressionRewriting.parseObjectLiteral",a.j.Ib);a.b("expressionRewriting.preProcessBindings",
a.j.kb);a.b("expressionRewriting._twoWayBindings",a.j.pa);a.b("jsonExpressionRewriting",a.j);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.j.kb);(function(){function b(a){return 8==a.nodeType&&h.test(f?a.text:a.nodeValue)}function c(a){return 8==a.nodeType&&g.test(f?a.text:a.nodeValue)}function d(a,d){for(var e=a,f=1,l=[];e=e.nextSibling;){if(c(e)&&(f--,0===f))return l;l.push(e);b(e)&&f++}if(!d)throw Error("Cannot find closing comment tag to match: "+a.nodeValue);return null}function e(a,
b){var c=d(a,b);return c?0<c.length?c[c.length-1].nextSibling:a.nextSibling:null}var f=t&&"\x3c!--test--\x3e"===t.createComment("test").text,h=f?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,g=f?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,l={ul:!0,ol:!0};a.g={$:{},childNodes:function(a){return b(a)?d(a):a.childNodes},Ka:function(c){if(b(c)){c=a.g.childNodes(c);for(var d=0,e=c.length;d<e;d++)a.removeNode(c[d])}else a.a.Db(c)},oa:function(c,d){if(b(c)){a.g.Ka(c);for(var e=
c.nextSibling,f=0,l=d.length;f<l;f++)e.parentNode.insertBefore(d[f],e)}else a.a.oa(c,d)},zc:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},sc:function(c,d,e){e?b(c)?c.parentNode.insertBefore(d,e.nextSibling):e.nextSibling?c.insertBefore(d,e.nextSibling):c.appendChild(d):a.g.zc(c,d)},firstChild:function(a){return b(a)?!a.nextSibling||c(a.nextSibling)?null:a.nextSibling:a.firstChild},nextSibling:function(a){b(a)&&(a=e(a));
return a.nextSibling&&c(a.nextSibling)?null:a.nextSibling},hd:b,Bd:function(a){return(a=(f?a.text:a.nodeValue).match(h))?a[1]:null},xc:function(d){if(l[a.a.K(d)]){var f=d.firstChild;if(f){do if(1===f.nodeType){var g;g=f.firstChild;var h=null;if(g){do if(h)h.push(g);else if(b(g)){var p=e(g,!0);p?g=p:h=[g]}else c(g)&&(h=[g]);while(g=g.nextSibling)}if(g=h)for(h=f.nextSibling,p=0;p<g.length;p++)h?d.insertBefore(g[p],h):d.appendChild(g[p])}while(f=f.nextSibling)}}}}})();a.b("virtualElements",a.g);a.b("virtualElements.allowedBindings",
a.g.$);a.b("virtualElements.emptyNode",a.g.Ka);a.b("virtualElements.insertAfter",a.g.sc);a.b("virtualElements.prepend",a.g.zc);a.b("virtualElements.setDomNodeChildren",a.g.oa);(function(){a.ba=function(){this.Uc={}};a.a.extend(a.ba.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=b.getAttribute("data-bind")||a.i.getComponentNameForNode(b);case 8:return a.g.hd(b);default:return!1}},getBindings:function(b,c){var d=this.getBindingsString(b,c),d=d?this.parseBindingsString(d,
c,b):null;return a.i.Yb(d,b,c,!1)},getBindingAccessors:function(b,c){var d=this.getBindingsString(b,c),d=d?this.parseBindingsString(d,c,b,{valueAccessors:!0}):null;return a.i.Yb(d,b,c,!0)},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.g.Bd(b);default:return null}},parseBindingsString:function(b,c,d,e){try{var f=this.Uc,h=b+(e&&e.valueAccessors||""),g;if(!(g=f[h])){var l,k="with($context){with($data||{}){return{"+a.j.kb(b,e)+"}}}";l=new Function("$context",
"$element",k);g=f[h]=l}return g(c,d)}catch(m){throw m.message="Unable to parse bindings.\nBindings value: "+b+"\nMessage: "+m.message,m;}}});a.ba.instance=new a.ba})();a.b("bindingProvider",a.ba);(function(){function b(a){return function(){return a}}function c(a){return a()}function d(b){return a.a.Qa(a.s.I(b),function(a,c){return function(){return b()[c]}})}function e(c,e,f){return"function"===typeof c?d(c.bind(null,e,f)):a.a.Qa(c,b)}function f(a,b){return d(this.getBindings.bind(this,a,b))}function h(b,
c,d){var e,f=a.g.firstChild(c),k=a.ba.instance,m=k.preprocessNode;if(m){for(;e=f;)f=a.g.nextSibling(e),m.call(k,e);f=a.g.firstChild(c)}for(;e=f;)f=a.g.nextSibling(e),g(b,e,d)}function g(b,c,d){var e=!0,f=1===c.nodeType;f&&a.g.xc(c);if(f&&d||a.ba.instance.nodeHasBindings(c))e=k(c,null,b,d).shouldBindDescendants;e&&!q[a.a.K(c)]&&h(b,c,!f)}function l(b){var c=[],d={},e=[];a.a.L(b,function Z(f){if(!d[f]){var k=a.getBindingHandler(f);k&&(k.after&&(e.push(f),a.a.D(k.after,function(c){if(b[c]){if(-1!==a.a.A(e,
c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+e.join(", "));Z(c)}}),e.length--),c.push({key:f,qc:k}));d[f]=!0}});return c}function k(b,d,e,k){var m=a.a.h.get(b,r);if(!d){if(m)throw Error("You cannot apply bindings multiple times to the same element.");a.a.h.set(b,r,!0)}!m&&k&&a.Hc(b,e);var g;if(d&&"function"!==typeof d)g=d;else{var h=a.ba.instance,q=h.getBindingAccessors||f,p=a.N(function(){(g=d?d(e,b):q.call(h,b,e))&&e.Z&&e.Z();return g},null,{l:b});
g&&p.ka()||(p=null)}var u;if(g){var t=function(){return a.a.Qa(p?p():g,c)},w=p?function(a){return function(){return c(p()[a])}}:function(a){return g[a]};t.get=function(a){return g[a]&&c(w(a))};t.has=function(a){return a in g};k=l(g);a.a.D(k,function(c){var d=c.qc.init,f=c.qc.update,k=c.key;if(8===b.nodeType&&!a.g.$[k])throw Error("The binding '"+k+"' cannot be used with virtual elements");try{"function"==typeof d&&a.s.I(function(){var a=d(b,w(k),t,e.$data,e);if(a&&a.controlsDescendantBindings){if(u!==
n)throw Error("Multiple bindings ("+u+" and "+k+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");u=k}}),"function"==typeof f&&a.N(function(){f(b,w(k),t,e.$data,e)},null,{l:b})}catch(m){throw m.message='Unable to process binding "'+k+": "+g[k]+'"\nMessage: '+m.message,m;}})}return{shouldBindDescendants:u===n}}function m(b){return b&&b instanceof a.aa?b:new a.aa(b)}a.f={};var q={script:!0,textarea:!0,template:!0};a.getBindingHandler=
function(b){return a.f[b]};a.aa=function(b,c,d,e,f){function k(){var f=l?b():b,m=a.a.c(f);c?(c.Z&&c.Z(),a.a.extend(g,c),g.Z=q):(g.$parents=[],g.$root=m,g.ko=a);g.$rawData=f;g.$data=m;d&&(g[d]=m);e&&e(g,c,m);return g.$data}function m(){return h&&!a.a.$b(h)}var g=this,l="function"==typeof b&&!a.J(b),h,q;f&&f.exportDependencies?k():(q=a.N(k,null,{wa:m,l:!0}),q.ka()&&(g.Z=q,q.equalityComparer=null,h=[],q.Nc=function(b){h.push(b);a.a.O.Da(b,function(b){a.a.Za(h,b);h.length||(q.o(),g.Z=q=n)})}))};a.aa.prototype.createChildContext=
function(b,c,d,e){return new a.aa(b,this,c,function(a,b){a.$parentContext=b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)},e)};a.aa.prototype.extend=function(b){return new a.aa(this.Z||this.$data,this,null,function(c,d){c.$rawData=d.$rawData;a.a.extend(c,"function"==typeof b?b():b)})};a.aa.prototype.hc=function(a,b){return this.createChildContext(a,b,null,{exportDependencies:!0})};var r=a.a.h.S(),p=a.a.h.S();a.Hc=function(b,c){if(2==arguments.length)a.a.h.set(b,
p,c),c.Z&&c.Z.Nc(b);else return a.a.h.get(b,p)};a.Wa=function(b,c,d){1===b.nodeType&&a.g.xc(b);return k(b,c,m(d),!0)};a.Sc=function(b,c,d){d=m(d);return a.Wa(b,e(c,d,b),d)};a.Fa=function(a,b){1!==b.nodeType&&8!==b.nodeType||h(m(a),b,!0)};a.ac=function(a,b){!w&&y.jQuery&&(w=y.jQuery);if(!b){if(b=y.document.body,!b)throw Error("ko.applyBindings: could not find window.document.body; has the document been loaded?");}else if(1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");
g(m(a),b,!0)};a.zb=function(b){switch(b.nodeType){case 1:case 8:var c=a.Hc(b);if(c)return c;if(b.parentNode)return a.zb(b.parentNode)}return n};a.Yc=function(b){return(b=a.zb(b))?b.$data:n};a.b("bindingHandlers",a.f);a.b("applyBindings",a.ac);a.b("applyBindingsToDescendants",a.Fa);a.b("applyBindingAccessorsToNode",a.Wa);a.b("applyBindingsToNode",a.Sc);a.b("contextFor",a.zb);a.b("dataFor",a.Yc)})();(function(b){function c(c,e){var k=Object.prototype.hasOwnProperty.call(f,c)?f[c]:b,m;k?k.subscribe(e):
(k=f[c]=new a.U,k.subscribe(e),d(c,function(b,d){var e=!(!d||!d.synchronous);h[c]={definition:b,md:e};delete f[c];m||e?k.notifySubscribers(b):a.ga.mb(function(){k.notifySubscribers(b)})}),m=!0)}function d(a,b){e("getConfig",[a],function(c){c?e("loadComponent",[a,c],function(a){b(a,c)}):b(null,null)})}function e(c,d,f,m){m||(m=a.i.loaders.slice(0));var h=m.shift();if(h){var r=h[c];if(r){var p=!1;if(r.apply(h,d.concat(function(a){p?f(null):null!==a?f(a):e(c,d,f,m)}))!==b&&(p=!0,!h.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");
}else e(c,d,f,m)}else f(null)}var f={},h={};a.i={get:function(d,e){var f=Object.prototype.hasOwnProperty.call(h,d)?h[d]:b;f?f.md?a.s.I(function(){e(f.definition)}):a.ga.mb(function(){e(f.definition)}):c(d,e)},gc:function(a){delete h[a]},Ub:e};a.i.loaders=[];a.b("components",a.i);a.b("components.get",a.i.get);a.b("components.clearCachedDefinition",a.i.gc)})();(function(){function b(b,c,d,e){function g(){0===--B&&e(h)}var h={},B=2,n=d.template;d=d.viewModel;n?f(c,n,function(c){a.i.Ub("loadTemplate",
[b,c],function(a){h.template=a;g()})}):g();d?f(c,d,function(c){a.i.Ub("loadViewModel",[b,c],function(a){h[l]=a;g()})}):g()}function c(a,b,d){if("function"===typeof b)d(function(a){return new b(a)});else if("function"===typeof b[l])d(b[l]);else if("instance"in b){var e=b.instance;d(function(){return e})}else"viewModel"in b?c(a,b.viewModel,d):a("Unknown viewModel value: "+b)}function d(b){switch(a.a.K(b)){case "script":return a.a.ya(b.text);case "textarea":return a.a.ya(b.value);case "template":if(e(b.content))return a.a.Ia(b.content.childNodes)}return a.a.Ia(b.childNodes)}
function e(a){return y.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType}function f(a,b,c){"string"===typeof b.require?P||y.require?(P||y.require)([b.require],c):a("Uses require, but no AMD loader is present"):c(b)}function h(a){return function(b){throw Error("Component '"+a+"': "+b);}}var g={};a.i.register=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.i.ib(b))throw Error("Component "+b+" is already registered");g[b]=c};a.i.ib=function(a){return Object.prototype.hasOwnProperty.call(g,
a)};a.i.unregister=function(b){delete g[b];a.i.gc(b)};a.i.jc={getConfig:function(b,c){c(a.i.ib(b)?g[b]:null)},loadComponent:function(a,c,d){var e=h(a);f(e,c,function(c){b(a,e,c,d)})},loadTemplate:function(b,c,f){b=h(b);if("string"===typeof c)f(a.a.ya(c));else if(c instanceof Array)f(c);else if(e(c))f(a.a.fa(c.childNodes));else if(c.element)if(c=c.element,y.HTMLElement?c instanceof HTMLElement:c&&c.tagName&&1===c.nodeType)f(d(c));else if("string"===typeof c){var g=t.getElementById(c);g?f(d(g)):b("Cannot find element with ID "+
c)}else b("Unknown element type: "+c);else b("Unknown template value: "+c)},loadViewModel:function(a,b,d){c(h(a),b,d)}};var l="createViewModel";a.b("components.register",a.i.register);a.b("components.isRegistered",a.i.ib);a.b("components.unregister",a.i.unregister);a.b("components.defaultLoader",a.i.jc);a.i.loaders.push(a.i.jc);a.i.Oc=g})();(function(){function b(b,e){var f=b.getAttribute("params");if(f){var f=c.parseBindingsString(f,e,b,{valueAccessors:!0,bindingParams:!0}),f=a.a.Qa(f,function(c){return a.u(c,
null,{l:b})}),h=a.a.Qa(f,function(c){var e=c.B();return c.ka()?a.u({read:function(){return a.a.c(c())},write:a.Oa(e)&&function(a){c()(a)},l:b}):e});Object.prototype.hasOwnProperty.call(h,"$raw")||(h.$raw=f);return h}return{$raw:{}}}a.i.getComponentNameForNode=function(b){var c=a.a.K(b);if(a.i.ib(c)&&(-1!=c.indexOf("-")||"[object HTMLUnknownElement]"==""+b||8>=a.a.ca&&b.tagName===c))return c};a.i.Yb=function(c,e,f,h){if(1===e.nodeType){var g=a.i.getComponentNameForNode(e);if(g){c=c||{};if(c.component)throw Error('Cannot use the "component" binding on a custom element matching a component');
var l={name:g,params:b(e,f)};c.component=h?function(){return l}:l}}return c};var c=new a.ba;9>a.a.ca&&(a.i.register=function(a){return function(b){return a.apply(this,arguments)}}(a.i.register),t.createDocumentFragment=function(b){return function(){var c=b(),f=a.i.Oc,h;for(h in f);return c}}(t.createDocumentFragment))})();(function(b){function c(b,c,d){c=c.template;if(!c)throw Error("Component '"+b+"' has no template");b=a.a.Ia(c);a.g.oa(d,b)}function d(a,b,c,d){var e=a.createViewModel;return e?e.call(a,
d,{element:b,templateNodes:c}):d}var e=0;a.f.component={init:function(f,h,g,l,k){function m(){var a=q&&q.dispose;"function"===typeof a&&a.call(q);r=q=null}var q,r,p=a.a.fa(a.g.childNodes(f));a.a.O.Da(f,m);a.u(function(){var g=a.a.c(h()),l,n;"string"===typeof g?l=g:(l=a.a.c(g.name),n=a.a.c(g.params));if(!l)throw Error("No component name specified");var G=r=++e;a.i.get(l,function(e){if(r===G){m();if(!e)throw Error("Unknown component '"+l+"'");c(l,e,f);var g=d(e,f,p,n);e=k.createChildContext(g,b,function(a){a.$component=
g;a.$componentTemplateNodes=p});q=g;a.Fa(e,f)}})},null,{l:f});return{controlsDescendantBindings:!0}}};a.g.$.component=!0})();var S={"class":"className","for":"htmlFor"};a.f.attr={update:function(b,c){var d=a.a.c(c())||{};a.a.L(d,function(c,d){d=a.a.c(d);var h=!1===d||null===d||d===n;h&&b.removeAttribute(c);8>=a.a.ca&&c in S?(c=S[c],h?b.removeAttribute(c):b[c]=d):h||b.setAttribute(c,d.toString());"name"===c&&a.a.Fc(b,h?"":d.toString())})}};(function(){a.f.checked={after:["value","attr"],init:function(b,
c,d){function e(){var e=b.checked,f=z?h():e;if(!a.Ja.hb()&&(!k||e)){var l=a.s.I(c);if(q){var m=r?l.B():l;p!==f?(e&&(a.a.Ea(m,f,!0,g),a.a.Ea(m,p,!1,g)),p=f):a.a.Ea(m,f,e,g);r&&a.Oa(l)&&l(m)}else a.j.Aa(l,d,"checked",f,!0)}}function f(){var d=a.a.c(c());q?b.checked=0<=a.a.A(d,h(),g):l?b.checked=d:b.checked=h()===d}var h=a.Ac(function(){return d.has("checkedValue")?a.a.c(d.get("checkedValue")):d.has("value")?a.a.c(d.get("value")):b.value}),g=d.has("checkedArrayContainsObservables")&&d.get("checkedArrayContainsObservables"),
l="checkbox"==b.type,k="radio"==b.type;if(l||k){var m=c(),q=l&&a.a.c(m)instanceof Array,r=!(q&&m.push&&m.splice),p=q?h():n,z=k||q;k&&!b.name&&a.f.uniqueName.init(b,function(){return!0});a.u(e,null,{l:b});a.a.C(b,"click",e);a.u(f,null,{l:b});m=n}}};a.j.pa.checked=!0;a.f.checkedValue={update:function(b,c){b.value=a.a.c(c())}}})();a.f["class"]={update:function(b,c){var d=a.a.pb(a.a.c(c()));a.a.rb(b,b.__ko__cssValue,!1);b.__ko__cssValue=d;a.a.rb(b,d,!0)}};a.f.css={update:function(b,c){var d=a.a.c(c());
null!==d&&"object"==typeof d?a.a.L(d,function(c,d){d=a.a.c(d);a.a.rb(b,c,d)}):a.f["class"].update(b,c)}};a.f.enable={update:function(b,c){var d=a.a.c(c());d&&b.disabled?b.removeAttribute("disabled"):d||b.disabled||(b.disabled=!0)}};a.f.disable={update:function(b,c){a.f.enable.update(b,function(){return!a.a.c(c())})}};a.f.event={init:function(b,c,d,e,f){var h=c()||{};a.a.L(h,function(g){"string"==typeof g&&a.a.C(b,g,function(b){var h,m=c()[g];if(m){try{var q=a.a.fa(arguments);e=f.$data;q.unshift(e);
h=m.apply(e,q)}finally{!0!==h&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===d.get(g+"Bubble")&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.f.foreach={vc:function(b){return function(){var c=b(),d=a.a.za(c);if(!d||"number"==typeof d.length)return{foreach:c,templateEngine:a.X.Ca};a.a.c(c);return{foreach:d.data,separatorTemplate:d.separatorTemplate,as:d.as,includeDestroyed:d.includeDestroyed,afterAdd:d.afterAdd,beforeRemove:d.beforeRemove,afterRender:d.afterRender,
beforeMove:d.beforeMove,afterMove:d.afterMove,templateEngine:a.X.Ca}}},init:function(b,c){return a.f.template.init(b,a.f.foreach.vc(c))},update:function(b,c,d,e,f){return a.f.template.update(b,a.f.foreach.vc(c),d,e,f)}};a.j.Ha.foreach=!1;a.g.$.foreach=!0;a.f.hasfocus={init:function(b,c,d){function e(e){b.__ko_hasfocusUpdating=!0;var f=b.ownerDocument;if("activeElement"in f){var h;try{h=f.activeElement}catch(m){h=f.body}e=h===b}f=c();a.j.Aa(f,d,"hasfocus",e,!0);b.__ko_hasfocusLastValue=e;b.__ko_hasfocusUpdating=
!1}var f=e.bind(null,!0),h=e.bind(null,!1);a.a.C(b,"focus",f);a.a.C(b,"focusin",f);a.a.C(b,"blur",h);a.a.C(b,"focusout",h)},update:function(b,c){var d=!!a.a.c(c());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===d||(d?b.focus():b.blur(),!d&&b.__ko_hasfocusLastValue&&b.ownerDocument.body.focus(),a.s.I(a.a.Ra,null,[b,d?"focusin":"focusout"]))}};a.j.pa.hasfocus=!0;a.f.hasFocus=a.f.hasfocus;a.j.pa.hasFocus=!0;a.f.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.Mb(b,
c())}};L("if");L("ifnot",!1,!0);L("with",!0,!1,function(a,c){return a.hc(c)});a.f.let={init:function(b,c,d,e,f){c=f.extend(c);a.Fa(c,b);return{controlsDescendantBindings:!0}}};a.g.$.let=!0;var M={};a.f.options={init:function(b){if("select"!==a.a.K(b))throw Error("options binding applies only to SELECT elements");for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,c,d){function e(){return a.a.Xa(b.options,function(a){return a.selected})}function f(a,b,c){var d=typeof b;
return"function"==d?b(a):"string"==d?a[b]:c}function h(c,e){if(z&&m)a.m.sa(b,a.a.c(d.get("value")),!0);else if(p.length){var f=0<=a.a.A(p,a.m.H(e[0]),!0);a.a.Gc(e[0],f);z&&!f&&a.s.I(a.a.Ra,null,[b,"change"])}}var g=b.multiple,l=0!=b.length&&g?b.scrollTop:null,k=a.a.c(c()),m=d.get("valueAllowUnset")&&d.has("value"),q=d.get("optionsIncludeDestroyed");c={};var r,p=[];m||(g?p=a.a.ub(e(),a.m.H):0<=b.selectedIndex&&p.push(a.m.H(b.options[b.selectedIndex])));k&&("undefined"==typeof k.length&&(k=[k]),r=a.a.Xa(k,
function(b){return q||b===n||null===b||!a.a.c(b._destroy)}),d.has("optionsCaption")&&(k=a.a.c(d.get("optionsCaption")),null!==k&&k!==n&&r.unshift(M)));var z=!1;c.beforeRemove=function(a){b.removeChild(a)};k=h;d.has("optionsAfterRender")&&"function"==typeof d.get("optionsAfterRender")&&(k=function(b,c){h(0,c);a.s.I(d.get("optionsAfterRender"),null,[c[0],b!==M?b:n])});a.a.Lb(b,r,function(c,e,g){g.length&&(p=!m&&g[0].selected?[a.m.H(g[0])]:[],z=!0);e=b.ownerDocument.createElement("option");c===M?(a.a.ob(e,
d.get("optionsCaption")),a.m.sa(e,n)):(g=f(c,d.get("optionsValue"),c),a.m.sa(e,a.a.c(g)),c=f(c,d.get("optionsText"),g),a.a.ob(e,c));return[e]},c,k);a.s.I(function(){if(m)a.m.sa(b,a.a.c(d.get("value")),!0);else{var c;g?c=p.length&&e().length<p.length:c=p.length&&0<=b.selectedIndex?a.m.H(b.options[b.selectedIndex])!==p[0]:p.length||0<=b.selectedIndex;c&&a.a.Ra(b,"change")}});a.a.bd(b);l&&20<Math.abs(l-b.scrollTop)&&(b.scrollTop=l)}};a.f.options.Hb=a.a.h.S();a.f.selectedOptions={after:["options","foreach"],
init:function(b,c,d){a.a.C(b,"change",function(){var e=c(),f=[];a.a.D(b.getElementsByTagName("option"),function(b){b.selected&&f.push(a.a.Cd(a.m.H(b)))});a.j.Aa(e,d,"selectedOptions",f)})},update:function(b,c){if("select"!=a.a.K(b))throw Error("values binding applies only to SELECT elements");var d=a.a.c(c()),e=b.scrollTop;d&&"number"==typeof d.length&&a.a.D(b.getElementsByTagName("option"),function(b){var c=0<=a.a.A(d,a.m.H(b),!0);b.selected!=c&&a.a.Gc(b,c)});b.scrollTop=e}};a.j.pa.selectedOptions=
!0;a.f.style={update:function(b,c){var d=a.a.c(c()||{});a.a.L(d,function(c,d){d=a.a.c(d);if(null===d||d===n||!1===d)d="";b.style[c]=d})}};a.f.submit={init:function(b,c,d,e,f){if("function"!=typeof c())throw Error("The value for a submit binding must be a function");a.a.C(b,"submit",function(a){var d,e=c();try{d=e.call(f.$data,b)}finally{!0!==d&&(a.preventDefault?a.preventDefault():a.returnValue=!1)}})}};a.f.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.ob(b,
c())}};a.g.$.text=!0;(function(){if(y&&y.navigator){var b=function(a){if(a)return parseFloat(a[1])},c=y.navigator.userAgent,d,e,f,h;(d=y.opera&&y.opera.version&&parseInt(y.opera.version()))||b(c.match(/Chrome\/([^ ]+)/))||(e=b(c.match(/Version\/([^ ]+) Safari/)))||(f=b(c.match(/Firefox\/([^ ]+)/)))||(h=a.a.ca||b(c.match(/MSIE ([^ ]+)/)))||(h=b(c.match(/rv:([^ )]+)/)))}if(8<=h&&10>h)var g=a.a.h.S(),l=a.a.h.S(),k=function(b){var c=this.activeElement;(c=c&&a.a.h.get(c,l))&&c(b)},m=function(b,c){var d=
b.ownerDocument;a.a.h.get(d,g)||(a.a.h.set(d,g,!0),a.a.C(d,"selectionchange",k));a.a.h.set(b,l,c)};a.f.textInput={init:function(b,c,g){function l(c,d){a.a.C(b,c,d)}function k(){var d=a.a.c(c());if(null===d||d===n)d="";t!==n&&d===t?a.a.setTimeout(k,4):b.value!==d&&(H=d,b.value=d)}function x(){u||(t=b.value,u=a.a.setTimeout(G,4))}function G(){clearTimeout(u);t=u=n;var d=b.value;H!==d&&(H=d,a.j.Aa(c(),g,"textInput",d))}var H=b.value,u,t,v=9==a.a.ca?x:G;h&&l("keypress",G);11>h&&l("propertychange",function(a){"value"===
a.propertyName&&v(a)});8==h&&(l("keyup",G),l("keydown",G));m&&(m(b,v),l("dragend",x));(!h||9<=h)&&l("input",v);5>e&&"textarea"===a.a.K(b)?(l("keydown",x),l("paste",x),l("cut",x)):11>d?l("keydown",x):4>f&&(l("DOMAutoComplete",G),l("dragdrop",G),l("drop",G));l("change",G);l("blur",G);a.u(k,null,{l:b})}};a.j.pa.textInput=!0;a.f.textinput={preprocess:function(a,b,c){c("textInput",a)}}})();a.f.uniqueName={init:function(b,c){if(c()){var d="ko_unique_"+ ++a.f.uniqueName.Xc;a.a.Fc(b,d)}}};a.f.uniqueName.Xc=
0;a.f.using={init:function(b,c,d,e,f){c=f.createChildContext(c);a.Fa(c,b);return{controlsDescendantBindings:!0}}};a.g.$.using=!0;a.f.value={after:["options","foreach"],init:function(b,c,d){var e=a.a.K(b),f="input"==e;if(!f||"checkbox"!=b.type&&"radio"!=b.type){var h=["change"],g=d.get("valueUpdate"),l=!1,k=null;g&&("string"==typeof g&&(g=[g]),a.a.Ya(h,g),h=a.a.cc(h));var m=function(){a.ja.Kb(function(){k=null;l=!1;var e=c(),f=a.m.H(b);a.j.Aa(e,d,"value",f)})};!a.a.ca||!f||"text"!=b.type||"off"==b.autocomplete||
b.form&&"off"==b.form.autocomplete||-1!=a.a.A(h,"propertychange")||(a.a.C(b,"propertychange",function(){l=!0}),a.a.C(b,"focus",function(){l=!1}),a.a.C(b,"blur",function(){l&&m()}));a.a.D(h,function(c){var d=m;a.a.Ad(c,"after")&&(d=function(){k=a.m.H(b);a.a.setTimeout(m,0)},c=c.substring(5));a.a.C(b,c,d)});var q;q=f&&"file"==b.type?function(){var d=a.a.c(c());null===d||d===n||""===d?b.value="":m()}:function(){var f=a.a.c(c()),g=a.m.H(b);if(null!==k&&f===k)a.a.setTimeout(q,0);else if(f!==g)if("select"===
e){var l=d.get("valueAllowUnset"),h=function(){a.m.sa(b,f,l);a.j.Aa(c(),d,"value",f)};a.ja.Kb(function(){h();l||f===a.m.H(b)?a.a.setTimeout(h,0):a.s.I(a.a.Ra,null,[b,"change"])})}else a.m.sa(b,f)};a.u(q,null,{l:b})}else a.Wa(b,{checkedValue:c})},update:function(){}};a.j.pa.value=!0;a.f.visible={update:function(b,c){var d=a.a.c(c()),e="none"!=b.style.display;d&&!e?b.style.display="":!d&&e&&(b.style.display="none")}};(function(b){a.f[b]={init:function(c,d,e,f,h){return a.f.event.init.call(this,c,function(){var a=
{};a[b]=d();return a},e,f,h)}}})("click");a.Y=function(){};a.Y.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");};a.Y.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");};a.Y.prototype.makeTemplateSource=function(b,c){if("string"==typeof b){c=c||t;var d=c.getElementById(b);if(!d)throw Error("Cannot find template with ID "+b);return new a.w.v(d)}if(1==b.nodeType||8==b.nodeType)return new a.w.ha(b);throw Error("Unknown template type: "+
b);};a.Y.prototype.renderTemplate=function(a,c,d,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,c,d,e)};a.Y.prototype.isTemplateRewritten=function(a,c){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,c).data("isRewritten")};a.Y.prototype.rewriteTemplate=function(a,c,d){a=this.makeTemplateSource(a,d);c=c(a.text());a.text(c);a.data("isRewritten",!0)};a.b("templateEngine",a.Y);a.Qb=function(){function b(b,c,d,g){b=a.j.Ib(b);for(var l=a.j.Ha,k=0;k<b.length;k++){var m=
b[k].key;if(Object.prototype.hasOwnProperty.call(l,m)){var q=l[m];if("function"===typeof q){if(m=q(b[k].value))throw Error(m);}else if(!q)throw Error("This template engine does not support the '"+m+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.j.kb(b,{valueAccessors:!0})+" } })()},'"+d.toLowerCase()+"')";return g.createJavaScriptEvaluatorBlock(d)+c}var c=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'|[^>]*))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,
d=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{cd:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.Qb.rd(b,c)},d)},rd:function(a,f){return a.replace(c,function(a,c,d,e,m){return b(m,c,d,f)}).replace(d,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",f)})},Tc:function(b,c){return a.W.Gb(function(d,g){var l=d.nextSibling;l&&l.nodeName.toLowerCase()===c&&a.Wa(l,b,g)})}}}();a.b("__tr_ambtns",a.Qb.Tc);(function(){a.w={};a.w.v=function(b){if(this.v=b){var c=
a.a.K(b);this.qb="script"===c?1:"textarea"===c?2:"template"==c&&b.content&&11===b.content.nodeType?3:4}};a.w.v.prototype.text=function(){var b=1===this.qb?"text":2===this.qb?"value":"innerHTML";if(0==arguments.length)return this.v[b];var c=arguments[0];"innerHTML"===b?a.a.Mb(this.v,c):this.v[b]=c};var b=a.a.h.S()+"_";a.w.v.prototype.data=function(c){if(1===arguments.length)return a.a.h.get(this.v,b+c);a.a.h.set(this.v,b+c,arguments[1])};var c=a.a.h.S();a.w.v.prototype.nodes=function(){var b=this.v;
if(0==arguments.length)return(a.a.h.get(b,c)||{}).yb||(3===this.qb?b.content:4===this.qb?b:n);a.a.h.set(b,c,{yb:arguments[0]})};a.w.ha=function(a){this.v=a};a.w.ha.prototype=new a.w.v;a.w.ha.prototype.constructor=a.w.ha;a.w.ha.prototype.text=function(){if(0==arguments.length){var b=a.a.h.get(this.v,c)||{};b.Rb===n&&b.yb&&(b.Rb=b.yb.innerHTML);return b.Rb}a.a.h.set(this.v,c,{Rb:arguments[0]})};a.b("templateSources",a.w);a.b("templateSources.domElement",a.w.v);a.b("templateSources.anonymousTemplate",
a.w.ha)})();(function(){function b(b,c,d){var e;for(c=a.g.nextSibling(c);b&&(e=b)!==c;)b=a.g.nextSibling(e),d(e,b)}function c(c,d){if(c.length){var e=c[0],f=c[c.length-1],g=e.parentNode,h=a.ba.instance,n=h.preprocessNode;if(n){b(e,f,function(a,b){var c=a.previousSibling,d=n.call(h,a);d&&(a===e&&(e=d[0]||b),a===f&&(f=d[d.length-1]||c))});c.length=0;if(!e)return;e===f?c.push(e):(c.push(e,f),a.a.Ma(c,g))}b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.ac(d,b)});b(e,f,function(b){1!==b.nodeType&&
8!==b.nodeType||a.W.Mc(b,[d])});a.a.Ma(c,g)}}function d(a){return a.nodeType?a:0<a.length?a[0]:null}function e(b,e,f,g,r){r=r||{};var p=(b&&d(b)||f||{}).ownerDocument,n=r.templateEngine||h;a.Qb.cd(f,n,p);f=n.renderTemplate(f,g,r,p);if("number"!=typeof f.length||0<f.length&&"number"!=typeof f[0].nodeType)throw Error("Template engine must return an array of DOM nodes");p=!1;switch(e){case "replaceChildren":a.g.oa(b,f);p=!0;break;case "replaceNode":a.a.Ec(b,f);p=!0;break;case "ignoreTargetNode":break;
default:throw Error("Unknown renderMode: "+e);}p&&(c(f,g),r.afterRender&&a.s.I(r.afterRender,null,[f,g.$data]));return f}function f(b,c,d){return a.J(b)?b():"function"===typeof b?b(c,d):b}var h;a.Nb=function(b){if(b!=n&&!(b instanceof a.Y))throw Error("templateEngine must inherit from ko.templateEngine");h=b};a.Jb=function(b,c,g,q,r){g=g||{};if((g.templateEngine||h)==n)throw Error("Set a template engine before calling renderTemplate");r=r||"replaceChildren";if(q){var p=d(q);return a.N(function(){var h=
c&&c instanceof a.aa?c:new a.aa(c,null,null,null,{exportDependencies:!0}),n=f(b,h.$data,h),h=e(q,r,n,h,g);"replaceNode"==r&&(q=h,p=d(q))},null,{wa:function(){return!p||!a.a.Cb(p)},l:p&&"replaceNode"==r?p.parentNode:p})}return a.W.Gb(function(d){a.Jb(b,c,g,d,"replaceNode")})};a.wd=function(b,d,g,h,r){function p(a,b){x!==n&&c(b.splice(0,x),r);c(b,t);g.afterRender&&g.afterRender(b,a);t=null}function u(c,d){var k=g.hierarchyRole;if(k){var p=[d],v=0,w="$"+(g.as||"item"),z={};"Child"===k&&(p=r.$indexPath.concat(p),
v=r.$hierarchyLevel+1);z.$index=d;z.$indexPath=p;z.$hierarchyLevel=v;z[w]=c;t=r.extend(z)}else t=r.createChildContext(c,g.as,function(a){a.$index=d});k=[];p=g.separatorTemplate;x=n;p&&0<a.a.za(d)&&(k=k.concat(e(h,"ignoreTargetNode",p,r,g)),x=k.length);p=f(b,c,t);return k=k.concat(e(h,"ignoreTargetNode",p,t,g))}var t,x;return a.N(function(){var b=a.a.c(d)||[];"undefined"==typeof b.length&&(b=[b]);b=a.a.Xa(b,function(b){return g.includeDestroyed||b===n||null===b||!a.a.c(b._destroy)});a.s.I(a.a.Lb,null,
[h,b,u,g,p])},null,{l:h})};var g=a.a.h.S();a.f.template={init:function(b,c){var d=a.a.c(c());if("string"==typeof d||d.name)a.g.Ka(b);else{if("nodes"in d){d=d.nodes||[];if(a.J(d))throw Error('The "nodes" option must be a plain, non-observable array.');d=a.a.wc(d)}else d=a.g.childNodes(b),d=a.a.wc(d);(new a.w.ha(b)).nodes(d)}return{controlsDescendantBindings:!0}},update:function(b,c,d,e,f){var h=c();c=a.a.c(h);d=!0;e=null;"string"==typeof c?c={}:(h=c.name,"if"in c&&(d=a.a.c(c["if"])),d&&"ifnot"in c&&
(d=!a.a.c(c.ifnot)));"foreach"in c?e=a.wd(h||b,d&&c.foreach||[],c,b,f):d?(f="data"in c?f.hc(c.data,c.as):f,e=a.Jb(h||b,f,c,b)):a.g.Ka(b);f=e;(c=a.a.h.get(b,g))&&"function"==typeof c.o&&c.o();a.a.h.set(b,g,f&&f.ka()?f:n)}};a.j.Ha.template=function(b){b=a.j.Ib(b);return 1==b.length&&b[0].unknown||a.j.od(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};a.g.$.template=!0})();a.b("setTemplateEngine",a.Nb);a.b("renderTemplate",a.Jb);a.a.oc=function(a,
c,d){if(a.length&&c.length){var e,f,h,g,l;for(e=f=0;(!d||e<d)&&(g=a[f]);++f){for(h=0;l=c[h];++h)if(g.value===l.value){g.moved=l.index;l.moved=g.index;c.splice(h,1);e=h=0;break}e+=h}}};a.a.xb=function(){function b(b,d,e,f,h){var g=Math.min,l=Math.max,k=[],m,q=b.length,n,p=d.length,t=p-q||1,u=q+p+1,x,w,y;for(m=0;m<=q;m++)for(w=x,k.push(x=[]),y=g(p,m+t),n=l(0,m-1);n<=y;n++)x[n]=n?m?b[m-1]===d[n-1]?w[n-1]:g(w[n]||u,x[n-1]||u)+1:n+1:m+1;g=[];l=[];t=[];m=q;for(n=p;m||n;)p=k[m][n]-1,n&&p===k[m][n-1]?l.push(g[g.length]=
{status:e,value:d[--n],index:n}):m&&p===k[m-1][n]?t.push(g[g.length]={status:f,value:b[--m],index:m}):(--n,--m,h.sparse||g.push({status:"retained",value:d[n]}));a.a.oc(t,l,!h.dontLimitMoves&&10*q);return g.reverse()}return function(a,d,e){e="boolean"===typeof e?{dontLimitMoves:e}:e||{};a=a||[];d=d||[];return a.length<d.length?b(a,d,"added","deleted",e):b(d,a,"deleted","added",e)}}();a.b("utils.compareArrays",a.a.xb);(function(){function b(b,c,d,g,l){var k=[],m=a.N(function(){var m=c(d,l,a.a.Ma(k,
b))||[];0<k.length&&(a.a.Ec(k,m),g&&a.s.I(g,null,[d,m,l]));k.length=0;a.a.Ya(k,m)},null,{l:b,wa:function(){return!a.a.$b(k)}});return{na:k,N:m.ka()?m:n}}var c=a.a.h.S(),d=a.a.h.S();a.a.Lb=function(e,f,h,g,l){function k(b,c){v=r[c];w!==c&&(E[b]=v);v.Eb(w++);a.a.Ma(v.na,e);u.push(v);A.push(v)}function m(b,c){if(b)for(var d=0,e=c.length;d<e;d++)c[d]&&a.a.D(c[d].na,function(a){b(a,d,c[d].ua)})}f=f||[];g=g||{};var q=a.a.h.get(e,c)===n,r=a.a.h.get(e,c)||[],p=a.a.ub(r,function(a){return a.ua}),t=a.a.xb(p,
f,g.dontLimitMoves),u=[],x=0,w=0,y=[],A=[];f=[];for(var E=[],p=[],v,D=0,C,F;C=t[D];D++)switch(F=C.moved,C.status){case "deleted":F===n&&(v=r[x],v.N&&(v.N.o(),v.N=n),a.a.Ma(v.na,e).length&&(g.beforeRemove&&(u.push(v),A.push(v),v.ua===d?v=null:f[D]=v),v&&y.push.apply(y,v.na)));x++;break;case "retained":k(D,x++);break;case "added":F!==n?k(D,F):(v={ua:C.value,Eb:a.T(w++)},u.push(v),A.push(v),q||(p[D]=v))}a.a.h.set(e,c,u);m(g.beforeMove,E);a.a.D(y,g.beforeRemove?a.ia:a.removeNode);for(var D=0,q=a.g.firstChild(e),
I;v=A[D];D++){v.na||a.a.extend(v,b(e,h,v.ua,l,v.Eb));for(x=0;t=v.na[x];q=t.nextSibling,I=t,x++)t!==q&&a.g.sc(e,t,I);!v.kd&&l&&(l(v.ua,v.na,v.Eb),v.kd=!0)}m(g.beforeRemove,f);for(D=0;D<f.length;++D)f[D]&&(f[D].ua=d);m(g.afterMove,E);m(g.afterAdd,p)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.Lb);a.X=function(){this.allowTemplateRewriting=!1};a.X.prototype=new a.Y;a.X.prototype.constructor=a.X;a.X.prototype.renderTemplateSource=function(b,c,d,e){if(c=(9>a.a.ca?0:b.nodes)?b.nodes():null)return a.a.fa(c.cloneNode(!0).childNodes);
b=b.text();return a.a.ya(b,e)};a.X.Ca=new a.X;a.Nb(a.X.Ca);a.b("nativeTemplateEngine",a.X);(function(){a.Pa=function(){var a=this.nd=function(){if(!w||!w.tmpl)return 0;try{if(0<=w.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,f,h){h=h||t;f=f||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");var g=b.data("precompiled");g||(g=b.text()||"",g=w.template(null,"{{ko_with $item.koBindingContext}}"+
g+"{{/ko_with}}"),b.data("precompiled",g));b=[e.$data];e=w.extend({koBindingContext:e},f.templateOptions);e=w.tmpl(g,b,e);e.appendTo(h.createElement("div"));w.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){t.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(w.tmpl.tag.ko_code={open:"__.push($1 || '');"},w.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.Pa.prototype=
new a.Y;a.Pa.prototype.constructor=a.Pa;var b=new a.Pa;0<b.nd&&a.Nb(b);a.b("jqueryTmplTemplateEngine",a.Pa)})()})})();})();
