/*!
 * Knockout JavaScript library v3.5.1-pre
 * (c) The Knockout.js team - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {(function(n){var A=this||(0,eval)("this"),y=A.document,T=A.navigator,v=A.jQuery,I=A.JSON;v||"undefined"===typeof jQuery||(v=jQuery);(function(n){"function"===typeof define&&define.amd?define(["exports","require"],n):"object"===typeof exports&&"object"===typeof module?n(module.exports||exports):n(A.ko={})})(function(U,V){function N(a,c){return null===a||typeof a in Y?a===c:!1}function Z(b,c){var d;return function(){d||(d=a.a.setTimeout(function(){d=n;b()},c))}}function aa(b,c){var d;return function(){clearTimeout(d);
d=a.a.setTimeout(b,c)}}function ba(a,c){c&&"change"!==c?"beforeChange"===c?this.rc(a):this.hb(a,c):this.sc(a)}function J(a){if(this[P]){var c=this[P].call(this,a).newValue;c!==a&&(this[H]=c)}}function ca(a,c){null!==c&&c.u&&c.u()}function da(a,c){var d=this.qd,e=d[r];e.ua||(this.Sb&&this.nb[c]?(d.wc(c,a,this.nb[c]),this.nb[c]=null,--this.Sb):e.I[c]||d.wc(c,a,e.K?{da:a}:d.$c(a)),a.Ka&&a.gd())}var a="undefined"!==typeof U?U:{};a.b=function(b,c){for(var d=b.split("."),e=a,f=0;f<d.length-1;f++)e=e[d[f]];
e[d[d.length-1]]=c};a.M=function(a,c,d){a[c]=d};a.version="3.5.1-pre";a.b("version",a.version);a.options={deferUpdates:!1,useOnlyNativeEvents:!1,foreachHidesDestroyed:!1};a.ra=function(){var a=!1,c=[],d={pause:function(){a=!0},Td:function(){a=!1;for(var d=0;d<c.length;d++)c[d]();c=[]},fc:function(d){a?c.push(d):d()}};Object.defineProperty(d,"isPaused",{get:function(){return a},enumerable:!0,configurable:!0});return d}();a.b("delaySync",a.ra);a.b("delaySync.pause",a.ra.pause);a.b("delaySync.isPaused",
a.ra.isPaused);a.b("delaySync.resume",a.ra.Td);a.b("delaySync.run",a.ra.fc);a.a=function(){function b(a,b){for(var c in a)f.call(a,c)&&b(c,a[c])}function c(a,b){if(b)for(var c in b)f.call(b,c)&&(a[c]=b[c]);return a}function d(a,b){a.__proto__=b;return a}function e(b,c,d,e){var l=b[c].match(q)||[];a.a.A(d.match(q),function(b){a.a.Oa(l,b,e)});b[c]=l.join(" ")}var f=Object.prototype.hasOwnProperty,g={__proto__:[]}instanceof Array,h="function"===typeof Symbol,m={},k={};m[T&&/Firefox\/2/i.test(T.userAgent)?
"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];m.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(m,function(a,b){if(b.length)for(var c=0,d=b.length;c<d;c++)k[b[c]]=a});var l={propertychange:!0},p=y&&function(){for(var a=3,b=y.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:n}(),q=/\S+/g,x;return{Kc:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],
A:function(a,b,c){for(var d=0,e=a.length;d<e;d++)b.call(c,a[d],d,a)},B:function(b,c,d,e){e=e||function(a){return a};return a.s.C(function(){if(d)for(var l=e(a.a.c(c)),k=0,f=b.length;k<f;k++){if(e(a.a.c(b[k]))===l)return k}else{if(!e&&"function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(b,c);l=e(c);k=0;for(f=b.length;k<f;k++)if(e(b[k])===l)return k}return-1})},Nb:function(a,b,c){for(var d=0,e=a.length;d<e;d++)if(b.call(c,a[d],d,a))return a[d];return n},Qa:function(b,c){var d=
a.a.B(b,c);0<d?b.splice(d,1):0===d&&b.shift()},yc:function(b){var c=[];b&&a.a.A(b,function(b){0>a.a.B(c,b)&&c.push(b)});return c},Ob:function(a,b,c){var d=[];if(a)for(var e=0,l=a.length;e<l;e++)d.push(b.call(c,a[e],e));return d},kb:function(a,b,c){var d=[];if(a)for(var e=0,l=a.length;e<l;e++)b.call(c,a[e],e)&&d.push(a[e]);return d},Pb:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var c=0,d=b.length;c<d;c++)a.push(b[c]);return a},Oa:function(b,c,d,e,l){l=a.a.B(a.a.wb(b),c,e,l);e&&
!a.J(c)&&(c=a.ia(c));0>l?d&&b.push(c):d||b.splice(l,1)},Da:g,extend:c,setPrototypeOf:d,Cb:g?d:c,P:b,Ha:function(a,b,c){if(!a)return a;var d={},e;for(e in a)f.call(a,e)&&(d[e]=b.call(c,a[e],e,a));return d},Vb:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},$b:function(b){b=a.a.ma(b);for(var c=(b[0]&&b[0].ownerDocument||y).createElement("div"),d=0,e=b.length;d<e;d++)c.appendChild(a.pa(b[d]));return c},Ea:function(b,c){for(var d=0,e=b.length,l=[];d<e;d++){var k=b[d].cloneNode(!0);l.push(c?
a.pa(k):k)}return l},xa:function(b,c){a.a.Vb(b);if(c)for(var d=0,e=c.length;d<e;d++)b.appendChild(c[d])},Xc:function(b,c){var d=b.nodeType?[b]:b;if(0<d.length){for(var e=d[0],l=e.parentNode,k=0,f=c.length;k<f;k++)l.insertBefore(c[k],e);k=0;for(f=d.length;k<f;k++)a.removeNode(d[k])}},Va:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.splice(0,1);for(;1<a.length&&a[a.length-1].parentNode!==b;)a.length--;if(1<a.length){var c=a[0],d=a[a.length-1];for(a.length=
0;c!==d;)a.push(c),c=c.nextSibling;a.push(d)}}return a},Zc:function(a,b){7>p?a.setAttribute("selected",b):a.selected=b},Fb:function(a){return null===a||a===n?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Wd:function(a,b){a=a||"";return b.length>a.length?!1:a.substring(0,b.length)===b},vd:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;if(b.contains)return b.contains(1!==a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&
16);for(;a&&a!=b;)a=a.parentNode;return!!a},Ub:function(b){return a.a.vd(b,b.ownerDocument.documentElement)},kd:function(b){return!!a.a.Nb(b,a.a.Ub)},R:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},Bc:function(b){return a.onError?function(){try{return b.apply(this,arguments)}catch(c){throw a.onError&&a.onError(c),c;}}:b},setTimeout:function(b,c){return setTimeout(a.a.Bc(b),c)},Hc:function(b){setTimeout(function(){a.onError&&a.onError(b);throw b;},0)},D:function(b,c,d){var e=a.a.Bc(d);
d=l[c];if(!a.options.useOnlyNativeEvents&&!d&&v)x||(x="function"==typeof v(b).on?"on":"bind"),v(b)[x](c,e);else if(!d&&"function"==typeof b.addEventListener)b.addEventListener(c,e,!1);else if("undefined"!=typeof b.attachEvent){var k=function(a){e.call(b,a)},f="on"+c;b.attachEvent(f,k);a.a.L.Ba(b,function(){b.detachEvent(f,k)})}},Hb:function(b,c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var d;"input"===a.a.R(b)&&b.type&&"click"==c.toLowerCase()?(d=b.type,
d="checkbox"==d||"radio"==d):d=!1;if(a.options.useOnlyNativeEvents||!v||d)if("function"==typeof y.createEvent)if("function"==typeof b.dispatchEvent)d=y.createEvent(k[c]||"HTMLEvents"),d.initEvent(c,!0,!0,A,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(d);else throw Error("The supplied element doesn't support dispatchEvent");else if(d&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");else v(b).trigger(c)},c:function(b){return a.J(b)?
b():b},Zd:function(b){return a.J(b)?b:a.ia(b)},wb:function(b){return a.J(b)?b.v():b},Gb:function(b,c,d){var l;c&&("object"===typeof b.classList?(l=b.classList[d?"add":"remove"],a.a.A(c.match(q),function(a){l.call(b.classList,a)})):"string"===typeof b.className.baseVal?e(b.className,"baseVal",c,d):e(b,"className",c,d))},Db:function(b,c){var d=a.a.c(c);if(null===d||d===n)d="";var e=a.h.firstChild(b);!e||3!=e.nodeType||a.h.nextSibling(e)?a.h.xa(b,[b.ownerDocument.createTextNode(d)]):e.data=d;a.a.Bd(b)},
Yc:function(a,b){a.name=b;if(7>=p)try{var c=a.name.replace(/[&<>'"]/g,function(a){return"&#"+a.charCodeAt(0)+";"});a.mergeAttributes(y.createElement("<input name='"+c+"'/>"),!1)}catch(d){}},Bd:function(a){9<=p&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},wd:function(a){if(p){var b=a.style.width;a.style.width=0;a.style.width=b}},Qd:function(b,c){b=a.a.c(b);c=a.a.c(c);for(var d=[],e=b;e<=c;e++)d.push(e);return d},ma:function(a){for(var b=[],c=0,d=a.length;c<d;c++)b.push(a[c]);
return b},qa:function(a){return h?Symbol(a):a},be:6===p,ce:7===p,W:p,Lc:function(b,c){for(var d=a.a.ma(b.getElementsByTagName("input")).concat(a.a.ma(b.getElementsByTagName("textarea"))),e="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},l=[],k=d.length-1;0<=k;k--)e(d[k])&&l.push(d[k]);return l},Od:function(b){return"string"==typeof b&&(b=a.a.Fb(b))?I&&I.parse?I.parse(b):(new Function("return "+b))():null},jc:function(b,c,d){if(!I||!I.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");
return I.stringify(a.a.c(b),c,d)},Pd:function(c,d,e){e=e||{};var l=e.params||{},k=e.includeFields||this.Kc,f=c;if("object"==typeof c&&"form"===a.a.R(c))for(var f=c.action,h=k.length-1;0<=h;h--)for(var g=a.a.Lc(c,k[h]),m=g.length-1;0<=m;m--)l[g[m].name]=g[m].value;d=a.a.c(d);var p=y.createElement("form");p.style.display="none";p.action=f;p.method="post";for(var q in d)c=y.createElement("input"),c.type="hidden",c.name=q,c.value=a.a.jc(a.a.c(d[q])),p.appendChild(c);b(l,function(a,b){var c=y.createElement("input");
c.type="hidden";c.name=a;c.value=b;p.appendChild(c)});y.body.appendChild(p);e.submitter?e.submitter(p):p.submit();setTimeout(function(){p.parentNode.removeChild(p)},0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",a.a.A);a.b("utils.arrayFirst",a.a.Nb);a.b("utils.arrayFilter",a.a.kb);a.b("utils.arrayGetDistinctValues",a.a.yc);a.b("utils.arrayIndexOf",a.a.B);a.b("utils.arrayMap",a.a.Ob);a.b("utils.arrayPushAll",a.a.Pb);a.b("utils.arrayRemoveItem",a.a.Qa);a.b("utils.cloneNodes",a.a.Ea);a.b("utils.createSymbolOrString",
a.a.qa);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",a.a.Kc);a.b("utils.getFormFields",a.a.Lc);a.b("utils.objectMap",a.a.Ha);a.b("utils.peekObservable",a.a.wb);a.b("utils.postJson",a.a.Pd);a.b("utils.parseJson",a.a.Od);a.b("utils.registerEventHandler",a.a.D);a.b("utils.stringifyJson",a.a.jc);a.b("utils.range",a.a.Qd);a.b("utils.toggleDomNodeCssClass",a.a.Gb);a.b("utils.triggerEvent",a.a.Hb);a.b("utils.unwrapObservable",a.a.c);a.b("utils.objectForEach",a.a.P);a.b("utils.addOrRemoveItem",
a.a.Oa);a.b("utils.setTextContent",a.a.Db);a.b("unwrap",a.a.c);Function.prototype.bind||(Function.prototype.bind=function(a){var c=this;if(1===arguments.length)return function(){return c.apply(a,arguments)};var d=Array.prototype.slice.call(arguments,1);return function(){var e=d.slice(0);e.push.apply(e,arguments);return c.apply(a,e)}});a.a.g=new function(){var b=0,c="__ko__"+(new Date).getTime(),d={},e,f;a.a.W?(e=function(a,e){var f=a[c];if(!f||"null"===f||!d[f]){if(!e)return n;f=a[c]="ko"+b++;d[f]=
{}}return d[f]},f=function(a){var b=a[c];return b?(delete d[b],a[c]=null,!0):!1}):(e=function(a,b){var d=a[c];!d&&b&&(d=a[c]={});return d},f=function(a){return a[c]?(delete a[c],!0):!1});return{get:function(a,b){var c=e(a,!1);return c&&c[b]},set:function(a,b,c){(a=e(a,c!==n))&&(a[b]=c)},Wb:function(a,b,c){a=e(a,!0);return a[b]||(a[b]=c)},clear:f,Z:function(){return b++ +c}}};a.b("utils.domData",a.a.g);a.b("utils.domData.clear",a.a.g.clear);a.a.L=new function(){function b(b,c){var d=a.a.g.get(b,e);
d===n&&c&&(d=[],a.a.g.set(b,e,d));return d}function c(c){var e=b(c,!1);if(e)for(var e=e.slice(0),k=0;k<e.length;k++)e[k](c);a.a.g.clear(c);a.a.L.cleanExternalData(c);g[c.nodeType]&&d(c.childNodes,!0)}function d(b,d){for(var e=[],l,f=0;f<b.length;f++)if(!d||8===b[f].nodeType)if(c(e[e.length]=l=b[f]),b[f]!==l)for(;f--&&-1==a.a.B(e,b[f]););}var e=a.a.g.Z(),f={1:!0,8:!0,9:!0},g={1:!0,9:!0};return{Ba:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},Ab:function(c,
d){var f=b(c,!1);f&&(a.a.Qa(f,d),0==f.length&&a.a.g.set(c,e,n))},pa:function(b){a.s.C(function(){f[b.nodeType]&&(c(b),g[b.nodeType]&&d(b.getElementsByTagName("*")))});return b},removeNode:function(b){a.pa(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){v&&"function"==typeof v.cleanData&&v.cleanData([a])}}};a.pa=a.a.L.pa;a.removeNode=a.a.L.removeNode;a.b("cleanNode",a.pa);a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.L);a.b("utils.domNodeDisposal.addDisposeCallback",
a.a.L.Ba);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.L.Ab);(function(){var b=[0,"",""],c=[1,"<table>","</table>"],d=[3,"<table><tbody><tr>","</tr></tbody></table>"],e=[1,"<select multiple='multiple'>","</select>"],f={thead:c,tbody:c,tfoot:c,tr:[2,"<table><tbody>","</tbody></table>"],td:d,th:d,option:e,optgroup:e},g=8>=a.a.W;a.a.wa=function(c,d){var e;if(v)if(v.parseHTML)e=v.parseHTML(c,d)||[];else{if((e=v.clean([c],d))&&e[0]){for(var l=e[0];l.parentNode&&11!==l.parentNode.nodeType;)l=l.parentNode;
l.parentNode&&l.parentNode.removeChild(l)}}else{(e=d)||(e=y);var l=e.parentWindow||e.defaultView||A,p=a.a.Fb(c).toLowerCase(),q=e.createElement("div"),x;x=(p=p.match(/^(?:\x3c!--.*?--\x3e\s*?)*?<([a-z]+)[\s>]/))&&f[p[1]]||b;p=x[0];x="ignored<div>"+x[1]+c+x[2]+"</div>";"function"==typeof l.innerShiv?q.appendChild(l.innerShiv(x)):(g&&e.body.appendChild(q),q.innerHTML=x,g&&q.parentNode.removeChild(q));for(;p--;)q=q.lastChild;e=a.a.ma(q.lastChild.childNodes)}return e};a.a.Nd=function(b,c){var d=a.a.wa(b,
c);return d.length&&d[0].parentElement||a.a.$b(d)};a.a.hc=function(b,c){a.a.Vb(b);c=a.a.c(c);if(null!==c&&c!==n)if("string"!=typeof c&&(c=c.toString()),v)v(b).html(c);else for(var d=a.a.wa(c,b.ownerDocument),e=0;e<d.length;e++)b.appendChild(d[e])}})();a.b("utils.parseHtmlFragment",a.a.wa);a.b("utils.setHtml",a.a.hc);a.aa=function(){function b(c,e){if(c)if(8==c.nodeType){var f=a.aa.Uc(c.nodeValue);null!=f&&e.push({ud:c,Ld:f})}else if(1==c.nodeType)for(var f=0,g=c.childNodes,h=g.length;f<h;f++)b(g[f],
e)}var c={};return{Zb:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);c[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},bd:function(a,b){var f=c[a];if(f===n)throw Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized.");try{return f.apply(null,b||[]),!0}finally{delete c[a]}},cd:function(c,e){var f=
[];b(c,f);for(var g=0,h=f.length;g<h;g++){var m=f[g].ud,k=[m];e&&a.a.Pb(k,e);a.aa.bd(f[g].Ld,k);m.nodeValue="";m.parentNode&&m.parentNode.removeChild(m)}},Uc:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.aa);a.b("memoization.memoize",a.aa.Zb);a.b("memoization.unmemoize",a.aa.bd);a.b("memoization.parseMemoText",a.aa.Uc);a.b("memoization.unmemoizeDomNodeAndDescendants",a.aa.cd);a.oa=function(){function b(){if(f)for(var b=f,c=0,d;h<f;)if(d=e[h++]){if(h>b){if(5E3<=
++c){h=f;a.a.Hc(Error("'Too much recursion' after processing "+c+" task groups."));break}b=f}try{d()}catch(p){a.a.Hc(p)}}}function c(){b();h=f=e.length=0}var d,e=[],f=0,g=1,h=0;A.MutationObserver?d=function(a){var b=y.createElement("div");(new MutationObserver(a)).observe(b,{attributes:!0});return function(){b.classList.toggle("foo")}}(c):d=y&&"onreadystatechange"in y.createElement("script")?function(a){var b=y.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;y.documentElement.removeChild(b);
b=null;a()};y.documentElement.appendChild(b)}:function(a){setTimeout(a,0)};return{scheduler:d,Bb:function(b){f||a.oa.scheduler(c);e[f++]=b;return g++},cancel:function(a){a=a-(g-f);a>=h&&a<f&&(e[a]=null)},resetForTesting:function(){var a=f-h;h=f=e.length=0;return a},Ud:b}}();a.b("tasks",a.oa);a.b("tasks.schedule",a.oa.Bb);a.b("tasks.runEarly",a.oa.Ud);a.Ua={throttle:function(b,c){b.throttleEvaluation=c;var d=null;return a.$({read:b,write:function(e){clearTimeout(d);d=a.a.setTimeout(function(){b(e)},
c)}})},rateLimit:function(a,c){var d,e,f;"number"==typeof c?d=c:(d=c.timeout,e=c.method);a.Jb=!1;f="function"==typeof e?e:"notifyWhenChangesStop"==e?aa:Z;a.vb(function(a){return f(a,d,c)})},deferred:function(b,c){if(!0!==c)throw Error("The 'deferred' extender only accepts the value 'true', because it is not supported to turn deferral off once enabled.");b.Jb||(b.Jb=!0,b.vb(function(c){var e,f=!1;return function(){if(!f){a.oa.cancel(e);e=a.oa.Bb(c);try{f=!0,b.notifySubscribers(n,"dirty")}finally{f=
!1}}}}))},notify:function(a,c){a.equalityComparer="always"==c?null:N}};var Y={undefined:1,"boolean":1,number:1,string:1};a.b("extenders",a.Ua);a.kc=function(b,c,d){this.da=b;this.nc=c;this.oc=d;this.Kb=!1;this.gb=this.Lb=null;a.M(this,"dispose",this.u);a.M(this,"disposeWhenNodeIsRemoved",this.l)};a.kc.prototype.u=function(){this.Kb||(this.gb&&a.a.L.Ab(this.Lb,this.gb),this.Kb=!0,this.oc(),this.da=this.nc=this.oc=this.Lb=this.gb=null)};a.kc.prototype.l=function(b){this.Lb=b;a.a.L.Ba(b,this.gb=this.u.bind(this))};
a.T=function(){a.a.Cb(this,D);D.rb(this)};var D={rb:function(a){a.U={change:[]};a.uc=1},subscribe:function(b,c,d){var e=this;d=d||"change";var f=new a.kc(e,c?b.bind(c):b,function(){a.a.Qa(e.U[d],f);e.ib&&e.ib(d)});e.Ra&&e.Ra(d);e.U[d]||(e.U[d]=[]);e.U[d].push(f);return f},notifySubscribers:function(b,c){c=c||"change";"change"===c&&this.Ib();if(this.Xa(c)){var d="change"===c&&this.ed||this.U[c].slice(0);try{a.s.zc();for(var e=0,f;f=d[e];++e)f.Kb||f.nc(b)}finally{a.s.end()}}},pb:function(){return this.uc},
Ed:function(a){return this.pb()!==a},Ib:function(){++this.uc},vb:function(b){var c=this,d=a.J(c),e,f,g,h,m;c.hb||(c.hb=c.notifySubscribers,c.notifySubscribers=ba);var k=b(function(){c.Ka=!1;d&&h===c&&(h=c.pc?c.pc():c());var a=f||m&&c.tb(g,h);m=f=e=!1;a&&c.hb(g=h)});c.sc=function(a,b){b&&c.Ka||(m=!b);c.ed=c.U.change.slice(0);c.Ka=e=!0;h=a;k()};c.rc=function(a){e||(g=a,c.hb(a,"beforeChange"))};c.tc=function(){m=!0};c.gd=function(){c.tb(g,c.v(!0))&&(f=!0)}},Xa:function(a){return this.U[a]&&this.U[a].length},
Cd:function(b){if(b)return this.U[b]&&this.U[b].length||0;var c=0;a.a.P(this.U,function(a,b){"dirty"!==a&&(c+=b.length)});return c},tb:function(a,c){return!this.equalityComparer||!this.equalityComparer(a,c)},toString:function(){return"[object Object]"},extend:function(b){var c=this;b&&a.a.P(b,function(b,e){var f=a.Ua[b];"function"==typeof f&&(c=f(c,e)||c)});return c}};a.M(D,"init",D.rb);a.M(D,"subscribe",D.subscribe);a.M(D,"extend",D.extend);a.M(D,"getSubscriptionsCount",D.Cd);a.a.Da&&a.a.setPrototypeOf(D,
Function.prototype);a.T.fn=D;a.Qc=function(a){return null!=a&&"function"==typeof a.subscribe&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.T);a.b("isSubscribable",a.Qc);a.S=a.s=function(){function b(a){d.push(e);e=a}function c(){e=d.pop()}var d=[],e,f=0;return{zc:b,end:c,dc:function(b){if(e){if(!a.Qc(b))throw Error("Only subscribable things can act as dependencies");e.od.call(e.pd,b,b.fd||(b.fd=++f))}},C:function(a,d,e){try{return b(),a.apply(d,e||[])}finally{c()}},ta:function(){if(e)return e.o.ta()},
Wa:function(){if(e)return e.o.Wa()},Za:function(){if(e)return e.Za},o:function(){if(e)return e.o}}}();a.b("computedContext",a.S);a.b("computedContext.getDependenciesCount",a.S.ta);a.b("computedContext.getDependencies",a.S.Wa);a.b("computedContext.isInitial",a.S.Za);a.b("computedContext.registerDependency",a.S.dc);a.b("ignoreDependencies",a.ae=a.s.C);var H=a.a.qa("_latestValue"),P=a.a.qa("_validator");a.ia=function(b,c){function d(){if(0<arguments.length){var b=arguments[0],f;c&&(result=c.call(d,b),
b=result.newValue,f=result.de);if(d.tb(d[H],b)||f)d.Aa(),d[H]=b,d.za();return this}a.s.dc(d);return d[H]}d[H]=b;d[P]=c;a.a.Da||a.a.extend(d,a.T.fn);a.T.fn.rb(d);a.a.Cb(d,F);a.options.deferUpdates&&a.Ua.deferred(d,!0);return d};var F={equalityComparer:N,v:function(){return this[H]},za:function(){this.notifySubscribers(this[H],"spectate");this.notifySubscribers(this[H])},Aa:function(){this.notifySubscribers(this[H],"beforeChange")}};a.a.Da&&a.a.setPrototypeOf(F,a.T.fn);var G=a.ia.Na="__ko_proto__";
F[G]=a.ia;a.J=function(b){if((b="function"==typeof b&&b[G])&&b!==F[G]&&b!==a.o.fn[G])throw Error("Invalid object that looks like an observable; possibly from another Knockout instance");return!!b};a.$a=function(b){return"function"==typeof b&&(b[G]===F[G]||b[G]===a.o.fn[G]&&b.Nc)};a.b("observable",a.ia);a.b("isObservable",a.J);a.b("isWriteableObservable",a.$a);a.b("isWritableObservable",a.$a);a.b("observable.fn",F);a.M(F,"peek",F.v);a.M(F,"valueHasMutated",F.za);a.M(F,"valueWillMutate",F.Aa);a.Ia=
function(b,c){b=b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");var d=a.ia(b,c);a.a.Cb(d,a.Ia.fn);return d.extend({trackArrayChanges:!0})};a.Ia.fn={remove:function(b){for(var c=this.v(),d=[],e="function"!=typeof b||a.J(b)?function(a){return a===b}:b,f=0;f<c.length;f++){var g=c[f];if(e(g)){0===d.length&&this.Aa();if(c[f]!==g)throw Error("Array modified during remove; cannot remove item");
d.push(g);c.splice(f,1);f--}}d.length&&(J.call(this,c),this.za());return d},removeAll:function(b){if(b===n){var c=this.v(),d=c.slice(0);this.Aa();c.splice(0,c.length);this.za();return d}return b?this.remove(function(c){return 0<=a.a.B(b,c)}):[]},destroy:function(b){var c=this.v(),d="function"!=typeof b||a.J(b)?function(a){return a===b}:b;this.Aa();for(var e=c.length-1;0<=e;e--){var f=c[e];d(f)&&(f._destroy=!0)}J.call(this,c);this.za()},destroyAll:function(b){return b===n?this.destroy(function(){return!0}):
b?this.destroy(function(c){return 0<=a.a.B(b,c)}):[]},indexOf:function(b){var c=this();return a.a.B(c,b)},replace:function(a,c){var d=this.indexOf(a);if(0<=d){this.Aa();var e=this.v();e[d]=c;J.call(this,e);this.za()}},sorted:function(a){var c=this().slice(0);return a?c.sort(a):c.sort()},reversed:function(){return this().slice(0).reverse()}};a.a.Da&&a.a.setPrototypeOf(a.Ia.fn,a.ia.fn);a.a.A("pop push reverse shift sort splice unshift".split(" "),function(b){a.Ia.fn[b]=function(){var a=this.v();this.Aa();
var d=a[b].apply(a,arguments);J.call(this,a);this.za();return d===a?this:d}});a.a.A(["slice"],function(b){a.Ia.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.Pc=function(b){return a.J(b)&&"function"==typeof b.remove&&"function"==typeof b.push};a.b("observableArray",a.Ia);a.b("isObservableArray",a.Pc);var W=Symbol();a.Ua.trackArrayChanges=function(b,c){function d(){function c(){if(m){var d=[].concat(b.v()||[]),e;if(b.Xa("arrayChange")){if(!f||1<m)f=a.a.Rb(k,d,b.Qb);e=f}k=d;f=null;
m=0;e&&e.length&&b.notifySubscribers(e,"arrayChange")}}e?c():(e=!0,h=b.subscribe(function(){++m},null,"spectate"),k=[].concat(b.v()||[]),f=null,g=b.subscribe(c))}b.Qb={};c&&"object"==typeof c&&a.a.extend(b.Qb,c);b.Qb.sparse=!0;if(!b[W]){b[W]=!0;var e=!1,f=null,g,h,m=0,k,l=b.Ra,p=b.ib;b.Ra=function(a){l&&l.call(b,a);"arrayChange"===a&&d()};b.ib=function(a){p&&p.call(b,a);"arrayChange"!==a||b.Xa("arrayChange")||(g&&g.u(),h&&h.u(),h=g=null,e=!1,k=n)}}};var r=a.a.qa("_state");a.o=a.$=function(b,c,d){function e(){if(0<
arguments.length){if("function"===typeof f)f.apply(g.ob,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this}g.ua||a.s.dc(e);(g.la||g.K&&e.Ya())&&e.ha();return g.X}"object"===typeof b?d=b:(d=d||{},b&&(d.read=b));if("function"!=typeof d.read)throw Error("Pass a function that returns the value of the ko.computed");var f=d.write,g={X:n,va:!0,la:!0,sb:!1,lc:!1,ua:!1,yb:!1,
K:!1,Wc:d.read,ob:c||d.owner,l:d.disposeWhenNodeIsRemoved||d.l||null,Ta:d.disposeWhen||d.Ta,Tb:null,I:{},V:0,Jc:null};e[r]=g;e.Nc="function"===typeof f;a.a.Da||a.a.extend(e,a.T.fn);a.T.fn.rb(e);a.a.Cb(e,B);d.pure?(g.yb=!0,g.K=!0,a.a.extend(e,fa)):d.deferEvaluation&&a.a.extend(e,ga);a.options.deferUpdates&&a.Ua.deferred(e,!0);g.l&&(g.lc=!0,g.l.nodeType||(g.l=null));g.K||d.deferEvaluation||e.ha();g.l&&e.ka()&&a.a.L.Ba(g.l,g.Tb=function(){e.u()});return e};var B={equalityComparer:N,ta:function(){return this[r].V},
Wa:function(){var b=[];a.a.P(this[r].I,function(a,d){b[d.La]=d.da});return b},Xb:function(b){if(!this[r].V)return!1;var c=this.Wa();return-1!==a.a.B(c,b)?!0:!!a.a.Nb(c,function(a){return a.Xb&&a.Xb(b)})},wc:function(a,c,d){if(this[r].yb&&c===this)throw Error("A 'pure' computed must not be called recursively");this[r].I[a]=d;d.La=this[r].V++;d.Ma=c.pb()},Ya:function(){var a,c,d=this[r].I;for(a in d)if(Object.prototype.hasOwnProperty.call(d,a)&&(c=d[a],this.Ja&&c.da.Ka||c.da.Ed(c.Ma)))return!0},Kd:function(){this.Ja&&
!this[r].sb&&this.Ja(!1)},ka:function(){var a=this[r];return a.la||0<a.V},Sd:function(){this.Ka?this[r].la&&(this[r].va=!0):this.Ic()},$c:function(a){if(a.Jb){var c=a.subscribe(this.Kd,this,"dirty"),d=a.subscribe(this.Sd,this);return{da:a,u:function(){c.u();d.u()}}}return a.subscribe(this.Ic,this)},Ic:function(){var b=this,c=b.throttleEvaluation;c&&0<=c?(clearTimeout(this[r].Jc),this[r].Jc=a.a.setTimeout(function(){b.ha(!0)},c)):b.Ja?b.Ja(!0):b.ha(!0)},ha:function(b){var c=this[r],d=c.Ta,e=!1;if(!c.sb&&
!c.ua){if(c.l&&!a.a.Ub(c.l)||d&&d()){if(!c.lc){this.u();return}}else c.lc=!1;c.sb=!0;try{e=this.zd(b)}finally{c.sb=!1}return e}},zd:function(b){var c=this[r],d=!1,e=c.yb?n:!c.V,d={qd:this,nb:c.I,Sb:c.V};a.s.zc({pd:d,od:da,o:this,Za:e});c.I={};c.V=0;var f=this.yd(c,d);c.V?d=this.tb(c.X,f):(this.u(),d=!0);d&&(c.K?this.Ib():this.notifySubscribers(c.X,"beforeChange"),c.X=f,this.notifySubscribers(c.X,"spectate"),!c.K&&b&&this.notifySubscribers(c.X),this.tc&&this.tc());e&&this.notifySubscribers(c.X,"awake");
return d},yd:function(b,c){try{var d=b.Wc;return b.ob?d.call(b.ob):d()}finally{a.s.end(),c.Sb&&!b.K&&a.a.P(c.nb,ca),b.va=b.la=!1}},v:function(a){var c=this[r];(c.la&&(a||!c.V)||c.K&&this.Ya())&&this.ha();return c.X},vb:function(b){a.T.fn.vb.call(this,b);this.pc=function(){this[r].K||(this[r].va?this.ha():this[r].la=!1);return this[r].X};this.Ja=function(a){this.rc(this[r].X);this[r].la=!0;a&&(this[r].va=!0);this.sc(this,!a)}},u:function(){var b=this[r];!b.K&&b.I&&a.a.P(b.I,function(a,b){b.u&&b.u()});
b.l&&b.Tb&&a.a.L.Ab(b.l,b.Tb);b.I=n;b.V=0;b.ua=!0;b.va=!1;b.la=!1;b.K=!1;b.l=n;b.Ta=n;b.Wc=n;this.Nc||(b.ob=n)}},fa={Ra:function(b){var c=this,d=c[r];if(!d.ua&&d.K&&"change"==b){d.K=!1;if(d.va||c.Ya())d.I=null,d.V=0,c.ha()&&c.Ib();else{var e=[];a.a.P(d.I,function(a,b){e[b.La]=a});a.a.A(e,function(a,b){var e=d.I[a],m=c.$c(e.da);m.La=b;m.Ma=e.Ma;d.I[a]=m});c.Ya()&&c.ha()&&c.Ib()}d.ua||c.notifySubscribers(d.X,"awake")}},ib:function(b){var c=this[r];c.ua||"change"!=b||this.Xa("change")||(a.a.P(c.I,function(a,
b){b.u&&(c.I[a]={da:b.da,La:b.La,Ma:b.Ma},b.u())}),c.K=!0,this.notifySubscribers(n,"asleep"))},pb:function(){var b=this[r];b.K&&(b.va||this.Ya())&&this.ha();return a.T.fn.pb.call(this)}},ga={Ra:function(a){"change"!=a&&"beforeChange"!=a||this.v()}};a.a.Da&&a.a.setPrototypeOf(B,a.T.fn);var R=a.ia.Na;B[R]=a.o;a.Oc=function(a){return"function"==typeof a&&a[R]===B[R]};a.Gd=function(b){return a.Oc(b)&&b[r]&&b[r].yb};a.b("computed",a.o);a.b("dependentObservable",a.o);a.b("isComputed",a.Oc);a.b("isPureComputed",
a.Gd);a.b("computed.fn",B);a.M(B,"peek",B.v);a.M(B,"dispose",B.u);a.M(B,"isActive",B.ka);a.M(B,"getDependenciesCount",B.ta);a.M(B,"getDependencies",B.Wa);a.zb=function(b,c){if("function"===typeof b)return a.o(b,c,{pure:!0});b=a.a.extend({},b);b.pure=!0;return a.o(b,c)};a.b("pureComputed",a.zb);(function(){function b(a,f,g){g=g||new d;a=f(a);if("object"!=typeof a||null===a||a===n||a instanceof RegExp||a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var h=
a instanceof Array?[]:{};g.save(a,h);c(a,function(c){var d=f(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "function":h[c]=d;break;case "object":case "undefined":var l=g.get(d);h[c]=l!==n?l:b(d,f,g)}});return h}function c(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function d(){this.keys=[];this.values=[]}a.ad=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");
return b(c,function(b){for(var c=0;a.J(b)&&10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.ad(b);return a.a.jc(b,c,d)};d.prototype={constructor:d,save:function(b,c){var d=a.a.B(this.keys,b);0<=d?this.values[d]=c:(this.keys.push(b),this.values.push(c))},get:function(b){b=a.a.B(this.keys,b);return 0<=b?this.values[b]:n}}})();a.b("toJS",a.ad);a.b("toJSON",a.toJSON);a.Yd=function(b,c,d){function e(c){var e=a.zb(b,d).extend({na:"always"}),h=e.subscribe(function(a){a&&(h.u(),c(a))});e.notifySubscribers(e.v());
return h}return"function"!==typeof Promise||c?e(c.bind(d)):new Promise(e)};a.b("when",a.Yd);(function(){a.w={N:function(b){switch(a.a.R(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.a.g.get(b,a.f.options.bc):7>=a.a.W?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.w.N(b.options[b.selectedIndex]):n;default:return b.value}},eb:function(b,c,d){switch(a.a.R(b)){case "option":"string"===typeof c?(a.a.g.set(b,
a.f.options.bc,n),"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__,b.value=c):(a.a.g.set(b,a.f.options.bc,c),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof c?c:"");break;case "select":if(""===c||null===c)c=n;for(var e=-1,f=0,g=b.options.length,h;f<g;++f)if(h=a.w.N(b.options[f]),h==c||""===h&&c===n){e=f;break}if(d||0<=e||c===n&&1<b.size)b.selectedIndex=e,6===a.a.W&&a.a.setTimeout(function(){b.selectedIndex=e},0);break;default:if(null===c||c===n)c="";b.value=
c}}}})();a.b("selectExtensions",a.w);a.b("selectExtensions.readValue",a.w.N);a.b("selectExtensions.writeValue",a.w.eb);a.m=function(){function b(b){b=a.a.Fb(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));b+="\n,";var c=[],d=b.match(e),p,q=[],h=0;if(1<d.length){for(var t=0,w;w=d[t];++t){var u=w.charCodeAt(0);if(44===u){if(0>=h){c.push(p&&q.length?{key:p,value:q.join("")}:{unknown:p||q.join("")});p=h=0;q=[];continue}}else if(58===u){if(!h&&!p&&1===q.length){p=q.pop();continue}}else if(47===u&&1<w.length&&
(47===w.charCodeAt(1)||42===w.charCodeAt(1)))continue;else 47===u&&t&&1<w.length?(u=d[t-1].match(f))&&!g[u[0]]&&(b=b.substr(b.indexOf(w)+1),d=b.match(e),t=-1,w="/"):40===u||123===u||91===u?++h:41===u||125===u||93===u?--h:p||q.length||34!==u&&39!==u||(w=w.slice(1,-1));q.push(w)}if(0<h)throw Error("Unbalanced parentheses, braces, or brackets");}return c}var c=["true","false","null","undefined"],d=/^(?:[$_a-z][$\w]*|(.+?)\??(\.\s*[$_a-z][$\w]*|\[[^\]]+\]))$/i,e=RegExp("\"(?:\\\\.|[^\"])*\"|'(?:\\\\.|[^'])*'|`(?:\\\\.|[^`])*`|/\\*(?:[^*]|\\*+[^*/])*\\*+/|//.*\n|/(?:\\\\.|[^/])+/w*|[^\\s:,/][^,\"'`{}()/:[\\]]*[^\\s,\"'`{}()/:[\\]]|[^\\s]",
"g"),f=/[\])"'A-Za-z0-9_$]+$/,g={"in":1,"return":1,"typeof":1},h={};return{Sa:[],ya:h,cc:b,xb:function(e,f){function l(b,e){var f;if(!t){var k=a.getBindingHandler(b);if(k&&k.preprocess&&!(e=k.preprocess(e,b,l)))return;if(k=h[b])f=e,0<=a.a.B(c,f)?f=!1:(k=f.match(d),f=null===k?!1:k[1]?"Object("+k[1]+")"+k[2]:f),k=f;k&&q.push("'"+("string"==typeof h[b]?h[b]:b)+"':function(_z){"+f+"=_z}")}g&&(e="function(){return "+e+" }");p.push("'"+b+"':"+e)}f=f||{};var p=[],q=[],g=f.valueAccessors,t=f.bindingParams,
w="string"===typeof e?b(e):e;a.a.A(w,function(a){l(a.key||a.unknown,a.value)});q.length&&l("_ko_property_writers","{"+q.join(",")+" }");return p.join(",")},Jd:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},fb:function(b,c,d,e,f){if(b&&a.J(b))!a.$a(b)||f&&b.v()===e||b(e);else if((b=c.get("_ko_property_writers"))&&b[d])b[d](e)}}}();a.b("expressionRewriting",a.m);a.b("expressionRewriting.bindingRewriteValidators",a.m.Sa);a.b("expressionRewriting.parseObjectLiteral",a.m.cc);
a.b("expressionRewriting.preProcessBindings",a.m.xb);a.b("expressionRewriting._twoWayBindings",a.m.ya);a.b("jsonExpressionRewriting",a.m);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.m.xb);(function(){function b(a){return 8==a.nodeType&&g.test(f?a.text:a.nodeValue)}function c(a){return 8==a.nodeType&&h.test(f?a.text:a.nodeValue)}function d(d,e){for(var f=d,h=1,g=[];f=f.nextSibling;){if(c(f)&&(a.a.g.set(f,k,!0),h--,0===h))return g;g.push(f);b(f)&&h++}if(!e)throw Error("Cannot find closing comment tag to match: "+
d.nodeValue);return null}function e(a,b){var c=d(a,b);return c?0<c.length?c[c.length-1].nextSibling:a.nextSibling:null}var f=y&&"\x3c!--test--\x3e"===y.createComment("test").text,g=f?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,h=f?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,m={ul:!0,ol:!0},k="__ko_matchedEndComment__";a.h={ea:{},childNodes:function(a){return b(a)?d(a):a.childNodes},Fa:function(c){if(b(c)){c=a.h.childNodes(c);for(var d=0,e=c.length;d<e;d++)a.removeNode(c[d])}else a.a.Vb(c)},
xa:function(c,d){if(b(c)){a.h.Fa(c);for(var e=c.nextSibling,f=0,k=d.length;f<k;f++)e.parentNode.insertBefore(d[f],e)}else a.a.xa(c,d)},Vc:function(a,c){var d;b(a)?(d=a.nextSibling,a=a.parentNode):d=a.firstChild;d?c!==d&&a.insertBefore(c,d):a.appendChild(c)},Yb:function(c,d,e){e?(e=e.nextSibling,b(c)&&(c=c.parentNode),e?d!==e&&c.insertBefore(d,e):c.appendChild(d)):a.h.Vc(c,d)},firstChild:function(a){if(b(a))return!a.nextSibling||c(a.nextSibling)?null:a.nextSibling;if(a.firstChild&&c(a.firstChild))throw Error("Found invalid end comment, as the first child of "+
a);return a.firstChild},nextSibling:function(d){b(d)&&(d=e(d));if(d.nextSibling&&c(d.nextSibling)){var f=d.nextSibling;if(c(f)&&!a.a.g.get(f,k))throw Error("Found end comment without a matching opening comment, as child of "+d);return null}return d.nextSibling},Dd:b,Xd:function(a){return(a=(f?a.text:a.nodeValue).match(g))?a[1]:null},Sc:function(d){if(m[a.a.R(d)]){var f=d.firstChild;if(f){do if(1===f.nodeType){var k;k=f.firstChild;var h=null;if(k){do if(h)h.push(k);else if(b(k)){var g=e(k,!0);g?k=
g:h=[k]}else c(k)&&(h=[k]);while(k=k.nextSibling)}if(k=h)for(h=f.nextSibling,g=0;g<k.length;g++)h?d.insertBefore(k[g],h):d.appendChild(k[g])}while(f=f.nextSibling)}}}}})();a.b("virtualElements",a.h);a.b("virtualElements.allowedBindings",a.h.ea);a.b("virtualElements.emptyNode",a.h.Fa);a.b("virtualElements.insertAfter",a.h.Yb);a.b("virtualElements.prepend",a.h.Vc);a.b("virtualElements.setDomNodeChildren",a.h.xa);(function(){a.ga=function(){this.nd={}};a.a.extend(a.ga.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=
b.getAttribute("data-bind")||a.j.getComponentNameForNode(b);case 8:return a.h.Dd(b);default:return!1}},getBindings:function(b,c){var d=this.getBindingsString(b,c),d=d?this.parseBindingsString(d,c,b):null;return a.j.vc(d,b,c,!1)},getBindingAccessors:function(b,c){var d=this.getBindingsString(b,c),d=d?this.parseBindingsString(d,c,b,{valueAccessors:!0}):null;return a.j.vc(d,b,c,!0)},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.h.Xd(b);default:return null}},
parseBindingsString:function(b,c,d,e){try{var f=this.nd,g=b+(e&&e.valueAccessors||""),h;if(!(h=f[g])){var m,k="with($context){with($data||{}){return{"+a.m.xb(b,e)+"}}}";m=new Function("$context","$element",k);h=f[g]=m}return h(c,d)}catch(l){throw l.message="Unable to parse bindings.\nBindings value: "+b+"\nMessage: "+l.message,l;}}});a.ga.instance=new a.ga})();a.b("bindingProvider",a.ga);(function(){function b(b){var c=(b=a.a.g.get(b,C))&&b.O;c&&(b.O=null,c.Tc())}function c(c,d,e){this.node=c;this.Ac=
d;this.lb=[];this.H=!1;d.O||a.a.L.Ba(c,b);e&&e.O&&(e.O.lb.push(c),this.Mb=e)}function d(a){return function(){return a}}function e(a){return a()}function f(b){return a.a.Ha(a.s.C(b),function(a,c){return function(){return b()[c]}})}function g(b,c,e){return"function"===typeof b?f(b.bind(null,c,e)):a.a.Ha(b,d)}function h(a,b){return f(this.getBindings.bind(this,a,b))}function m(b,c){var d=a.h.firstChild(c);if(d){var e,f=a.ga.instance,l=f.preprocessNode;if(l){for(;e=d;)d=a.h.nextSibling(e),l.call(f,e);
d=a.h.firstChild(c)}for(;e=d;)d=a.h.nextSibling(e),k(b,e)}a.i.na(c,a.i.H)}function k(b,c){var d=b,e=1===c.nodeType;e&&a.h.Sc(c);if(e||a.ga.instance.nodeHasBindings(c))d=p(c,null,b).bindingContextForDescendants;d&&!u[a.a.R(c)]&&m(d,c)}function l(b){var c=[],d={},e=[];a.a.P(b,function ea(f){if(!d[f]){var k=a.getBindingHandler(f);k&&(k.after&&(e.push(f),a.a.A(k.after,function(c){if(b[c]){if(-1!==a.a.B(e,c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+e.join(", "));
ea(c)}}),e.length--),c.push({key:f,Mc:k}));d[f]=!0}});return c}function p(b,c,d){var f=a.a.g.Wb(b,C,{}),k=f.hd;if(!c){if(k)throw Error("You cannot apply bindings multiple times to the same element.");f.hd=!0}k||(f.context=d);f.ac||(f.ac={});var g;if(c&&"function"!==typeof c)g=c;else{var p=a.ga.instance,q=p.getBindingAccessors||h,m=a.$(function(){if(g=c?c(d,b):q.call(p,b,d)){if(d[x])d[x]();if(d[w])d[w]()}return g},null,{l:b});g&&m.ka()||(m=null)}var u=d,t;if(g){var K=function(){return a.a.Ha(m?m():
g,e)},r=m?function(a){return function(){return e(m()[a])}}:function(a){return g[a]};K.get=function(a){return g[a]&&e(r(a))};K.has=function(a){return a in g};a.i.H in g&&a.i.subscribe(b,a.i.H,function(){var c=(0,g[a.i.H])();if(c){var d=a.h.childNodes(b);d.length&&c(d,a.Fc(d[0]))}});a.i.sa in g&&(u=a.i.Eb(b,d),a.i.subscribe(b,a.i.sa,function(){var c=(0,g[a.i.sa])();c&&a.h.firstChild(b)&&c(b)}));f=l(g);a.a.A(f,function(c){var d=c.Mc.init,e=c.Mc.update,f=c.key;if(8===b.nodeType&&!a.h.ea[f])throw Error("The binding '"+
f+"' cannot be used with virtual elements");try{"function"==typeof d&&a.s.C(function(){var a=d(b,r(f),K,u.$data,u);if(a&&a.controlsDescendantBindings){if(t!==n)throw Error("Multiple bindings ("+t+" and "+f+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");t=f}}),"function"==typeof e&&a.$(function(){e(b,r(f),K,u.$data,u)},null,{l:b})}catch(k){throw k.message='Unable to process binding "'+f+": "+g[f]+'"\nMessage: '+k.message,
k;}})}f=t===n;return{shouldBindDescendants:f,bindingContextForDescendants:f&&u}}function q(b,c){return b&&b instanceof a.fa?b:new a.fa(b,n,n,c)}var x=a.a.qa("_subscribable"),t=a.a.qa("_ancestorBindingInfo"),w=a.a.qa("_dataDependency");a.f={};var u={script:!0,textarea:!0,template:!0};a.getBindingHandler=function(b){return a.f[b]};var K={};a.fa=function(b,c,d,e,f){function k(){var b=p?h():h,f=a.a.c(b);c?(a.a.extend(l,c),t in c&&(l[t]=c[t])):(l.$parents=[],l.$root=f,l.ko=a);l[x]=q;g?f=l.$data:(l.$rawData=
b,l.$data=f);d&&(l[d]=f);e&&e(l,c,f);if(c&&c[x]&&!a.S.o().Xb(c[x]))c[x]();m&&(l[w]=m);return l.$data}var l=this,g=b===K,h=g?n:b,p="function"==typeof h&&!a.J(h),q,m=f&&f.dataDependency;f&&f.exportDependencies?k():(q=a.zb(k),q.v(),q.ka()?q.equalityComparer=null:l[x]=n)};a.fa.prototype.createChildContext=function(b,c,d,e){!e&&c&&"object"==typeof c&&(e=c,c=e.as,d=e.extend);if(c&&e&&e.noChildContext){var f="function"==typeof b&&!a.J(b);return new a.fa(K,this,null,function(a){d&&d(a);a[c]=f?b():b},e)}return new a.fa(b,
this,c,function(a,b){a.$parentContext=b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)},e)};a.fa.prototype.extend=function(b,c){return new a.fa(K,this,null,function(c){a.a.extend(c,"function"==typeof b?b(c):b)},c)};var C=a.a.g.Z();c.prototype.Tc=function(){this.Mb&&this.Mb.O&&this.Mb.O.sd(this.node)};c.prototype.sd=function(b){a.a.Qa(this.lb,b);!this.lb.length&&this.H&&this.Dc()};c.prototype.Dc=function(){this.H=!0;this.Ac.O&&!this.lb.length&&(this.Ac.O=
null,a.a.L.Ab(this.node,b),a.i.na(this.node,a.i.sa),this.Tc())};a.i={H:"childrenComplete",sa:"descendantsComplete",subscribe:function(b,c,d,e,f){var k=a.a.g.Wb(b,C,{});k.Ga||(k.Ga=new a.T);f&&f.notifyImmediately&&k.ac[c]&&a.s.C(d,e,[b]);return k.Ga.subscribe(d,e,c)},na:function(b,c){var d=a.a.g.get(b,C);if(d&&(d.ac[c]=!0,d.Ga&&d.Ga.notifySubscribers(b,c),c==a.i.H))if(d.O)d.O.Dc();else if(d.O===n&&d.Ga&&d.Ga.Xa(a.i.sa))throw Error("descendantsComplete event not supported for bindings on this node");
},Eb:function(b,d){var e=a.a.g.Wb(b,C,{});e.O||(e.O=new c(b,e,d[t]));return d[t]==e?d:d.extend(function(a){a[t]=e})}};a.Vd=function(b){return(b=a.a.g.get(b,C))&&b.context};a.jb=function(b,c,d){1===b.nodeType&&a.h.Sc(b);return p(b,c,q(d))};a.ld=function(b,c,d){d=q(d);return a.jb(b,g(c,d,b),d)};a.Pa=function(a,b){1!==b.nodeType&&8!==b.nodeType||m(q(a),b)};a.xc=function(a,b,c){!v&&A.jQuery&&(v=A.jQuery);if(2>arguments.length){if(b=y.body,!b)throw Error("ko.applyBindings: could not find document.body; has the document been loaded?");
}else if(!b||1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");k(q(a,c),b)};a.Ec=function(b){return!b||1!==b.nodeType&&8!==b.nodeType?n:a.Vd(b)};a.Fc=function(b){return(b=a.Ec(b))?b.$data:n};a.b("bindingHandlers",a.f);a.b("bindingEvent",a.i);a.b("bindingEvent.subscribe",a.i.subscribe);a.b("bindingEvent.startPossiblyAsyncContentBinding",a.i.Eb);a.b("applyBindings",a.xc);a.b("applyBindingsToDescendants",a.Pa);
a.b("applyBindingAccessorsToNode",a.jb);a.b("applyBindingsToNode",a.ld);a.b("contextFor",a.Ec);a.b("dataFor",a.Fc)})();(function(b){function c(c,e){var k=Object.prototype.hasOwnProperty.call(f,c)?f[c]:b,l;k?k.subscribe(e):(k=f[c]=new a.T,k.subscribe(e),d(c,function(b,d){var e=!(!d||!d.synchronous);g[c]={definition:b,Hd:e};delete f[c];l||e?k.notifySubscribers(b):a.oa.Bb(function(){k.notifySubscribers(b)})}),l=!0)}function d(a,b){e("getConfig",[a],function(c){c?e("loadComponent",[a,c],function(a){b(a,
c)}):b(null,null)})}function e(c,d,f,l){l||(l=a.j.loaders.slice(0));var g=l.shift();if(g){var q=g[c];if(q){var x=!1;if(q.apply(g,d.concat(function(a){x?f(null):null!==a?f(a):e(c,d,f,l)}))!==b&&(x=!0,!g.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else e(c,d,f,l)}else f(null)}var f={},g={};a.j={get:function(d,e){var f=Object.prototype.hasOwnProperty.call(g,d)?g[d]:b;f?f.Hd?a.s.C(function(){e(f.definition)}):
a.oa.Bb(function(){e(f.definition)}):c(d,e)},Cc:function(a){delete g[a]},qc:e};a.j.loaders=[];a.b("components",a.j);a.b("components.get",a.j.get);a.b("components.clearCachedDefinition",a.j.Cc)})();(function(){function b(b,c,d,e){function g(){0===--w&&e(h)}var h={},w=2,u=d.template;d=d.viewModel;u?f(c,u,function(c){a.j.qc("loadTemplate",[b,c],function(a){h.template=a;g()})}):g();d?f(c,d,function(c){a.j.qc("loadViewModel",[b,c],function(a){h[m]=a;g()})}):g()}function c(a,b,d){if("function"===typeof b)d(function(a){return new b(a)});
else if("function"===typeof b[m])d(b[m]);else if("instance"in b){var e=b.instance;d(function(){return e})}else"viewModel"in b?c(a,b.viewModel,d):a("Unknown viewModel value: "+b)}function d(b){switch(a.a.R(b)){case "script":return a.a.wa(b.text);case "textarea":return a.a.wa(b.value);case "template":if(e(b.content))return a.a.Ea(b.content.childNodes)}return a.a.Ea(b.childNodes)}function e(a){return A.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType}function f(a,b,c){"string"===typeof b.require?
V||A.require?(V||A.require)([b.require],function(a){a&&"object"===typeof a&&a.$d&&a["default"]&&(a=a["default"]);c(a)}):a("Uses require, but no AMD loader is present"):c(b)}function g(a){return function(b){throw Error("Component '"+a+"': "+b);}}var h={};a.j.register=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.j.ub(b))throw Error("Component "+b+" is already registered");h[b]=c};a.j.ub=function(a){return Object.prototype.hasOwnProperty.call(h,a)};a.j.unregister=function(b){delete h[b];
a.j.Cc(b)};a.j.Gc={getConfig:function(b,c){c(a.j.ub(b)?h[b]:null)},loadComponent:function(a,c,d){var e=g(a);f(e,c,function(c){b(a,e,c,d)})},loadTemplate:function(b,c,f){b=g(b);if("string"===typeof c)f(a.a.wa(c));else if(c instanceof Array)f(c);else if(e(c))f(a.a.ma(c.childNodes));else if(c.element)if(c=c.element,A.HTMLElement?c instanceof HTMLElement:c&&c.tagName&&1===c.nodeType)f(d(c));else if("string"===typeof c){var h=y.getElementById(c);h?f(d(h)):b("Cannot find element with ID "+c)}else b("Unknown element type: "+
c);else b("Unknown template value: "+c)},loadViewModel:function(a,b,d){c(g(a),b,d)}};var m="createViewModel";a.b("components.register",a.j.register);a.b("components.isRegistered",a.j.ub);a.b("components.unregister",a.j.unregister);a.b("components.defaultLoader",a.j.Gc);a.j.loaders.push(a.j.Gc);a.j.dd=h})();(function(){function b(b,e){var f=b.getAttribute("params");if(f){var f=c.parseBindingsString(f,e,b,{valueAccessors:!0,bindingParams:!0}),f=a.a.Ha(f,function(c){return a.o(c,null,{l:b})}),g=a.a.Ha(f,
function(c){var e=c.v();return c.ka()?a.o({read:function(){return a.a.c(c())},write:a.$a(e)&&function(a){c()(a)},l:b}):e});Object.prototype.hasOwnProperty.call(g,"$raw")||(g.$raw=f);return g}return{$raw:{}}}a.j.getComponentNameForNode=function(b){var c=a.a.R(b);if(a.j.ub(c)&&(-1!=c.indexOf("-")||"[object HTMLUnknownElement]"==""+b||8>=a.a.W&&b.tagName===c))return c};a.j.vc=function(c,e,f,g){if(1===e.nodeType){var h=a.j.getComponentNameForNode(e);if(h){c=c||{};if(c.component)throw Error('Cannot use the "component" binding on a custom element matching a component');
var m={name:h,params:b(e,f)};c.component=g?function(){return m}:m}}return c};var c=new a.ga;9>a.a.W&&(a.j.register=function(a){return function(b){return a.apply(this,arguments)}}(a.j.register),y.createDocumentFragment=function(b){return function(){var c=b(),f=a.j.dd,g;for(g in f);return c}}(y.createDocumentFragment))})();(function(){function b(b,c,d){c=c.template;if(!c)throw Error("Component '"+b+"' has no template");b=a.a.Ea(c);a.h.xa(d,b)}function c(a,b,c){var d=a.createViewModel;return d?d.call(a,
b,c):b}var d=0;a.f.component={init:function(e,f,g,h,m){function k(){var a=l&&l.dispose;"function"===typeof a&&a.call(l);q&&q.u();p=l=q=null}var l,p,q,x=a.a.ma(a.h.childNodes(e));a.h.Fa(e);a.a.L.Ba(e,k);a.o(function(){var g=a.a.c(f()),h,u;"string"===typeof g?h=g:(h=a.a.c(g.name),u=a.a.c(g.params));if(!h)throw Error("No component name specified");var n=a.i.Eb(e,m),C=p=++d;a.j.get(h,function(d){if(p===C){k();if(!d)throw Error("Unknown component '"+h+"'");b(h,d,e);var f=c(d,u,{element:e,templateNodes:x});
d=n.createChildContext(f,{extend:function(a){a.$component=f;a.$componentTemplateNodes=x}});f&&f.koDescendantsComplete&&(q=a.i.subscribe(e,a.i.sa,f.koDescendantsComplete,f));l=f;a.Pa(d,e)}})},null,{l:e});return{controlsDescendantBindings:!0}}};a.h.ea.component=!0})();var X={"class":"className","for":"htmlFor"};a.f.attr={update:function(b,c){var d=a.a.c(c())||{};a.a.P(d,function(c,d){d=a.a.c(d);var g=c.indexOf(":"),g="lookupNamespaceURI"in b&&0<g&&b.lookupNamespaceURI(c.substr(0,g)),h=!1===d||null===
d||d===n;h?g?b.removeAttributeNS(g,c):b.removeAttribute(c):d=d.toString();8>=a.a.W&&c in X?(c=X[c],h?b.removeAttribute(c):b[c]=d):h||(g?b.setAttributeNS(g,c,d):b.setAttribute(c,d));"name"===c&&a.a.Yc(b,h?"":d)})}};(function(){a.f.checked={after:["value","attr"],init:function(b,c,d){function e(){var e=b.checked,f=g();if(!a.S.Za()&&(e||!l&&!a.S.ta())){var p=a.s.C(c);if(q){var t=x?p.v():p,r=w;w=f;r!==f?e&&(a.a.Oa(t,f,!0,h,m),a.a.Oa(t,r,!1,h,m)):a.a.Oa(t,f,e,h,m);x&&a.$a(p)&&p(t)}else k&&(f===n?f=e:e||
(f=n)),a.m.fb(p,d,"checked",f,!0)}}function f(){var d=a.a.c(c()),e=g();q?(b.checked=0<=a.a.B(d,e,h,m),w=e):b.checked=k&&e===n?!!d:m?m(g())===m(d):g()===d}var g=a.zb(function(){if(d.has("checkedValue"))return a.a.c(d.get("checkedValue"));if(t)return d.has("value")?a.a.c(d.get("value")):b.value}),h=d.has("checkedArrayContainsObservables")&&d.get("checkedArrayContainsObservables"),m=d.get("checkedValueComparer"),k="checkbox"==b.type,l="radio"==b.type;if(k||l){var p=c(),q=k&&a.a.c(p)instanceof Array,
x=!(q&&p.push&&p.splice),t=l||q,w=q?g():n;l&&!b.name&&a.f.uniqueName.init(b,function(){return!0});a.o(e,null,{l:b});a.a.D(b,"click",e);a.o(f,null,{l:b});p=n}}};a.m.ya.checked=!0;a.f.checkedValue={update:function(b,c){b.value=a.a.c(c())}}})();a.f["class"]={update:function(b,c){var d=a.a.Fb(a.a.c(c()));a.a.Gb(b,b.__ko__cssValue,!1);b.__ko__cssValue=d;a.a.Gb(b,d,!0)}};a.f.css={update:function(b,c){var d=a.a.c(c());null!==d&&"object"==typeof d?a.a.P(d,function(c,d){d=a.a.c(d);a.a.Gb(b,c,d)}):a.f["class"].update(b,
c)}};a.f.enable={update:function(b,c){var d=a.a.c(c());d&&b.disabled?b.removeAttribute("disabled"):d||b.disabled||(b.disabled=!0)}};a.f.disable={update:function(b,c){a.f.enable.update(b,function(){return!a.a.c(c())})}};a.f.event={init:function(b,c,d,e,f){var g=c()||{};a.a.P(g,function(g){"string"==typeof g&&a.a.D(b,g,function(b){var k,l=c()[g];if(l){try{var p=a.a.ma(arguments);e=f.$data;p.unshift(e);k=l.apply(e,p)}finally{!0!==k&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===d.get(g+
"Bubble")&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.f.foreach={Rc:function(b){return function(){var c=b(),d=a.a.wb(c);if(!d||"number"==typeof d.length)return{foreach:c,templateEngine:a.ba.Na};a.a.c(c);return{foreach:d.data,separatorTemplate:d.separatorTemplate,as:d.as,noChildContext:d.noChildContext,includeDestroyed:d.includeDestroyed,afterAdd:d.afterAdd,beforeRemove:d.beforeRemove,afterRender:d.afterRender,beforeMove:d.beforeMove,afterMove:d.afterMove,templateEngine:a.ba.Na}}},
init:function(b,c){return a.f.template.init(b,a.f.foreach.Rc(c))},update:function(b,c,d,e,f){return a.f.template.update(b,a.f.foreach.Rc(c),d,e,f)}};a.m.Sa.foreach=!1;a.h.ea.foreach=!0;a.f.hasfocus={init:function(b,c,d){function e(e){b.__ko_hasfocusUpdating=!0;var f=b.ownerDocument;if("activeElement"in f){var k;try{k=f.activeElement}catch(g){k=f.body}e=k===b}f=c();a.m.fb(f,d,"hasfocus",e,!0);b.__ko_hasfocusLastValue=e;b.__ko_hasfocusUpdating=!1}var f=e.bind(null,!0),g=e.bind(null,!1);a.a.D(b,"focus",
f);a.a.D(b,"focusin",f);a.a.D(b,"blur",g);a.a.D(b,"focusout",g);b.__ko_hasfocusLastValue=!1},update:function(b,c){var d=!!a.a.c(c());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===d||(d?b.focus():b.blur(),!d&&b.__ko_hasfocusLastValue&&b.ownerDocument.body.focus(),a.s.C(a.a.Hb,null,[b,d?"focusin":"focusout"]))}};a.m.ya.hasfocus=!0;a.f.hasFocus=a.f.hasfocus;a.m.ya.hasFocus="hasfocus";a.f.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.hc(b,c())}};(function(){function b(b,
d,e){a.f[b]={init:function(b,c,h,m,k){var l,p,q={},x,t,w;if(d){m=h.get("as");var u=h.get("noChildContext");w=!(m&&u);q={as:m,noChildContext:u,exportDependencies:w}}t=(x="render"==h.get("completeOn"))||h.has(a.i.sa);a.o(function(){var h=a.a.c(c()),m=d?null!=h:!e!==!h,u=!p,n;if(w||m!==l){t&&(k=a.i.Eb(b,k));if(m){if(!d||w)q.dataDependency=a.S.o();n=d?k.createChildContext("function"==typeof h?h:c,q):a.S.ta()?k.extend(null,q):k}u&&a.S.ta()&&(p=a.a.Ea(a.h.childNodes(b),!0));m?(u||a.h.xa(b,a.a.Ea(p)),a.Pa(n,
b)):(a.h.Fa(b),x||a.i.na(b,a.i.H));l=m}},null,{l:b});return{controlsDescendantBindings:!0}}};a.m.Sa[b]=!1;a.h.ea[b]=!0}b("if");b("ifnot",!1,!0);b("with",!0)})();a.f.let={init:function(b,c,d,e,f){c=f.extend(c);a.Pa(c,b);return{controlsDescendantBindings:!0}}};a.h.ea.let=!0;var S={};a.f.options={init:function(b){if("select"!==a.a.R(b))throw Error("options binding applies only to SELECT elements");for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,c,d){function e(){return a.a.kb(b.options,
function(a){return a.selected})}function f(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?a[b]:c}function g(c,d){if(t&&l)a.i.na(b,a.i.H);else if(x.length){var e=0<=a.a.B(x,a.w.N(d[0]),!0);a.a.Zc(d[0],e);t&&!e&&a.s.C(a.a.Hb,null,[b,"change"])}}var h=b.multiple,m=0!=b.length&&h?b.scrollTop:null,k=a.a.c(c()),l=d.get("valueAllowUnset")&&d.has("value"),p=d.get("optionsIncludeDestroyed");c={};var q,x=[];l||(h?x=a.a.Ob(e(),a.w.N):0<=b.selectedIndex&&x.push(a.w.N(b.options[b.selectedIndex])));
k&&("undefined"==typeof k.length&&(k=[k]),q=a.a.kb(k,function(b){return p||b===n||null===b||!a.a.c(b._destroy)}),d.has("optionsCaption")&&(k=a.a.c(d.get("optionsCaption")),null!==k&&k!==n&&q.unshift(S)));var t=!1;c.beforeRemove=function(a){b.removeChild(a)};k=g;d.has("optionsAfterRender")&&"function"==typeof d.get("optionsAfterRender")&&(k=function(b,c){g(0,c);a.s.C(d.get("optionsAfterRender"),null,[c[0],b!==S?b:n])});a.a.gc(b,q,function(c,e,k){k.length&&(x=!l&&k[0].selected?[a.w.N(k[0])]:[],t=!0);
e=b.ownerDocument.createElement("option");c===S?(a.a.Db(e,d.get("optionsCaption")),a.w.eb(e,n)):(k=f(c,d.get("optionsValue"),c),a.w.eb(e,a.a.c(k)),k=f(c,d.get("optionsText"),k),a.a.Db(e,k),d.has("optionsTitle")&&(c=f(c,d.get("optionsTitle")),e.setAttribute("title",c)));return[e]},c,k);if(!l){var w;h?w=x.length&&e().length<x.length:w=x.length&&0<=b.selectedIndex?a.w.N(b.options[b.selectedIndex])!==x[0]:x.length||0<=b.selectedIndex;w&&a.s.C(a.a.Hb,null,[b,"change"])}(l||a.S.Za())&&a.i.na(b,a.i.H);a.a.wd(b);
m&&20<Math.abs(m-b.scrollTop)&&(b.scrollTop=m)}};a.f.options.bc=a.a.g.Z();a.f.selectedOptions={init:function(b,c,d){function e(){var e=c(),f=[];a.a.A(b.getElementsByTagName("option"),function(b){b.selected&&f.push(a.a.Zd(a.w.N(b)))});a.m.fb(e,d,"selectedOptions",f)}function f(){var d=a.a.c(c()),e=b.scrollTop;d&&"number"==typeof d.length&&(a.a.A(d,a.a.c),a.a.A(b.getElementsByTagName("option"),function(b){var c=0<=a.a.B(d,a.w.N(b),!0);b.selected!=c&&a.a.Zc(b,c)}));b.scrollTop=e}if("select"!=a.a.R(b))throw Error("selectedOptions binding applies only to SELECT elements");
var g;a.i.subscribe(b,a.i.H,function(){g?e():(a.a.D(b,"change",e),g=a.o(f,null,{l:b}))},null,{notifyImmediately:!0})},update:function(){}};a.m.ya.selectedOptions=!0;a.f.style={update:function(b,c){var d=a.a.c(c()||{});a.a.P(d,function(c,d){d=a.a.c(d);if(null===d||d===n||!1===d)d="";if(v)v(b).css(c,d);else if(/^--/.test(c))b.style.setProperty(c,d);else{c=c.replace(/-(\w)/g,function(a,b){return b.toUpperCase()});var g=b.style[c];b.style[c]=d;d===g||b.style[c]!=g||isNaN(d)||(b.style[c]=d+"px")}})}};
a.f.submit={init:function(b,c,d,e,f){if("function"!=typeof c())throw Error("The value for a submit binding must be a function");a.a.D(b,"submit",function(a){var d,e=c();try{d=e.call(f.$data,b)}finally{!0!==d&&(a.preventDefault?a.preventDefault():a.returnValue=!1)}})}};a.f.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.Db(b,c())}};a.h.ea.text=!0;(function(){if(A&&A.navigator){var b=function(a){if(a)return parseFloat(a[1])},c=A.navigator.userAgent,d,e,f,g,h;(d=
A.opera&&A.opera.version&&parseInt(A.opera.version()))||(h=b(c.match(/Edge\/([^ ]+)$/)))||b(c.match(/Chrome\/([^ ]+)/))||(e=b(c.match(/Version\/([^ ]+) Safari/)))||(f=b(c.match(/Firefox\/([^ ]+)/)))||(g=a.a.W||b(c.match(/MSIE ([^ ]+)/)))||(g=b(c.match(/rv:([^ )]+)/)))}if(8<=g&&10>g)var m=a.a.g.Z(),k=a.a.g.Z(),l=function(b){var c=this.activeElement;(c=c&&a.a.g.get(c,k))&&c(b)},p=function(b,c){var d=b.ownerDocument;a.a.g.get(d,m)||(a.a.g.set(d,m,!0),a.a.D(d,"selectionchange",l));a.a.g.set(b,k,c)};a.f.textInput=
{init:function(b,c,k){function l(c,d){a.a.D(b,c,d)}function m(){var d=a.a.c(c());if(null===d||d===n)d="";A!==n&&d===A?a.a.setTimeout(m,4):b.value!==d&&(z=!0,b.value=d,z=!1,v=b.value)}function r(){y||(A=b.value,y=a.a.setTimeout(C,4))}function C(){clearTimeout(y);A=y=n;var d=b.value;v!==d&&(v=d,a.m.fb(c(),k,"textInput",d))}var v=b.value,y,A,Q=9==a.a.W?r:C,z=!1;g&&l("keypress",C);11>g&&l("propertychange",function(a){z||"value"!==a.propertyName||Q(a)});8==g&&(l("keyup",C),l("keydown",C));p&&(p(b,Q),l("dragend",
r));(!g||9<=g)&&l("input",Q);5>e&&"textarea"===a.a.R(b)?(l("keydown",r),l("paste",r),l("cut",r)):11>d?l("keydown",r):4>f?(l("DOMAutoComplete",C),l("dragdrop",C),l("drop",C)):h&&"number"===b.type&&l("keydown",r);l("change",C);l("blur",C);a.o(m,null,{l:b})}};a.m.ya.textInput=!0;a.f.textinput={preprocess:function(a,b,c){c("textInput",a)}}})();a.f.uniqueName={init:function(b,c){if(c()){var d="ko_unique_"+ ++a.f.uniqueName.rd;a.a.Yc(b,d)}}};a.f.uniqueName.rd=0;a.f.using={init:function(b,c,d,e,f){var g;
d.has("as")&&(g={as:d.get("as"),noChildContext:d.get("noChildContext")});c=f.createChildContext(c,g);a.Pa(c,b);return{controlsDescendantBindings:!0}}};a.h.ea.using=!0;a.f.value={init:function(b,c,d){var e=a.a.R(b),f="input"==e;if(!f||"checkbox"!=b.type&&"radio"!=b.type){var g=[],h=d.get("valueUpdate"),m=!1,k=null;h&&("string"==typeof h?g=[h]:g=a.a.yc(h),a.a.Qa(g,"change"));var l=function(){a.ra.fc(function(){k=null;m=!1;var e=c(),f=a.w.N(b);a.m.fb(e,d,"value",f)})};!a.a.W||!f||"text"!=b.type||"off"==
b.autocomplete||b.form&&"off"==b.form.autocomplete||-1!=a.a.B(g,"propertychange")||(a.a.D(b,"propertychange",function(){m=!0}),a.a.D(b,"focus",function(){m=!1}),a.a.D(b,"blur",function(){m&&l()}));a.a.A(g,function(c){var d=l;a.a.Wd(c,"after")&&(d=function(){k=a.w.N(b);a.a.setTimeout(l,0)},c=c.substring(5));a.a.D(b,c,d)});var p;p=f&&"file"==b.type?function(){var d=a.a.c(c());null===d||d===n||""===d?b.value="":a.s.C(l)}:function(){var f=a.a.c(c()),g=a.w.N(b);if(null!==k&&f===k)a.a.setTimeout(p,0);else if(f!==
g||g===n)if("select"===e){var h=d.get("valueAllowUnset");a.ra.fc(function(){a.w.eb(b,f,h);h||f===a.w.N(b)||a.s.C(l)})}else a.w.eb(b,f)};if("select"===e){var q;a.a.D(b,"change",function(){q&&l()});a.i.subscribe(b,a.i.H,function(){q?d.get("valueAllowUnset")?p():l():q=a.o(p,null,{l:b})},null,{notifyImmediately:!0})}else a.a.D(b,"change",l),a.o(p,null,{l:b})}else a.jb(b,{checkedValue:c})},update:function(){}};a.m.ya.value=!0;a.f.visible={update:function(b,c){var d=a.a.c(c()),e="none"!=b.style.display;
d&&!e?b.style.display="":!d&&e&&(b.style.display="none")}};a.f.hidden={update:function(b,c){a.f.visible.update(b,function(){return!a.a.c(c())})}};(function(b){a.f[b]={init:function(c,d,e,f,g){return a.f.event.init.call(this,c,function(){var a={};a[b]=d();return a},e,f,g)}}})("click");a.ca=function(){};a.ca.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");};a.ca.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");
};a.ca.prototype.makeTemplateSource=function(b,c){if("string"==typeof b){c=c||y;var d=c.getElementById(b);if(!d)throw Error("Cannot find template with ID "+b);return new a.F.G(d)}if(1==b.nodeType||8==b.nodeType)return new a.F.ja(b);throw Error("Unknown template type: "+b);};a.ca.prototype.renderTemplate=function(a,c,d,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,c,d,e)};a.ca.prototype.isTemplateRewritten=function(a,c){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,
c).data("isRewritten")};a.ca.prototype.rewriteTemplate=function(a,c,d){a=this.makeTemplateSource(a,d);c=c(a.text());a.text(c);a.data("isRewritten",!0)};a.b("templateEngine",a.ca);a.mc=function(){function b(b,c,d,h){b=a.m.cc(b);for(var m=a.m.Sa,k=0;k<b.length;k++){var l=b[k].key;if(Object.prototype.hasOwnProperty.call(m,l)){var p=m[l];if("function"===typeof p){if(l=p(b[k].value))throw Error(l);}else if(!p)throw Error("This template engine does not support the '"+l+"' binding within its templates");
}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.m.xb(b,{valueAccessors:!0})+" } })()},'"+d.toLowerCase()+"')";return h.createJavaScriptEvaluatorBlock(d)+c}var c=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'|[^>]*))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,d=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{xd:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.mc.Md(b,c)},d)},Md:function(a,f){return a.replace(c,
function(a,c,d,e,l){return b(l,c,d,f)}).replace(d,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",f)})},md:function(b,c){return a.aa.Zb(function(d,h){var m=d.nextSibling;m&&m.nodeName.toLowerCase()===c&&a.jb(m,b,h)})}}}();a.b("__tr_ambtns",a.mc.md);(function(){a.F={};a.F.G=function(b){if(this.G=b){var c=a.a.R(b);this.bb="script"===c?1:"textarea"===c?2:"template"==c&&b.content&&11===b.content.nodeType?3:4}};a.F.G.prototype.text=function(){var b=1===this.bb?"text":2===this.bb?"value":"innerHTML";
if(0==arguments.length)return this.G[b];var c=arguments[0];"innerHTML"===b?a.a.hc(this.G,c):this.G[b]=c};var b=a.a.g.Z()+"_";a.F.G.prototype.data=function(c){if(1===arguments.length)return a.a.g.get(this.G,b+c);a.a.g.set(this.G,b+c,arguments[1])};var c=a.a.g.Z();a.F.G.prototype.nodes=function(){var b=this.G;if(0==arguments.length){var e=a.a.g.get(b,c)||{},f=e.mb||(3===this.bb?b.content:4===this.bb?b:n);if(!f||e.jd){var g=this.text();g&&g!==e.cb&&(f=a.a.Nd(g,b.ownerDocument),a.a.g.set(b,c,{mb:f,cb:g,
jd:!0}))}return f}e=arguments[0];this.bb!==n&&this.text("");a.a.g.set(b,c,{mb:e})};a.F.ja=function(a){this.G=a};a.F.ja.prototype=new a.F.G;a.F.ja.prototype.constructor=a.F.ja;a.F.ja.prototype.text=function(){if(0==arguments.length){var b=a.a.g.get(this.G,c)||{};b.cb===n&&b.mb&&(b.cb=b.mb.innerHTML);return b.cb}a.a.g.set(this.G,c,{cb:arguments[0]})};a.b("templateSources",a.F);a.b("templateSources.domElement",a.F.G);a.b("templateSources.anonymousTemplate",a.F.ja)})();(function(){function b(b,c,d){var e;
for(c=a.h.nextSibling(c);b&&(e=b)!==c;)b=a.h.nextSibling(e),d(e,b)}function c(c,d){if(c.length){var e=c[0],f=c[c.length-1],g=e.parentNode,h=a.ga.instance,m=h.preprocessNode;if(m){b(e,f,function(a,b){var c=a.previousSibling,d=m.call(h,a);d&&(a===e&&(e=d[0]||b),a===f&&(f=d[d.length-1]||c))});c.length=0;if(!e)return;e===f?c.push(e):(c.push(e,f),a.a.Va(c,g))}b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.xc(d,b)});b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.aa.cd(b,[d])});a.a.Va(c,g)}}function d(a){return a.nodeType?
a:0<a.length?a[0]:null}function e(b,e,f,h,m){m=m||{};var n=(b&&d(b)||f||{}).ownerDocument,w=m.templateEngine||g;a.mc.xd(f,w,n);f=w.renderTemplate(f,h,m,n);if("number"!=typeof f.length||0<f.length&&"number"!=typeof f[0].nodeType)throw Error("Template engine must return an array of DOM nodes");n=!1;switch(e){case "replaceChildren":a.h.xa(b,f);n=!0;break;case "replaceNode":a.a.Xc(b,f);n=!0;break;case "ignoreTargetNode":break;default:throw Error("Unknown renderMode: "+e);}n&&(c(f,h),m.afterRender&&a.s.C(m.afterRender,
null,[f,h[m.as||"$data"]]),"replaceChildren"==e&&a.i.na(b,a.i.H));return f}function f(b,c,d){return a.J(b)?b():"function"===typeof b?b(c,d):b}var g;a.ic=function(b){if(b!=n&&!(b instanceof a.ca))throw Error("templateEngine must inherit from ko.templateEngine");g=b};a.ec=function(b,c,h,m,x){h=h||{};if((h.templateEngine||g)==n)throw Error("Set a template engine before calling renderTemplate");x=x||"replaceChildren";if(m){var t=d(m);return a.$(function(){var g=c&&c instanceof a.fa?c:new a.fa(c,null,
null,null,{exportDependencies:!0}),n=f(b,g.$data,g),g=e(m,x,n,g,h);"replaceNode"==x&&(m=g,t=d(m))},null,{Ta:function(){return!t||!a.a.Ub(t)},l:t&&"replaceNode"==x?t.parentNode:t})}return a.aa.Zb(function(d){a.ec(b,c,h,d,"replaceNode")})};a.Rd=function(b,d,g,h,m){function t(b,c){a.s.C(a.a.gc,null,[h,b,u,g,w,c]);a.i.na(h,a.i.H)}function w(a,b){var d=b;v!==n&&(c(b.slice(0,v),m),d=b.slice(v));c(d,r);g.afterRender&&g.afterRender(b,a);r=null}function u(c,d){var l=g.hierarchyRole;if(l){var t=[d],u=0,w="$"+
(y||"item"),A={};"Child"===l&&(t=m.$indexPath.concat(t),u=m.$hierarchyLevel+1);A.$index=d;A.$indexPath=t;A.$hierarchyLevel=u;A[w]=c;r=m.extend(A)}else r=m.createChildContext(c,{as:y,noChildContext:g.noChildContext,extend:function(a){a.$index=d;y&&(a[y+"Index"]=d)}});l=[];t=g.separatorTemplate;v=n;t&&0<a.a.wb(d)&&(l=l.concat(e(h,"ignoreTargetNode",t,m,g)),v=l.length);t=f(b,c,r);return l=l.concat(e(h,"ignoreTargetNode",t,r,g))}var r,v,y=g.as,A=!1===g.includeDestroyed||a.options.foreachHidesDestroyed&&
!g.includeDestroyed;if(A||g.beforeRemove||!a.Pc(d))return a.$(function(){var b=a.a.c(d)||[];"undefined"==typeof b.length&&(b=[b]);A&&(b=a.a.kb(b,function(b){return b===n||null===b||!a.a.c(b._destroy)}));t(b)},null,{l:h});t(d.v());var B=d.subscribe(function(a){t(d(),a)},null,"arrayChange");B.l(h);return B};var h=a.a.g.Z(),m=a.a.g.Z();a.f.template={init:function(b,c){var d=a.a.c(c());if("string"==typeof d||"name"in d)a.h.Fa(b);else if("nodes"in d){d=d.nodes||[];if(a.J(d))throw Error('The "nodes" option must be a plain, non-observable array.');
var e=d[0]&&d[0].parentNode;e&&a.a.g.get(e,m)||(e=a.a.$b(d),a.a.g.set(e,m,!0));(new a.F.ja(b)).nodes(e)}else if(d=a.h.childNodes(b),0<d.length)e=a.a.$b(d),(new a.F.ja(b)).nodes(e);else throw Error("Anonymous template defined, but no template content was provided");return{controlsDescendantBindings:!0}},update:function(b,c,d,e,f){var g=c();c=a.a.c(g);d=!0;e=null;"string"==typeof c?c={}:(g="name"in c?c.name:b,"if"in c&&(d=a.a.c(c["if"])),d&&"ifnot"in c&&(d=!a.a.c(c.ifnot)),d&&!g&&(d=!1));var m=a.a.g.get(b,
h);m&&"function"==typeof m.u&&m.u();"foreach"in c?e=a.Rd(g,d&&c.foreach||[],c,b,f):d?(d=f,"data"in c&&(d=f.createChildContext(c.data,{as:c.as,noChildContext:c.noChildContext,exportDependencies:!0})),e=a.ec(g,d,c,b)):a.h.Fa(b);a.a.g.set(b,h,!e||e.ka&&!e.ka()?n:e)}};a.m.Sa.template=function(b){b=a.m.cc(b);return 1==b.length&&b[0].unknown||a.m.Jd(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};a.h.ea.template=!0})();a.b("setTemplateEngine",a.ic);
a.b("renderTemplate",a.ec);a.a.Ad=function(a,c,d){if(a.length&&c.length){var e,f,g,h,m;for(e=f=0;(!d||e<d)&&(h=a[f]);++f){for(g=0;m=c[g];++g)if(h.value===m.value){h.moved=m.index;m.moved=h.index;c.splice(g,1);e=g=0;break}e+=g}}};a.a.Rb=function(){function b(b,d,e,f,g){var h=Math.min,m=Math.max,k=[],l,p=b.length,q,n=d.length,t=n-p||1,r=p+n+1,u,v,y;for(l=0;l<=p;l++)for(v=u,k.push(u=[]),y=h(n,l+t),q=m(0,l-1);q<=y;q++)u[q]=q?l?b[l-1]===d[q-1]?v[q-1]:h(v[q]||r,u[q-1]||r)+1:q+1:l+1;h=[];m=[];t=[];l=p;for(q=
n;l||q;)n=k[l][q]-1,q&&n===k[l][q-1]?m.push(h[h.length]={status:e,value:d[--q],index:q}):l&&n===k[l-1][q]?t.push(h[h.length]={status:f,value:b[--l],index:l}):(--q,--l,g.sparse||h.push({status:"retained",value:d[q]}));a.a.Ad(t,m,!g.dontLimitMoves&&10*p);return h.reverse()}return function(a,d,e){e="boolean"===typeof e?{dontLimitMoves:e}:e||{};a=a||[];d=d||[];return a.length<d.length?b(a,d,"added","deleted",e):b(d,a,"deleted","added",e)}}();a.b("utils.compareArrays",a.a.Rb);(function(){function b(b,
c,d,h,m){var k=[],l=a.$(function(){var l=c(d,m,a.a.Va(k,b))||[];0<k.length&&(a.a.Xc(k,l),h&&a.s.C(h,null,[d,l,m]));k.length=0;a.a.Pb(k,l)},null,{l:b,Ta:function(){return!a.a.kd(k)}});return{Y:k,$:l.ka()?l:n}}var c=a.a.g.Z(),d=a.a.g.Z();a.a.gc=function(e,f,g,h,m,k){function l(b){z={Ca:b,qb:a.ia(v++)};w.push(z);t||F.push(z)}function p(b){z=r[b];v!==z.qb.v()&&D.push(z);z.qb(v++);a.a.Va(z.Y,e);w.push(z)}function q(b,c){if(b)for(var d=0,e=c.length;d<e;d++)a.a.A(c[d].Y,function(a){b(a,d,c[d].Ca)})}f=f||
[];"undefined"==typeof f.length&&(f=[f]);h=h||{};var r=a.a.g.get(e,c),t=!r,w=[],u=0,v=0,y=[],A=[],B=[],D=[],F=[],z,H=0;if(t)a.a.A(f,l);else{if(!k||r&&r._countWaitingForRemove){var E=a.a.Ob(r,function(a){return a.Ca});k=a.a.Rb(E,f,{dontLimitMoves:h.dontLimitMoves,sparse:!0})}for(var E=0,G,I,J;G=k[E];E++)switch(I=G.moved,J=G.index,G.status){case "deleted":for(;u<J;)p(u++);I===n&&(z=r[u],z.$&&(z.$.u(),z.$=n),a.a.Va(z.Y,e).length&&(h.beforeRemove&&(w.push(z),H++,z.Ca===d?z=null:B.push(z)),z&&y.push.apply(y,
z.Y)));u++;break;case "added":for(;v<J;)p(u++);I!==n?(A.push(w.length),p(I)):l(G.value)}for(;v<f.length;)p(u++);w._countWaitingForRemove=H}a.a.g.set(e,c,w);q(h.beforeMove,D);a.a.A(y,h.beforeRemove?a.pa:a.removeNode);var L,O,M;try{M=e.ownerDocument.activeElement}catch(N){}if(A.length)for(;(E=A.shift())!=n;){z=w[E];for(L=n;E;)if((O=w[--E].Y)&&O.length){L=O[O.length-1];break}for(f=0;u=z.Y[f];L=u,f++)a.h.Yb(e,u,L)}for(E=0;z=w[E];E++){z.Y||a.a.extend(z,b(e,g,z.Ca,m,z.qb));for(f=0;u=z.Y[f];L=u,f++)a.h.Yb(e,
u,L);!z.Fd&&m&&(m(z.Ca,z.Y,z.qb),z.Fd=!0,L=z.Y[z.Y.length-1])}M&&e.ownerDocument.activeElement!=M&&"function"===typeof M.focus&&M.focus();q(h.beforeRemove,B);for(E=0;E<B.length;++E)B[E].Ca=d;q(h.afterMove,D);q(h.afterAdd,F)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.gc);a.ba=function(){this.allowTemplateRewriting=!1};a.ba.prototype=new a.ca;a.ba.prototype.constructor=a.ba;a.ba.prototype.renderTemplateSource=function(b,c,d,e){if(c=(9>a.a.W?0:b.nodes)?b.nodes():null)return a.a.ma(c.cloneNode(!0).childNodes);
b=b.text();return a.a.wa(b,e)};a.ba.Na=new a.ba;a.ic(a.ba.Na);a.b("nativeTemplateEngine",a.ba);(function(){a.ab=function(){var a=this.Id=function(){if(!v||!v.tmpl)return 0;try{if(0<=v.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,f,g){g=g||y;f=f||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");var h=b.data("precompiled");h||(h=b.text()||"",h=v.template(null,"{{ko_with $item.koBindingContext}}"+
h+"{{/ko_with}}"),b.data("precompiled",h));b=[e.$data];e=v.extend({koBindingContext:e},f.templateOptions);e=v.tmpl(h,b,e);e.appendTo(g.createElement("div"));v.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){y.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(v.tmpl.tag.ko_code={open:"__.push($1 || '');"},v.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.ab.prototype=
new a.ca;a.ab.prototype.constructor=a.ab;var b=new a.ab;0<b.Id&&a.ic(b);a.b("jqueryTmplTemplateEngine",a.ab)})()})})();})();
