//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redwood.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Parser_RwHtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Parser_RwHtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redwood.Framework.Resources.Parser.RwHtml", typeof(Parser_RwHtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding inside attribute must end with double right curly brace! E.g. &lt;div class=&quot;row{{binding: RowIndex % 2}}&quot;&gt;.
        /// </summary>
        internal static string Attribute_BindingMustEndWithDoubleRightCurlyBraces {
            get {
                return ResourceManager.GetString("Attribute_BindingMustEndWithDoubleRightCurlyBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute value must not contain tag close brace!.
        /// </summary>
        internal static string Attribute_ValueMustNotContainTagCloseBrace {
            get {
                return ResourceManager.GetString("Attribute_ValueMustNotContainTagCloseBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon must follow the binding identifier! E.g. {binding: FirstName}.
        /// </summary>
        internal static string Binding_ColonAfterIdentifier {
            get {
                return ResourceManager.GetString("Binding_ColonAfterIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding that started with {{ must be closed with }} sequence!.
        /// </summary>
        internal static string Binding_DoubleCloseBraceRequired {
            get {
                return ResourceManager.GetString("Binding_DoubleCloseBraceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding must start with identifier! E.g. {binding: FirstName}.
        /// </summary>
        internal static string Binding_MustStartWithIdentifier {
            get {
                return ResourceManager.GetString("Binding_MustStartWithIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; is not supported in bindings!.
        /// </summary>
        internal static string Binding_UnsupportedExpression {
            get {
                return ResourceManager.GetString("Binding_UnsupportedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; is not supported in bindings in the DataContext property!.
        /// </summary>
        internal static string Binding_UnsupportedExpressionInDataContext {
            get {
                return ResourceManager.GetString("Binding_UnsupportedExpressionInDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator &apos;{0}&apos; is not supported in the binding!.
        /// </summary>
        internal static string Binding_UnsupportedOperator {
            get {
                return ResourceManager.GetString("Binding_UnsupportedOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control cannot be added to the collection because it already has a different parent! Remove it from the original collection first..
        /// </summary>
        internal static string ControlCollection_ControlAlreadyHasParent {
            get {
                return ResourceManager.GetString("ControlCollection_ControlAlreadyHasParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon expected after directive name! E.g. @viewmodel: Redwood.Samples.Sample1.IndexViewModel.
        /// </summary>
        internal static string Directive_ColonExpected {
            get {
                return ResourceManager.GetString("Directive_ColonExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected after directive! E.g. @viewmodel: Redwood.Samples.Sample1.IndexViewModel.
        /// </summary>
        internal static string Directive_IdentifierExpected {
            get {
                return ResourceManager.GetString("Directive_IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute name expected! E.g. &lt;div class=&apos;value&apos; ....
        /// </summary>
        internal static string Element_AttributeNameExpected {
            get {
                return ResourceManager.GetString("Element_AttributeNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected after colon in the name! E.g. &lt;rw:textbox ....
        /// </summary>
        internal static string Element_IdentifierExpectedAfterColonInTagName {
            get {
                return ResourceManager.GetString("Element_IdentifierExpectedAfterColonInTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected after tag opening brace! E.g. &lt;html ....
        /// </summary>
        internal static string Element_IdentifierExpectedAfterTagOpenBrace {
            get {
                return ResourceManager.GetString("Element_IdentifierExpectedAfterTagOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End tag brace expected!.
        /// </summary>
        internal static string Element_TagNotClosed {
            get {
                return ResourceManager.GetString("Element_TagNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HtmlWriter cannot close the tag because no tag is open!.
        /// </summary>
        internal static string HtmlWriter_CannotCloseTagBecauseNoTagIsOpen {
            get {
                return ResourceManager.GetString("HtmlWriter_CannotCloseTagBecauseNoTagIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closing tag &apos;&lt;/{0}&gt;&apos; doesn&apos;t have a matching opening tag!.
        /// </summary>
        internal static string Parser_ClosingTagHasNoMatchingOpenTag {
            get {
                return ResourceManager.GetString("Parser_ClosingTagHasNoMatchingOpenTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser could not continue due to errors in the file..
        /// </summary>
        internal static string ParsingInterrupted {
            get {
                return ResourceManager.GetString("ParsingInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of input!.
        /// </summary>
        internal static string UnexpectedEndOfInput {
            get {
                return ResourceManager.GetString("UnexpectedEndOfInput", resourceCulture);
            }
        }
    }
}
