using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DotVVM.Framework.Compilation.Parser.Binding.Tokenizer
{
    public static class TokenTypeDisplay
    {
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        public static string ToDisplayString(this BindingTokenType tokenType)
        {
            return tokenType switch {
                BindingTokenType.WhiteSpace                => " ",
                BindingTokenType.EscapedIdentifier         => "@",
                BindingTokenType.Identifier                => "Identifier",
                BindingTokenType.Dot                       => ".",
                BindingTokenType.Comma                     => ",",
                BindingTokenType.OpenParenthesis           => "(",
                BindingTokenType.CloseParenthesis          => ")",
                BindingTokenType.OpenArrayBrace            => "[",
                BindingTokenType.CloseArrayBrace           => "]",
                BindingTokenType.AddOperator               => "+",
                BindingTokenType.SubtractOperator          => "-",
                BindingTokenType.MultiplyOperator          => "*",
                BindingTokenType.DivideOperator            => "/",
                BindingTokenType.ModulusOperator           => "%",
                BindingTokenType.UnsupportedOperator       => "UnsupportedOp",
                BindingTokenType.EqualsEqualsOperator      => "==",
                BindingTokenType.LessThanOperator          => "<",
                BindingTokenType.LessThanEqualsOperator    => "<=",
                BindingTokenType.GreaterThanOperator       => ">",
                BindingTokenType.GreaterThanEqualsOperator => ">=",
                BindingTokenType.NotEqualsOperator         => "!=",
                BindingTokenType.NotOperator               => "!",
                BindingTokenType.OnesComplementOperator    => "~",
                BindingTokenType.StringLiteralToken        => "Literal",
                BindingTokenType.InterpolatedStringToken   => "InterpolatedString",
                BindingTokenType.NullCoalescingOperator    => "??",
                BindingTokenType.QuestionMarkOperator      => "?",
                BindingTokenType.ColonOperator             => ":",
                BindingTokenType.AndOperator               => "&",
                BindingTokenType.ExclusiveOrOperator       => "^",
                BindingTokenType.AndAlsoOperator           => "&&",
                BindingTokenType.OrOperator                => "|",
                BindingTokenType.OrElseOperator            => "||",
                BindingTokenType.AssignOperator            => "=",
                BindingTokenType.LambdaOperator            => "=>",
                BindingTokenType.Semicolon                 => ";",
                BindingTokenType.KeywordAbstract           => "abstract",
                BindingTokenType.KeywordAs                 => "as",
                BindingTokenType.KeywordBase               => "base",
                BindingTokenType.KeywordBool               => "bool",
                BindingTokenType.KeywordBreak              => "break",
                BindingTokenType.KeywordByte               => "byte",
                BindingTokenType.KeywordCase               => "case",
                BindingTokenType.KeywordCatch              => "catch",
                BindingTokenType.KeywordChar               => "char",
                BindingTokenType.KeywordChecked            => "checked",
                BindingTokenType.KeywordClass              => "class",
                BindingTokenType.KeywordConst              => "const",
                BindingTokenType.KeywordContinue           => "continue",
                BindingTokenType.KeywordDecimal            => "decimal",
                BindingTokenType.KeywordDefault            => "default",
                BindingTokenType.KeywordDelegate           => "delegate",
                BindingTokenType.KeywordDo                 => "do",
                BindingTokenType.KeywordDouble             => "double",
                BindingTokenType.KeywordElse               => "else",
                BindingTokenType.KeywordEnum               => "enum",
                BindingTokenType.KeywordEvent              => "event",
                BindingTokenType.KeywordExplicit           => "explicit",
                BindingTokenType.KeywordExtern             => "extern",
                BindingTokenType.KeywordFalse              => "false",
                BindingTokenType.KeywordFinally            => "finally",
                BindingTokenType.KeywordFixed              => "fixed",
                BindingTokenType.KeywordFloat              => "float",
                BindingTokenType.KeywordFor                => "for",
                BindingTokenType.KeywordForeach            => "foreach",
                BindingTokenType.KeywordGoto               => "goto",
                BindingTokenType.KeywordIf                 => "if",
                BindingTokenType.KeywordImplicit           => "implicit",
                BindingTokenType.KeywordIn                 => "in",
                BindingTokenType.KeywordInt                => "int",
                BindingTokenType.KeywordInterface          => "interface",
                BindingTokenType.KeywordInternal           => "internal",
                BindingTokenType.KeywordIs                 => "is",
                BindingTokenType.KeywordLock               => "lock",
                BindingTokenType.KeywordLong               => "long",
                BindingTokenType.KeywordNamespace          => "namespace",
                BindingTokenType.KeywordNew                => "new",
                BindingTokenType.KeywordNull               => "null",
                BindingTokenType.KeywordObject             => "object",
                BindingTokenType.KeywordOperator           => "operator",
                BindingTokenType.KeywordOut                => "out",
                BindingTokenType.KeywordOverride           => "override",
                BindingTokenType.KeywordParams             => "params",
                BindingTokenType.KeywordPrivate            => "private",
                BindingTokenType.KeywordProtected          => "protected",
                BindingTokenType.KeywordPublic             => "public",
                BindingTokenType.KeywordReadonly           => "readonly",
                BindingTokenType.KeywordRef                => "ref",
                BindingTokenType.KeywordReturn             => "return",
                BindingTokenType.KeywordSbyte              => "sbyte",
                BindingTokenType.KeywordSealed             => "sealed",
                BindingTokenType.KeywordShort              => "short",
                BindingTokenType.KeywordSizeof             => "sizeof",
                BindingTokenType.KeywordStackalloc         => "stackalloc",
                BindingTokenType.KeywordStatic             => "static",
                BindingTokenType.KeywordString             => "string",
                BindingTokenType.KeywordStruct             => "struct",
                BindingTokenType.KeywordSwitch             => "switch",
                BindingTokenType.KeywordThis               => "this",
                BindingTokenType.KeywordThrow              => "throw",
                BindingTokenType.KeywordTrue               => "true",
                BindingTokenType.KeywordTry                => "try",
                BindingTokenType.KeywordTypeof             => "typeof",
                BindingTokenType.KeywordUint               => "uint",
                BindingTokenType.KeywordUlong              => "ulong",
                BindingTokenType.KeywordUnchecked          => "unchecked",
                BindingTokenType.KeywordUnsafe             => "unsafe",
                BindingTokenType.KeywordUshort             => "ushort",
                BindingTokenType.KeywordUsing              => "using",
                BindingTokenType.KeywordVirtual            => "virtual",
                BindingTokenType.KeywordVoid               => "void",
                BindingTokenType.KeywordVolatile           => "volatile",
                BindingTokenType.KeywordWhile              => "while",
                _ => "Unknown",
            };
        }

    }
}
